// Generated by Copilot
import React, { useEffect, useMemo, useRef, useState } from 'react';

import { getDisplayToothNumber, getToothNumberingLegend, type DentalNumberingSystem } from '@/lib/dental-numbering';
import { getRestorationColor, getRestorationLabel, type DentalConnectorCandidate } from '@/lib/dental-workflow';
import { cn } from '@/lib/utils';
import type { TlantiToothState } from '@/stores/tlantidb-case-store';

interface InteractiveOdontogramProps {
  toothMap: Record<string, TlantiToothState>;
  numberingSystem: DentalNumberingSystem;
  connectors?: DentalConnectorCandidate[];
  onToothClick: (
    toothNumber: string,
    mode: 'primary' | 'antagonist',
    interaction?: { additive: boolean; shift: boolean; meta: boolean; ctrl: boolean },
  ) => void;
  onToothHoverChange?: (toothNumber: string | null) => void;
  className?: string;
  width?: number | string;
  height?: number | string;
}

const DEFAULT_COLOR = '#2f2f2f';
const HOVER_COLOR = '#5b9bf6';
function getToothFill(state?: TlantiToothState) {
  return state?.selected ? getRestorationColor(state.restorationType, state.antagonist) : DEFAULT_COLOR;
}

function getToothTooltip(toothNumber: string, numberingSystem: DentalNumberingSystem, state?: TlantiToothState) {
  if (!state?.selected) {
    return getToothNumberingLegend(toothNumber, numberingSystem);
  }

  const parts = [
    getToothNumberingLegend(toothNumber, numberingSystem),
    getRestorationLabel(state.restorationType),
    state.material,
    state.shade,
  ].filter(Boolean);

  return parts.join(' · ');
}

export function InteractiveOdontogram({
  toothMap,
  numberingSystem,
  connectors = [],
  onToothClick,
  onToothHoverChange,
  className,
  width = '100%',
  height = '100%',
}: InteractiveOdontogramProps) {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const pathsRef = useRef<Record<string, SVGPathElement>>({});
  const centersRef = useRef<Record<string, { x: number; y: number }>>({});
  const boundsRef = useRef<Record<string, DOMRect | SVGRect>>({});
  const overlaysRef = useRef<{ connectors?: SVGGElement | null; shades?: SVGGElement | null; numbering?: SVGGElement | null }>({});
  const tooltipRef = useRef<HTMLDivElement | null>(null);
  const connectorsRef = useRef(connectors);
  const toothMapRef = useRef(toothMap);
  const onToothClickRef = useRef(onToothClick);
  const onToothHoverChangeRef = useRef(onToothHoverChange);
  const [loadFailed, setLoadFailed] = useState(false);

  const normalizedMap = useMemo(() => toothMap, [toothMap]);

  const isToothVisible = useMemo(() => {
    return (toothNumber: string) => /^[1-4]/.test(toothNumber);
  }, []);

  useEffect(() => {
    connectorsRef.current = connectors;
    toothMapRef.current = normalizedMap;
    onToothClickRef.current = onToothClick;
    onToothHoverChangeRef.current = onToothHoverChange;
  }, [connectors, normalizedMap, onToothClick, onToothHoverChange]);

  useEffect(() => {
    const tooltip = document.createElement('div');
    tooltip.className = 'pointer-events-none fixed z-50 rounded-md border border-border bg-surface px-2 py-1 text-[11px] font-mono uppercase tracking-widest text-text-primary shadow-lg';
    tooltip.style.display = 'none';
    document.body.appendChild(tooltip);
    tooltipRef.current = tooltip;

    return () => {
      tooltip.remove();
    };
  }, []);

  useEffect(() => {
    const renderOverlays = () => {
      const connectorLayer = overlaysRef.current.connectors;
      const shadeLayer = overlaysRef.current.shades;
      const numberingLayer = overlaysRef.current.numbering;

      if (connectorLayer) {
        connectorLayer.innerHTML = '';
        connectorsRef.current.filter((item) => item.active && item.canConnect).forEach((connector) => {
          const fromCenter = centersRef.current[`tooth-${connector.fromTooth}`];
          const toCenter = centersRef.current[`tooth-${connector.toTooth}`];
          if (!fromCenter || !toCenter) {
            return;
          }

          const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
          line.setAttribute('x1', String(fromCenter.x));
          line.setAttribute('y1', String(fromCenter.y));
          line.setAttribute('x2', String(toCenter.x));
          line.setAttribute('y2', String(toCenter.y));
          line.setAttribute('stroke', '#d4a843');
          line.setAttribute('stroke-width', connector.span.length ? '3' : '2');
          line.setAttribute('stroke-linecap', 'round');
          line.setAttribute('opacity', '0.9');
          connectorLayer.appendChild(line);
        });
      }

      if (shadeLayer) {
        shadeLayer.innerHTML = '';
        Object.entries(toothMapRef.current).forEach(([id, state]) => {
          if (!state.selected || !state.shade) {
            return;
          }

          const center = centersRef.current[id];
          if (!center) {
            return;
          }

          const badge = document.createElementNS('http://www.w3.org/2000/svg', 'text');
          badge.setAttribute('x', String(center.x));
          badge.setAttribute('y', String(center.y + 6));
          badge.setAttribute('text-anchor', 'middle');
          badge.setAttribute('font-size', '8');
          badge.setAttribute('font-family', 'system-ui, sans-serif');
          badge.setAttribute('font-weight', '700');
          badge.setAttribute('fill', '#111111');
          badge.textContent = state.shade;
          shadeLayer.appendChild(badge);
        });
      }

      if (numberingLayer) {
        numberingLayer.innerHTML = '';
        Object.keys(pathsRef.current).forEach((id) => {
          const toothNumber = id.replace('tooth-', '');
          const center = centersRef.current[id];
          const bounds = boundsRef.current[id];
          if (!center || !bounds) {
            return;
          }

          const label = document.createElementNS('http://www.w3.org/2000/svg', 'text');
          label.setAttribute('x', String(center.x));
          label.setAttribute('y', String(bounds.y - 4));
          label.setAttribute('text-anchor', 'middle');
          label.setAttribute('font-size', '8');
          label.setAttribute('font-family', 'system-ui, sans-serif');
          label.setAttribute('font-weight', '700');
          label.setAttribute('fill', '#e8e8e8');
          label.setAttribute('stroke', '#111111');
          label.setAttribute('stroke-width', '1.4');
          label.setAttribute('paint-order', 'stroke');
          label.textContent = getDisplayToothNumber(toothNumber, numberingSystem);
          numberingLayer.appendChild(label);
        });
      }
    };

    const applyPathStyles = () => {
      Object.entries(pathsRef.current).forEach(([id, path]) => {
        const state = toothMapRef.current[id];
        path.style.fill = getToothFill(state);
        path.style.stroke = '#3d3d3d';
        path.style.strokeWidth = '1';
      });

      renderOverlays();
    };

    const loadSvg = async () => {
      try {
        const response = await fetch('/odontogram/teeth-selection.svg');
        if (!response.ok) {
          throw new Error(`Odontogram SVG failed with ${response.status}`);
        }
        const svgText = await response.text();

        if (!containerRef.current) {
          return;
        }

        containerRef.current.innerHTML = svgText;
        const svgElement = containerRef.current.querySelector('svg');
        if (!svgElement) {
          throw new Error('Odontogram SVG did not contain an svg element');
        }
        setLoadFailed(false);

        svgElement.setAttribute('width', '100%');
      svgElement.setAttribute('height', '100%');
      svgElement.setAttribute('viewBox', '0 0 346.85 468.26');
      svgElement.style.width = '100%';
      svgElement.style.height = '100%';
      svgElement.style.overflow = 'hidden';

      const paths = Array.from(svgElement.querySelectorAll('path'));
      pathsRef.current = {};
      centersRef.current = {};

      const connectorLayer = document.createElementNS('http://www.w3.org/2000/svg', 'g');
      const shadeLayer = document.createElementNS('http://www.w3.org/2000/svg', 'g');
      const numberingLayer = document.createElementNS('http://www.w3.org/2000/svg', 'g');
      connectorLayer.setAttribute('data-layer', 'connectors');
      shadeLayer.setAttribute('data-layer', 'shades');
      numberingLayer.setAttribute('data-layer', 'numbering');
      svgElement.appendChild(connectorLayer);
      svgElement.appendChild(shadeLayer);
      svgElement.appendChild(numberingLayer);
      overlaysRef.current = { connectors: connectorLayer, shades: shadeLayer, numbering: numberingLayer };

      paths.forEach((path) => {
        const toothNumber = path.id;
        const id = `tooth-${toothNumber}`;
        const visible = isToothVisible(toothNumber);
        path.setAttribute('id', id);
        path.style.display = visible ? 'block' : 'none';

        if (!visible) {
          return;
        }

        path.style.cursor = 'pointer';
        path.style.transition = 'fill 150ms ease-out, transform 150ms ease-out';
        path.style.transformOrigin = 'center';
        pathsRef.current[id] = path;

        const bbox = path.getBBox();
        centersRef.current[id] = { x: bbox.x + bbox.width / 2, y: bbox.y + bbox.height / 2 };
        boundsRef.current[id] = bbox;
        const hitArea = document.createElementNS('http://www.w3.org/2000/svg', 'rect');
        hitArea.setAttribute('x', String(bbox.x - 2));
        hitArea.setAttribute('y', String(bbox.y - 2));
        hitArea.setAttribute('width', String(bbox.width + 4));
        hitArea.setAttribute('height', String(bbox.height + 4));
        hitArea.setAttribute('fill', 'transparent');
        hitArea.setAttribute('role', 'button');
        hitArea.setAttribute('tabindex', '0');
        hitArea.setAttribute('aria-label', `Tooth ${getDisplayToothNumber(toothNumber, numberingSystem)}`);
        hitArea.style.cursor = 'pointer';
        hitArea.style.touchAction = 'manipulation';

        hitArea.addEventListener('mouseenter', (event) => {
          if (!toothMapRef.current[id]?.selected) {
            path.style.fill = HOVER_COLOR;
          }
          path.style.transform = 'scale(1.01)';
          onToothHoverChangeRef.current?.(toothNumber);
          if (tooltipRef.current) {
            tooltipRef.current.textContent = getToothTooltip(toothNumber, numberingSystem, toothMapRef.current[id]);
            tooltipRef.current.style.display = 'block';
            tooltipRef.current.style.left = `${event.clientX + 8}px`;
            tooltipRef.current.style.top = `${event.clientY - 24}px`;
          }
        });

        hitArea.addEventListener('mousemove', (event) => {
          if (tooltipRef.current) {
            tooltipRef.current.style.left = `${event.clientX + 8}px`;
            tooltipRef.current.style.top = `${event.clientY - 24}px`;
          }
        });

        hitArea.addEventListener('mouseleave', () => {
          const state = toothMapRef.current[id];
          path.style.fill = getToothFill(state);
          path.style.transform = 'scale(1)';
          onToothHoverChangeRef.current?.(null);
          if (tooltipRef.current) {
            tooltipRef.current.style.display = 'none';
          }
        });

        hitArea.addEventListener('click', (event) => {
          onToothClickRef.current(toothNumber, event.shiftKey ? 'antagonist' : 'primary', {
            additive: event.metaKey || event.ctrlKey,
            shift: event.shiftKey,
            meta: event.metaKey,
            ctrl: event.ctrlKey,
          });
        });

        hitArea.addEventListener('keydown', (event) => {
          if (event.key !== 'Enter' && event.key !== ' ') {
            return;
          }

          event.preventDefault();
          onToothClickRef.current(toothNumber, event.shiftKey ? 'antagonist' : 'primary', {
            additive: event.metaKey || event.ctrlKey,
            shift: event.shiftKey,
            meta: event.metaKey,
            ctrl: event.ctrlKey,
          });
        });

        path.parentNode?.insertBefore(hitArea, path.nextSibling);
      });

        applyPathStyles();
      } catch (error) {
        console.warn('[tlantidb] odontogram svg fallback active', error);
        setLoadFailed(true);
      }
    };

    loadSvg();
  }, [isToothVisible, numberingSystem]);

  useEffect(() => {
    Object.entries(pathsRef.current).forEach(([id, path]) => {
      const state = normalizedMap[id];
      path.style.fill = getToothFill(state);
    });
    overlaysRef.current.connectors && (overlaysRef.current.connectors.innerHTML = '');
    overlaysRef.current.shades && (overlaysRef.current.shades.innerHTML = '');
    overlaysRef.current.numbering && (overlaysRef.current.numbering.innerHTML = '');
    connectors.filter((item) => item.active && item.canConnect).forEach((connector) => {
      const fromCenter = centersRef.current[`tooth-${connector.fromTooth}`];
      const toCenter = centersRef.current[`tooth-${connector.toTooth}`];
      if (!fromCenter || !toCenter || !overlaysRef.current.connectors) {
        return;
      }
      const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
      line.setAttribute('x1', String(fromCenter.x));
      line.setAttribute('y1', String(fromCenter.y));
      line.setAttribute('x2', String(toCenter.x));
      line.setAttribute('y2', String(toCenter.y));
      line.setAttribute('stroke', '#d4a843');
      line.setAttribute('stroke-width', connector.span.length ? '3' : '2');
      line.setAttribute('stroke-linecap', 'round');
      line.setAttribute('opacity', '0.9');
      overlaysRef.current.connectors.appendChild(line);
    });

    Object.entries(normalizedMap).forEach(([id, state]) => {
      if (!state.selected || !state.shade || !overlaysRef.current.shades) {
        return;
      }
      const center = centersRef.current[id];
      if (!center) {
        return;
      }
      const badge = document.createElementNS('http://www.w3.org/2000/svg', 'text');
      badge.setAttribute('x', String(center.x));
      badge.setAttribute('y', String(center.y + 6));
      badge.setAttribute('text-anchor', 'middle');
      badge.setAttribute('font-size', '8');
      badge.setAttribute('font-family', 'system-ui, sans-serif');
      badge.setAttribute('font-weight', '700');
      badge.setAttribute('fill', '#111111');
      badge.textContent = state.shade;
      overlaysRef.current.shades.appendChild(badge);
    });

    Object.keys(pathsRef.current).forEach((id) => {
      if (!overlaysRef.current.numbering) {
        return;
      }

      const toothNumber = id.replace('tooth-', '');
      const center = centersRef.current[id];
      const bounds = boundsRef.current[id];
      if (!center || !bounds) {
        return;
      }

      const label = document.createElementNS('http://www.w3.org/2000/svg', 'text');
      label.setAttribute('x', String(center.x));
      label.setAttribute('y', String(bounds.y - 4));
      label.setAttribute('text-anchor', 'middle');
      label.setAttribute('font-size', '8');
      label.setAttribute('font-family', 'system-ui, sans-serif');
      label.setAttribute('font-weight', '700');
      label.setAttribute('fill', '#e8e8e8');
      label.setAttribute('stroke', '#111111');
      label.setAttribute('stroke-width', '1.4');
      label.setAttribute('paint-order', 'stroke');
      label.textContent = getDisplayToothNumber(toothNumber, numberingSystem);
      overlaysRef.current.numbering.appendChild(label);
    });
  }, [connectors, normalizedMap, numberingSystem]);

  if (loadFailed) {
    return (
      <img
        src="/odontogram/teeth-selection.svg"
        alt="Dental odontogram"
        className={cn('mx-auto aspect-[346.85/468.26] w-full max-w-[34rem] object-contain', className)}
        style={{ width, height }}
      />
    );
  }

  return (
    <div
      ref={containerRef}
      className={cn('mx-auto aspect-[346.85/468.26] w-full max-w-[34rem] overflow-hidden', className)}
      style={{ width, height }}
    />
  );
}
