// Generated by Copilot
import React, { useState } from 'react';
import { BrainCircuit, Cpu, Gauge, HardDrive, Play, RefreshCw, Sparkles } from 'lucide-react';

import { Badge } from '@/components/ui/badge';
import { Switch } from '@/components/ui/interfaces-switch';
import type { PythonBridgeStatus, SystemRuntimeReport } from '@/lib/backend-integrations';
import { buildPythonRoutingPreview } from '@/lib/python-workflow-router';
import type { TlantiDbPerformanceProfile } from '@/stores/tlantidb-case-store';
import { cn } from '@/lib/utils';
import {
  cadComputeRunBoundaryBench,
  type BoundaryBenchProfile,
  type EnergyMode,
} from '@/lib/cad-real-bridge';

interface SystemRuntimeSettingsPanelProps {
  report: SystemRuntimeReport | null;
  pythonBridge: PythonBridgeStatus | null;
  loading: boolean;
  error: string | null;
  profile: TlantiDbPerformanceProfile;
  onRefresh: () => void;
  onToggleAutoMode: (checked: boolean) => void;
  onApplyRecommended: () => void;
}

function toneForScore(score: number) {
  if (score >= 80) return 'text-emerald-300';
  if (score >= 60) return 'text-sky-300';
  if (score >= 40) return 'text-amber-300';
  return 'text-rose-300';
}

function MetricCard({ label, value, helper }: { label: string; value: string; helper?: string }) {
  return (
    <div className="rounded-2xl border border-border bg-surface-raised px-3 py-3">
      <p className="text-[11px] uppercase text-text-secondary">{label}</p>
      <p className="mt-1 text-sm font-semibold text-text-display tabular-nums">{value}</p>
      {helper ? <p className="mt-1 text-xs text-text-secondary text-pretty">{helper}</p> : null}
    </div>
  );
}

function formatBytes(bytes: number) {
  if (!Number.isFinite(bytes) || bytes <= 0) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  let value = bytes;
  let unitIndex = 0;
  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024;
    unitIndex += 1;
  }
  return `${value.toFixed(value >= 10 || unitIndex === 0 ? 0 : 1)} ${units[unitIndex]}`;
}

function formatMs(value: number) {
  return `${value.toFixed(value >= 10 ? 1 : 2)} ms`;
}

export function SystemRuntimeSettingsPanel({
  report,
  pythonBridge,
  loading,
  error,
  profile,
  onRefresh,
  onToggleAutoMode,
  onApplyRecommended,
}: SystemRuntimeSettingsPanelProps) {
  const recommended = report?.aiWorkload.recommendedSettings;
  const scores = report?.aiWorkload.workloadScores;
  const memoryGb = report ? `${(report.system.memory.totalBytes / (1024 ** 3)).toFixed(1)} GB` : '—';
  const gpuName = report?.system.gpus[0]?.name ?? 'No discrete GPU reported';
  const activeProfileSummary = `${profile.renderQuality} · ${profile.dicomCacheMb} MB cache · ${profile.maxConcurrentImports} imports`;
  const readyPythonWorkflows = pythonBridge?.workflows.filter((workflow) => workflow.ready) ?? [];
  const routingPreview = buildPythonRoutingPreview(pythonBridge);
  const [boundaryBench, setBoundaryBench] = useState<BoundaryBenchProfile | null>(null);
  const [boundaryBenchPath, setBoundaryBenchPath] = useState<string | null>(null);
  const [boundaryBenchLoading, setBoundaryBenchLoading] = useState(false);
  const [boundaryBenchError, setBoundaryBenchError] = useState<string | null>(null);

  const runBoundaryBench = async () => {
    setBoundaryBenchLoading(true);
    setBoundaryBenchError(null);
    try {
      const energyMode: EnergyMode = profile.renderQuality === 'low' ? 'low-power' : 'performance';
      const response = await cadComputeRunBoundaryBench({
        sampleVertices: 4096,
        energyMode,
      });
      setBoundaryBench(response.profile);
      setBoundaryBenchPath(response.profilePath);
    } catch (error) {
      setBoundaryBenchError(error instanceof Error ? error.message : 'Compute boundary benchmark requires the Tauri desktop runtime.');
    } finally {
      setBoundaryBenchLoading(false);
    }
  };

  return (
    <div className="rounded-2xl border border-border bg-card p-4">
      <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
        <div>
          <div className="flex items-center gap-2">
            <BrainCircuit className="size-4 text-text-display" />
            <h4 className="text-sm font-semibold text-text-primary text-balance">Adaptive runtime profile</h4>
          </div>
          <p className="mt-2 text-sm text-text-secondary text-pretty">
            Reads the desktop runtime report and keeps AI, render and DICOM cache tuned to the current workstation.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Badge variant="outline">{loading ? 'Refreshing…' : profile.mode === 'auto' ? 'Auto mode' : 'Manual mode'}</Badge>
          {report ? <Badge variant="outline">{report.system.capabilities.recommendedRenderQuality}</Badge> : null}
        </div>
      </div>

      <div className="mt-4 flex items-center justify-between gap-4 rounded-2xl border border-border bg-surface px-4 py-3">
        <div>
          <p className="text-sm text-text-primary">Auto-apply machine profile</p>
          <p className="mt-1 text-xs text-text-secondary text-pretty">
            When enabled, the TlantiCAD Workspace reapplies the recommended AI/render/cache profile for this hardware.
          </p>
        </div>
        <Switch checked={profile.mode === 'auto'} onCheckedChange={onToggleAutoMode} aria-label="Toggle adaptive runtime profile" />
      </div>

      <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
        <MetricCard label="Current profile" value={profile.renderQuality} helper={activeProfileSummary} />
        <MetricCard label="GPU inference" value={profile.enableGpuInference ? 'Enabled' : 'Disabled'} helper={profile.enableCbctViewer ? 'CBCT viewer allowed' : 'CBCT viewer limited'} />
        <MetricCard label="3D viewer" value={profile.enable3dViewer ? 'Enabled' : 'Reduced'} helper={`Thumbnails: ${profile.thumbnailQuality}`} />
        <MetricCard label="Last auto-apply" value={profile.lastAutoAppliedAt ? new Date(profile.lastAutoAppliedAt).toLocaleString() : 'Not applied yet'} />
      </div>

      <div className="mt-4 flex flex-wrap gap-2">
        <button
          type="button"
          onClick={onRefresh}
          className="inline-flex items-center gap-2 rounded-2xl border border-border bg-surface px-3 py-2 text-sm text-text-primary transition-colors hover:bg-surface-raised"
        >
          <RefreshCw className={cn('size-4', loading && 'animate-spin')} />
          Refresh runtime report
        </button>
        <button
          type="button"
          onClick={onApplyRecommended}
          disabled={!recommended}
          className={cn(
            'inline-flex items-center gap-2 rounded-2xl border px-3 py-2 text-sm transition-colors',
            recommended
              ? 'border-border bg-surface text-text-primary hover:bg-surface-raised'
              : 'cursor-not-allowed border-border bg-card text-text-disabled',
          )}
        >
          <Sparkles className="size-4" />
          Apply recommended profile
        </button>
      </div>

      {error ? (
        <p className="mt-3 text-sm text-rose-300 text-pretty">{error}</p>
      ) : null}

      {!report && !loading ? (
        <div className="mt-4 rounded-2xl border border-dashed border-border px-4 py-5 text-sm text-text-secondary">
          No runtime report loaded yet. Refresh the runtime report to inspect the workstation and apply the recommended profile.
        </div>
      ) : null}

      {report ? (
        <div className="mt-4 grid gap-4 xl:grid-cols-[1.05fr_0.95fr]">
          <div className="rounded-2xl border border-border bg-surface px-4 py-4">
            <div className="mb-3 flex items-center gap-2">
              <Cpu className="size-4 text-text-secondary" />
              <p className="text-xs uppercase text-text-secondary">Machine snapshot</p>
            </div>
            <div className="grid gap-3 md:grid-cols-2">
              <MetricCard label="OS" value={`${report.system.os.name} ${report.system.os.version}`} helper={report.system.os.arch} />
              <MetricCard label="CPU" value={report.system.cpu.brand || 'Unknown CPU'} helper={`${report.system.cpu.cores} cores · ${report.system.cpu.frequencyMhz} MHz`} />
              <MetricCard label="Memory" value={memoryGb} helper={`${report.system.memory.usagePercent.toFixed(1)}% in use`} />
              <MetricCard label="Primary GPU" value={gpuName} helper={report.system.capabilities.metalSupported ? 'Metal available' : report.system.capabilities.vulkanSupported ? 'Vulkan available' : 'Basic graphics path'} />
            </div>
          </div>

          <div className="rounded-2xl border border-border bg-surface px-4 py-4">
            <div className="mb-3 flex items-center gap-2">
              <HardDrive className="size-4 text-text-secondary" />
              <p className="text-xs uppercase text-text-secondary">AI / render workload</p>
            </div>
            <div className="grid gap-3 md:grid-cols-2">
              <div className="rounded-2xl border border-border bg-surface-raised px-3 py-3 md:col-span-2">
                <p className="text-[11px] uppercase text-text-secondary">Overall workstation score</p>
                <p className={cn('mt-1 text-2xl font-semibold tabular-nums', toneForScore(scores?.overall ?? 0))}>{scores?.overall ?? 0}/100</p>
              </div>
              <MetricCard label="DICOM" value={`${scores?.dicomViewing ?? 0}/100`} />
              <MetricCard label="CBCT / 3D" value={`${scores?.cbct3d ?? 0}/100`} />
              <MetricCard label="AI inference" value={`${scores?.aiInference ?? 0}/100`} />
              <MetricCard label="Mesh / PACS" value={`${Math.round(((scores?.meshGeneration ?? 0) + (scores?.pacsStorage ?? 0)) / 2)}/100`} />
            </div>
          </div>
        </div>
      ) : null}

      <div className="mt-4 rounded-2xl border border-border bg-surface px-4 py-4">
        <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
          <div>
            <div className="flex items-center gap-2">
              <Gauge className="size-4 text-text-secondary" />
              <p className="text-xs uppercase text-text-secondary">Renderer → Rust compute boundary</p>
            </div>
            <p className="mt-2 text-sm text-text-primary text-pretty">
              Measures JSON IPC cost versus local Rust mesh compute so the CAD shell can decide what stays in Three.js and what becomes a Rust/wgpu job.
            </p>
          </div>
          <button
            type="button"
            onClick={() => { void runBoundaryBench(); }}
            disabled={boundaryBenchLoading}
            className={cn(
              'inline-flex items-center gap-2 rounded-2xl border border-border bg-card px-3 py-2 text-sm text-text-primary transition-colors hover:bg-surface-raised',
              boundaryBenchLoading && 'cursor-wait opacity-70',
            )}
          >
            {boundaryBenchLoading ? <RefreshCw className="size-4 animate-spin" /> : <Play className="size-4" />}
            Run boundary bench
          </button>
        </div>

        {boundaryBenchError ? (
          <p className="mt-3 text-sm text-amber-300 text-pretty">{boundaryBenchError}</p>
        ) : null}

        {boundaryBench ? (
          <>
            <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
              <MetricCard label="Recommendation" value={boundaryBench.recommendedBoundary} helper={`${boundaryBench.sampleVertices.toLocaleString()} vertices / ${boundaryBench.sampleTriangles.toLocaleString()} triangles`} />
              <MetricCard label="JSON IPC payload" value={formatBytes(boundaryBench.jsonIpcBytes)} helper={`${boundaryBench.ipcPayloadRatio.toFixed(0)}x bigger than transform-only IPC`} />
              <MetricCard label="CPU smooth" value={formatMs(boundaryBench.cpuSmoothMs)} helper={`${boundaryBench.cpuItemsPerMs.toFixed(0)} vertices/ms`} />
              <MetricCard label="GPU buffer estimate" value={formatBytes(boundaryBench.meshBufferBytes)} helper={`Frame budget ${boundaryBench.frameBudgetMs.toFixed(0)} ms`} />
            </div>
            <div className="mt-3 rounded-2xl border border-border bg-surface-raised px-3 py-3">
              <p className="text-[11px] uppercase text-text-secondary">Measured operations</p>
              <div className="mt-2 grid gap-2 xl:grid-cols-3">
                {boundaryBench.results.map((result) => (
                  <div key={`${result.op}-${result.owner}`} className="rounded-xl border border-border bg-card px-3 py-3">
                    <p className="text-sm font-semibold text-text-display">{result.op}</p>
                    <p className="mt-1 text-xs text-text-secondary">{result.owner} · {formatMs(result.elapsedMs)} · {formatBytes(result.payloadBytes)}</p>
                  </div>
                ))}
              </div>
              <div className="mt-3 space-y-1 text-xs text-text-secondary">
                {boundaryBench.notes.map((note) => <p key={note}>{note}</p>)}
              </div>
              {boundaryBenchPath ? <p className="mt-3 break-all text-[11px] text-text-secondary">Profile: {boundaryBenchPath}</p> : null}
            </div>
          </>
        ) : (
          <div className="mt-4 rounded-2xl border border-dashed border-border px-4 py-4 text-sm text-text-secondary">
            No boundary profile yet. Run the bench in the desktop app before moving kernels to wgpu.
          </div>
        )}
      </div>

      {recommended ? (
        <div className="mt-4 rounded-2xl border border-border bg-surface px-4 py-4">
          <div className="mb-3 flex items-center justify-between gap-3">
            <div>
              <p className="text-xs uppercase text-text-secondary">Recommended machine profile</p>
              <p className="text-sm text-text-primary text-pretty">These values come directly from the runtime report generated on this workstation.</p>
            </div>
            <Badge variant="outline">{report?.route}</Badge>
          </div>
          <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
            <MetricCard label="Render" value={recommended.renderQuality} helper={`Max texture ${recommended.maxTextureSize}`} />
            <MetricCard label="DICOM cache" value={`${recommended.dicomCacheMb} MB`} helper={`${recommended.maxConcurrentImports} concurrent imports`} />
            <MetricCard label="AI" value={recommended.enableGpuInference ? 'GPU inference on' : 'CPU fallback'} helper={recommended.enableCbctViewer ? 'CBCT viewer enabled' : 'CBCT viewer limited'} />
            <MetricCard label="Thumbnails" value={recommended.thumbnailQuality} helper={recommended.enable3dViewer ? '3D viewer enabled' : '3D viewer reduced'} />
          </div>
        </div>
      ) : null}

      {pythonBridge ? (
        <div className="mt-4 rounded-2xl border border-border bg-surface px-4 py-4">
          <div className="mb-3 flex items-center justify-between gap-3">
            <div>
              <p className="text-xs uppercase text-text-secondary">Python / AI workflow runtime</p>
              <p className="text-sm text-text-primary text-pretty">Provisioned vendors, models and local site-packages for dental segmentation and labeling.</p>
            </div>
            <Badge variant="outline">{pythonBridge.pythonAvailable ? pythonBridge.bridgeMode : 'runtime missing'}</Badge>
          </div>

          <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
            <MetricCard label="Python" value={pythonBridge.pythonVersion ?? 'Unavailable'} helper={pythonBridge.pythonExecutable ?? 'No interpreter resolved'} />
            <MetricCard label="PyO3" value={pythonBridge.pyo3Enabled ? 'Embedded enabled' : 'Sidecar / external'} helper={pythonBridge.pythonHome ?? 'No python home'} />
            <MetricCard label="Workflows ready" value={`${readyPythonWorkflows.length}/${pythonBridge.workflows.length}`} helper="Dental workflows with runtime + vendors present" />
            <MetricCard label="Vendors" value={`${pythonBridge.repos.filter((repo) => repo.present).length}/${pythonBridge.repos.length}`} helper={pythonBridge.manifestPath ?? 'No runtime manifest'} />
          </div>

          {pythonBridge.workflows.length ? (
            <div className="mt-4 grid gap-2 xl:grid-cols-2">
              {pythonBridge.workflows.map((workflow) => (
                <div key={workflow.id} className="rounded-2xl border border-border bg-surface-raised px-3 py-3">
                  <div className="flex items-center justify-between gap-3">
                    <div>
                      <p className="text-sm font-semibold text-text-display">{workflow.label}</p>
                      <p className="mt-1 text-xs text-text-secondary">{workflow.supportedInputs.join(' · ')}</p>
                    </div>
                    <Badge variant="outline">{workflow.ready ? 'Ready' : 'Missing deps'}</Badge>
                  </div>
                  <p className="mt-2 text-xs text-text-secondary text-pretty">{workflow.notes}</p>
                </div>
              ))}
            </div>
          ) : null}

          <div className="mt-4 rounded-2xl border border-border bg-surface-raised px-3 py-3">
            <p className="text-[11px] uppercase text-text-secondary">Clinical routing preview</p>
            <div className="mt-2 grid gap-2 xl:grid-cols-2">
              {routingPreview.map(({ label, recommendation }) => (
                <div key={label} className="rounded-xl border border-border bg-card px-3 py-3">
                  <div className="flex items-center justify-between gap-3">
                    <p className="text-sm font-semibold text-text-display">{label}</p>
                    <Badge variant="outline">{recommendation.kind}</Badge>
                  </div>
                  <p className="mt-2 text-xs text-text-primary">{recommendation.title}</p>
                  <p className="mt-1 break-all text-[11px] text-text-secondary">{recommendation.route}</p>
                </div>
              ))}
            </div>
          </div>

          {pythonBridge.repos.length ? (
            <div className="mt-4 grid gap-2 xl:grid-cols-2">
              {pythonBridge.repos.map((repo) => (
                <div key={repo.id} className="rounded-2xl border border-border bg-surface-raised px-3 py-3">
                  <div className="flex items-center justify-between gap-3">
                    <p className="text-sm font-semibold text-text-display">{repo.label}</p>
                    <Badge variant="outline">{repo.present ? 'Present' : 'Missing'}</Badge>
                  </div>
                  <p className="mt-2 break-all text-xs text-text-secondary">{repo.path ?? repo.url}</p>
                </div>
              ))}
            </div>
          ) : null}

          {Object.keys(pythonBridge.supportPaths).length ? (
            <div className="mt-4 rounded-2xl border border-border bg-surface-raised px-3 py-3">
              <p className="text-[11px] uppercase text-text-secondary">Support paths</p>
              <div className="mt-2 grid gap-2">
                {Object.entries(pythonBridge.supportPaths).map(([key, value]) => (
                  <div key={key} className="flex flex-col gap-1 rounded-xl border border-border bg-card px-3 py-2">
                    <span className="text-[11px] uppercase text-text-secondary">{key}</span>
                    <span className="break-all text-xs text-text-primary">{value}</span>
                  </div>
                ))}
              </div>
            </div>
          ) : null}
        </div>
      ) : null}
    </div>
  );
}
