// Generated by Copilot
import React from 'react';

import { Badge } from '@/components/ui/badge';
import { ExpandingSearchDock } from '@/components/ui/expanding-search-dock-shadcnui';
import type { TlantiDbSearchResult } from '@/lib/tlantidb-search';

interface TlantiDbSearchPanelProps {
  results: TlantiDbSearchResult[];
  onSearch: (query: string) => void;
  onResultSelect: (result: TlantiDbSearchResult) => void;
}

export function TlantiDbSearchPanel({ results, onSearch, onResultSelect }: TlantiDbSearchPanelProps) {
  return (
    <div className="space-y-3 rounded-2xl border border-border bg-surface-raised p-4">
      <div className="flex items-center justify-between gap-3">
        <div>
          <h3 className="text-balance text-sm font-semibold uppercase text-text-primary">Case explorer</h3>
          <p className="text-pretty text-xs text-text-secondary">
            Busca casos, ajustes, numeración FDI y futuras opciones del workspace.
          </p>
        </div>
        <ExpandingSearchDock onSearch={onSearch} placeholder="Buscar caso, XML, FDI, idioma..." />
      </div>

      {results.length > 0 ? (
        <div className="space-y-2">
          {results.map((result) => (
            <button
              key={result.id}
              type="button"
              onClick={() => onResultSelect(result)}
              className="flex w-full items-start justify-between gap-3 rounded-xl border border-border bg-surface px-3 py-3 text-left transition-colors hover:border-border-visible hover:bg-muted"
            >
              <div className="min-w-0">
                <p className="truncate text-sm text-text-primary">{result.label}</p>
                <p className="text-pretty text-xs text-text-secondary">{result.description}</p>
              </div>
              <Badge variant="outline">{result.kind}</Badge>
            </button>
          ))}
        </div>
      ) : (
        <div className="rounded-xl border border-dashed border-border px-3 py-4 text-xs text-text-secondary">
          Escribe para encontrar casos, configuración, XML, usuario o numeración dental.
        </div>
      )}
    </div>
  );
}
