// Generated by Copilot
import React, { lazy } from 'react';
import { Language, ThemeMode } from '../../types';
import { WORKSPACE_TITLES } from '../workspace.config';
import { WorkspaceSuspenseBoundary } from '../WorkspaceSuspenseBoundary';
import type { WorkspaceContextSyncRequest } from '@/lib/workspace-shell-contract';

const TlantiDB = lazy(() => import('../TlantiDB').then((module) => ({ default: module.TlantiDB })));

interface TlantiDbWorkspaceProps {
  onEnter: (options?: { caseId?: string; moduleId?: string }) => void;
  onSyncWorkspaceContext: (request: WorkspaceContextSyncRequest) => void;
  language: Language;
  setLanguage: (lang: Language) => void;
  themeMode: ThemeMode;
  setThemeMode: (mode: ThemeMode) => void;
  caseId?: string;
  moduleId?: string;
}

export const TlantiDbWorkspace: React.FC<TlantiDbWorkspaceProps> = (props) => {
  return (
    <WorkspaceSuspenseBoundary title={WORKSPACE_TITLES.app} subtitle={WORKSPACE_TITLES.tlantidb} themeMode={props.themeMode}>
      <TlantiDB {...props} />
    </WorkspaceSuspenseBoundary>
  );
};
