// Generated by Copilot
import React, { useMemo, useState } from 'react';
import { Clock3, FolderSearch2, HardDriveDownload, PlayCircle, Search, Workflow } from 'lucide-react';

import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/interfaces-select';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { cn } from '@/lib/utils';
import { CLINICAL_ASSET_ROLE_LABELS } from '@/lib/tlanticad-asset-classification';
import type { TlantiCase, TlantiCaseAssetRole } from '@/lib/tlantidb-case-store';
import { getMissingRequiredAssets, getNextWorkloadAction, inferWorkloadFromCase, normalizeWorkloadModuleTarget, TLANTIDB_WORKLOAD_PRESETS, type TlantiWorkloadId } from '@/lib/tlantidb-workloads';

type SourceFilter = 'all' | 'recent' | 'local' | 'imported';
type StatusFilter = 'all' | TlantiCase['status'];
type PipelineFilter = 'all' | 'pending-scan' | 'in-design' | 'ready-for-manufacture' | 'exported';
type WorkloadFilter = 'all' | TlantiWorkloadId;

interface TlantiDbCaseBrowserSheetProps {
  open: boolean;
  cases: TlantiCase[];
  activeCaseId: string | null;
  onOpenChange: (open: boolean) => void;
  onSelectCase: (caseId: string) => void;
  onImportCase: () => void;
  onRevealCaseFolder: (caseItem: TlantiCase) => void;
  onOpenModule?: (caseItem: TlantiCase, moduleId: string, label: string) => void;
  onImportRequiredAssets?: (caseItem: TlantiCase, roles: TlantiCaseAssetRole[]) => void;
}

const RECENT_DAYS = 14;

function isRecent(caseItem: TlantiCase) {
  const lastOpenedAt = caseItem.lastOpenedAt ?? caseItem.updatedAt ?? caseItem.createdAt;
  const timestamp = Date.parse(lastOpenedAt);
  if (Number.isNaN(timestamp)) {
    return false;
  }

  const threshold = Date.now() - RECENT_DAYS * 24 * 60 * 60 * 1000;
  return timestamp >= threshold;
}

function getPipelineSummary(caseItem: TlantiCase) {
  const pipeline = caseItem.pipeline;
  if (!pipeline) {
    return 'Pending scan';
  }

  if (pipeline.export) {
    return 'Exported';
  }

  if (pipeline.manufacture) {
    return 'Ready for manufacture';
  }

  if (pipeline.design || pipeline.model) {
    return 'In design';
  }

  return pipeline.scan ? 'Scan ready' : 'Pending scan';
}

function matchesPipeline(caseItem: TlantiCase, filter: PipelineFilter) {
  const pipeline = caseItem.pipeline;
  switch (filter) {
    case 'pending-scan':
      return !pipeline?.scan;
    case 'in-design':
      return Boolean(pipeline?.design || pipeline?.model) && !pipeline?.manufacture && !pipeline?.export;
    case 'ready-for-manufacture':
      return Boolean(pipeline?.manufacture) && !pipeline?.export;
    case 'exported':
      return Boolean(pipeline?.export);
    case 'all':
    default:
      return true;
  }
}

function StageDot({ active }: { active: boolean }) {
  return <span className={cn('size-2 rounded-full', active ? 'bg-text-display' : 'bg-border')} />;
}

export function TlantiDbCaseBrowserSheet({
  open,
  cases,
  activeCaseId,
  onOpenChange,
  onSelectCase,
  onImportCase,
  onRevealCaseFolder,
  onOpenModule = () => undefined,
  onImportRequiredAssets = () => undefined,
}: TlantiDbCaseBrowserSheetProps) {
  const [query, setQuery] = useState('');
  const [sourceFilter, setSourceFilter] = useState<SourceFilter>('all');
  const [statusFilter, setStatusFilter] = useState<StatusFilter>('all');
  const [pipelineFilter, setPipelineFilter] = useState<PipelineFilter>('all');
  const [workloadFilter, setWorkloadFilter] = useState<WorkloadFilter>('all');

  const filteredCases = useMemo(() => {
    return [...cases]
      .filter((caseItem) => {
        const haystack = [caseItem.caseNumber, caseItem.name, caseItem.clientName, caseItem.technicianName].join(' ').toLowerCase();
        return query ? haystack.includes(query.toLowerCase()) : true;
      })
      .filter((caseItem) => {
        if (sourceFilter === 'all') {
          return true;
        }
        if (sourceFilter === 'recent') {
          return isRecent(caseItem);
        }
        return (caseItem.sourceType ?? 'local') === sourceFilter;
      })
      .filter((caseItem) => (statusFilter === 'all' ? true : caseItem.status === statusFilter))
      .filter((caseItem) => matchesPipeline(caseItem, pipelineFilter))
      .filter((caseItem) => (workloadFilter === 'all' ? true : inferWorkloadFromCase(caseItem).id === workloadFilter))
      .sort((left, right) => {
        const a = Date.parse(left.lastOpenedAt ?? left.updatedAt ?? left.createdAt);
        const b = Date.parse(right.lastOpenedAt ?? right.updatedAt ?? right.createdAt);
        return b - a;
      });
  }, [cases, pipelineFilter, query, sourceFilter, statusFilter, workloadFilter]);

  const recentCount = useMemo(() => cases.filter(isRecent).length, [cases]);
  const importedCount = useMemo(() => cases.filter((item) => item.sourceType === 'imported').length, [cases]);

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="left" data-testid="tlantidb-case-browser" className="w-full border-r border-border bg-surface p-0 sm:max-w-[34rem]">
        <SheetHeader className="border-b border-border px-5 py-5">
          <div className="flex items-start justify-between gap-4">
            <div>
              <SheetTitle className="text-balance text-xl text-text-display">Case browser</SheetTitle>
              <SheetDescription className="text-pretty text-sm text-text-secondary">
                Browse recent, imported, and local `.tlanticad` cases with pipeline visibility.
              </SheetDescription>
            </div>
            <button
              type="button"
              onClick={onImportCase}
              className="rounded-2xl border border-border bg-card px-4 py-2 text-sm text-text-primary transition-colors hover:bg-surface-raised"
            >
              Import case
            </button>
          </div>

          <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
            <div className="rounded-2xl border border-border bg-card px-3 py-3">
              <p className="text-[11px] uppercase text-text-secondary">All cases</p>
              <p className="text-lg font-semibold text-text-display tabular-nums">{cases.length}</p>
            </div>
            <div className="rounded-2xl border border-border bg-card px-3 py-3">
              <p className="text-[11px] uppercase text-text-secondary">Recent</p>
              <p className="text-lg font-semibold text-text-display tabular-nums">{recentCount}</p>
            </div>
            <div className="rounded-2xl border border-border bg-card px-3 py-3">
              <p className="text-[11px] uppercase text-text-secondary">Imported</p>
              <p className="text-lg font-semibold text-text-display tabular-nums">{importedCount}</p>
            </div>
            <div className="rounded-2xl border border-border bg-card px-3 py-3">
              <p className="text-[11px] uppercase text-text-secondary">Active</p>
              <p className="text-lg font-semibold text-text-display tabular-nums">{activeCaseId ? 1 : 0}</p>
            </div>
          </div>
        </SheetHeader>

        <div className="flex flex-1 flex-col gap-4 overflow-y-auto px-5 py-5">
          <div className="grid gap-3">
            <label className="grid gap-2">
              <span className="text-[11px] uppercase text-text-secondary">Search</span>
              <div className="flex items-center gap-2 rounded-2xl border border-border bg-card px-3 py-2">
                <Search className="size-4 text-text-secondary" />
                <input
                  value={query}
                  onChange={(event) => setQuery(event.target.value)}
                  placeholder="Case, patient, client or technician"
                  className="w-full bg-transparent text-sm text-text-primary outline-none"
                />
              </div>
            </label>

            <div className="grid grid-cols-1 gap-3 sm:grid-cols-4">
              <label className="grid gap-2">
                <span className="text-[11px] uppercase text-text-secondary">Source</span>
                <Select value={sourceFilter} onValueChange={(value) => setSourceFilter(value as SourceFilter)}>
                  <SelectTrigger className="w-full bg-card">
                    <SelectValue placeholder="Source" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All</SelectItem>
                    <SelectItem value="recent">Recent</SelectItem>
                    <SelectItem value="local">Local</SelectItem>
                    <SelectItem value="imported">Imported</SelectItem>
                  </SelectContent>
                </Select>
              </label>

              <label className="grid gap-2">
                <span className="text-[11px] uppercase text-text-secondary">Status</span>
                <Select value={statusFilter} onValueChange={(value) => setStatusFilter(value as StatusFilter)}>
                  <SelectTrigger className="w-full bg-card">
                    <SelectValue placeholder="Status" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All</SelectItem>
                    <SelectItem value="draft">Draft</SelectItem>
                    <SelectItem value="in-progress">In progress</SelectItem>
                    <SelectItem value="ready">Ready</SelectItem>
                  </SelectContent>
                </Select>
              </label>

              <label className="grid gap-2">
                <span className="text-[11px] uppercase text-text-secondary">Pipeline</span>
                <Select value={pipelineFilter} onValueChange={(value) => setPipelineFilter(value as PipelineFilter)}>
                  <SelectTrigger className="w-full bg-card">
                    <SelectValue placeholder="Pipeline" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All</SelectItem>
                    <SelectItem value="pending-scan">Pending scan</SelectItem>
                    <SelectItem value="in-design">In design</SelectItem>
                    <SelectItem value="ready-for-manufacture">Ready for manufacture</SelectItem>
                    <SelectItem value="exported">Exported</SelectItem>
                  </SelectContent>
                </Select>
              </label>

              <label className="grid gap-2">
                <span className="text-[11px] uppercase text-text-secondary">Workload</span>
                <Select value={workloadFilter} onValueChange={(value) => setWorkloadFilter(value as WorkloadFilter)}>
                  <SelectTrigger className="w-full bg-card">
                    <SelectValue placeholder="Workload" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All</SelectItem>
                    {TLANTIDB_WORKLOAD_PRESETS.map((preset) => (
                      <SelectItem key={preset.id} value={preset.id}>{preset.shortLabel}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </label>
            </div>
          </div>

          {filteredCases.length ? (
            <div className="grid gap-3">
              {filteredCases.map((caseItem) => {
                const pipeline = caseItem.pipeline ?? { scan: false, design: false, model: false, manufacture: false, export: false };
                const active = caseItem.id === activeCaseId;
                const workload = inferWorkloadFromCase(caseItem);
                const missingAssets = getMissingRequiredAssets(caseItem);
                const nextAction = getNextWorkloadAction(caseItem);
                return (
                  <div
                    key={caseItem.id}
                    className={cn(
                      'rounded-[1.5rem] border border-border bg-card p-4 transition-colors',
                      active ? 'border-text-display bg-surface-raised' : 'hover:bg-surface-raised',
                    )}
                  >
                    <div className="flex items-start justify-between gap-3">
                      <button type="button" onClick={() => onSelectCase(caseItem.id)} className="min-w-0 flex-1 text-left">
                        <div className="flex flex-wrap items-center gap-2">
                          <p className="truncate text-sm font-semibold text-text-display">{caseItem.caseNumber}</p>
                          {active ? <Badge className="border border-border bg-surface text-text-primary">Active</Badge> : null}
                          {isRecent(caseItem) ? <Badge className="border border-border bg-surface text-text-primary">Recent</Badge> : null}
                          {caseItem.sourceType === 'imported' ? <Badge className="border border-border bg-surface text-text-primary">Imported</Badge> : null}
                          <Badge className="border border-border bg-surface text-text-primary">{workload.shortLabel}</Badge>
                        </div>
                        <p className="truncate text-sm text-text-primary">{caseItem.name}</p>
                        <p className="truncate text-xs text-text-secondary">{caseItem.clientName} · {caseItem.technicianName}</p>
                      </button>

                      <div className="flex items-center gap-2">
                        <button
                          type="button"
                          onClick={() => onOpenModule(caseItem, normalizeWorkloadModuleTarget(caseItem.moduleTarget ?? workload.moduleTarget), workload.label)}
                          className="flex size-10 items-center justify-center rounded-2xl border border-border bg-surface text-text-secondary transition-colors hover:text-text-primary"
                          aria-label={`Open ${workload.label} for ${caseItem.caseNumber}`}
                        >
                          <PlayCircle className="size-4" />
                        </button>
                        <button
                          type="button"
                          onClick={() => onRevealCaseFolder(caseItem)}
                          disabled={!caseItem.storagePath}
                          className="flex size-10 items-center justify-center rounded-2xl border border-border bg-surface text-text-secondary transition-colors hover:text-text-primary disabled:cursor-not-allowed disabled:opacity-40"
                          aria-label={`Open folder for ${caseItem.caseNumber}`}
                        >
                          <FolderSearch2 className="size-4" />
                        </button>
                      </div>
                    </div>

                    <div className="mt-3 flex items-center justify-between gap-3 rounded-2xl border border-border bg-surface px-3 py-3">
                      <div>
                        <p className="text-[11px] uppercase text-text-secondary">{workload.label}</p>
                        <p className="text-xs text-text-primary">{getPipelineSummary(caseItem)} · {nextAction.label}</p>
                      </div>
                      <div className="flex items-center gap-3">
                        <div className="flex items-center gap-1.5 text-text-secondary">
                          <StageDot active={pipeline.scan} />
                          <StageDot active={pipeline.design} />
                          <StageDot active={pipeline.model} />
                          <StageDot active={pipeline.manufacture} />
                          <StageDot active={pipeline.export} />
                        </div>
                        <Workflow className="size-4 text-text-secondary" />
                      </div>
                    </div>

                    <div className="tl-panel mt-3 rounded-md px-3 py-3">
                      <div className="flex items-start justify-between gap-3">
                        <div>
                          <p className="text-[11px] uppercase text-text-secondary">Required assets</p>
                          <p className="text-xs text-text-primary">
                            {missingAssets.length ? `${missingAssets.length} missing` : 'Ready to design'}
                          </p>
                        </div>
                        <button
                          type="button"
                          onClick={() => onImportRequiredAssets(caseItem, missingAssets.length ? missingAssets : workload.optionalAssetRoles)}
                          className="tl-control rounded-md px-3 py-1.5 text-xs transition-colors"
                        >
                          Import
                        </button>
                      </div>
                      <div className="mt-2 flex flex-wrap gap-1.5">
                        {(missingAssets.length ? missingAssets : workload.requiredAssetRoles).map((role) => (
                          <span key={role} className={cn(
                            'rounded-full border px-2 py-0.5 text-[10px]',
                            missingAssets.includes(role) ? 'border-warning/50 bg-warning/10 text-warning' : 'border-glass-border bg-control-bg text-text-secondary',
                          )}>
                            {CLINICAL_ASSET_ROLE_LABELS[role] ?? role}
                          </span>
                        ))}
                      </div>
                    </div>

                    <div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-text-secondary">
                      <span className="inline-flex items-center gap-1"><Clock3 className="size-3.5" />{new Date(caseItem.lastOpenedAt ?? caseItem.updatedAt ?? caseItem.createdAt).toLocaleString()}</span>
                      <span className="inline-flex items-center gap-1"><HardDriveDownload className="size-3.5" />{caseItem.storagePath ? 'Folder linked' : 'No folder linked'}</span>
                    </div>
                  </div>
                );
              })}
            </div>
          ) : (
            <div className="rounded-[1.75rem] border border-dashed border-border px-5 py-8 text-center">
              <p className="text-sm text-text-primary">No matching cases</p>
              <p className="mt-1 text-sm text-text-secondary">Adjust the filters or import a `.tlanticad` case from disk.</p>
            </div>
          )}
        </div>
      </SheetContent>
    </Sheet>
  );
}
