// Generated by Copilot
import React, { useEffect, useMemo, useState } from 'react';
import { Activity, Box, ChevronDown, ChevronRight, ExternalLink, FileText, FolderSearch2, Image as ImageIcon, Import, Link2, RefreshCcw, Save, ScanLine, Sparkles, Tag, Trash2, UploadCloud } from 'lucide-react';

import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/interfaces-select';
import { CLINICAL_ASSET_ROLE_LABELS, inferClinicalAssetRole, inferClinicalAssetTags, normalizeAssetTags } from '@/lib/tlanticad-asset-classification';
import { deriveChecklistFromCase, deriveNextClinicalAction, deriveSuggestedAssetsByStage, groupAssetsByRole } from '@/lib/tlantidb-clinical-workflow';
import { cn } from '@/lib/utils';
import { isTauriRuntime } from '@/lib/desktop-system';
import type { DicomMetadata } from '@/types';
import type { TlantiCase, TlantiCaseAsset, TlantiCaseAssetCategory, TlantiCaseAssetRole } from '@/lib/tlantidb-case-store';

interface TlantiDbClinicalAssetsPanelProps {
  activeCase: TlantiCase;
  onImportAssets: () => void;
  onDropAssets: (files: File[]) => void;
  onRevealCaseFolder: () => void;
  onOpenAsset: (asset: TlantiCaseAsset) => void;
  onReplaceAsset: (asset: TlantiCaseAsset) => void;
  onRelinkAsset: (asset: TlantiCaseAsset) => void;
  onDeleteAsset: (asset: TlantiCaseAsset) => void;
  onUpdateAssetMetadata: (assetId: string, patch: Partial<TlantiCaseAsset>) => void;
  onGuideImport: (roles: TlantiCaseAssetRole[]) => void;
}

type AssetFilter = 'all' | TlantiCaseAssetCategory;

const FILTERS: Array<{ value: AssetFilter; label: string }> = [
  { value: 'all', label: 'All' },
  { value: 'image', label: 'Images' },
  { value: 'document', label: 'Docs' },
  { value: 'model', label: 'Models' },
  { value: 'dicom', label: 'DICOM' },
];

function getAssetIcon(category: TlantiCaseAssetCategory) {
  switch (category) {
    case 'image':
      return ImageIcon;
    case 'model':
      return Box;
    case 'dicom':
      return ScanLine;
    case 'report':
      return Activity;
    case 'document':
    default:
      return FileText;
  }
}

function formatSize(value?: number | null) {
  if (!value) return '—';
  if (value < 1024) return `${value} B`;
  if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`;
  return `${(value / (1024 * 1024)).toFixed(1)} MB`;
}

export function TlantiDbClinicalAssetsPanel({ activeCase, onImportAssets, onDropAssets, onRevealCaseFolder, onOpenAsset, onReplaceAsset, onRelinkAsset, onDeleteAsset, onUpdateAssetMetadata, onGuideImport }: TlantiDbClinicalAssetsPanelProps) {
  const [assetFilter, setAssetFilter] = useState<AssetFilter>('all');
  const [selectedAssetId, setSelectedAssetId] = useState<string | null>(null);
  const [assetPreviewUrls, setAssetPreviewUrls] = useState<Record<string, string>>({});
  const [isDragOver, setIsDragOver] = useState(false);
  const [draftName, setDraftName] = useState('');
  const [draftRole, setDraftRole] = useState<TlantiCaseAssetRole>('other');
  const [draftTags, setDraftTags] = useState('');
  const [dicomMetadata, setDicomMetadata] = useState<DicomMetadata | null>(null);
  const [dicomPreviewError, setDicomPreviewError] = useState<string | null>(null);
  const [collapsedRoles, setCollapsedRoles] = useState<Record<string, boolean>>({});

  const assets = activeCase.assets ?? [];
  const filteredAssets = useMemo(() => assets.filter((asset) => (assetFilter === 'all' ? true : asset.category === assetFilter)), [assetFilter, assets]);
  const groupedAssets = useMemo(() => groupAssetsByRole(filteredAssets), [filteredAssets]);
  const clinicalChecklist = useMemo(() => deriveChecklistFromCase(activeCase, assets), [activeCase, assets]);
  const stageSuggestions = useMemo(() => deriveSuggestedAssetsByStage(activeCase, assets), [activeCase, assets]);
  const nextClinicalAction = useMemo(() => deriveNextClinicalAction(activeCase, assets), [activeCase, assets]);

  const selectedAsset = useMemo(
    () => filteredAssets.find((asset) => asset.id === selectedAssetId) ?? filteredAssets.find((asset) => asset.category === 'image') ?? filteredAssets[0] ?? null,
    [filteredAssets, selectedAssetId],
  );

  useEffect(() => {
    if (!selectedAsset) {
      setDraftName('');
      setDraftRole('other');
      setDraftTags('');
      return;
    }

    setDraftName(selectedAsset.name);
    setDraftRole(selectedAsset.role);
    setDraftTags(selectedAsset.tags.join(', '));
  }, [selectedAsset]);

  useEffect(() => {
    let cancelled = false;

    const loadPreviewUrls = async () => {
      if (!isTauriRuntime() || !activeCase.storagePath || !assets.length) {
        setAssetPreviewUrls({});
        return;
      }

      const [{ convertFileSrc }, { join }] = await Promise.all([
        import('@tauri-apps/api/core'),
        import('@tauri-apps/api/path'),
      ]);

      const pairs = await Promise.all(
        assets.map(async (asset) => {
          const absolutePath = await join(activeCase.storagePath!, asset.relativePath);
          return [asset.id, convertFileSrc(absolutePath)] as const;
        }),
      );

      if (!cancelled) {
        setAssetPreviewUrls(Object.fromEntries(pairs));
      }
    };

    void loadPreviewUrls();
    return () => {
      cancelled = true;
    };
  }, [activeCase.storagePath, assets]);

  useEffect(() => {
    let cancelled = false;

    const loadDicomMetadata = async () => {
      if (!selectedAsset || selectedAsset.category !== 'dicom' || !activeCase.storagePath || !isTauriRuntime()) {
        setDicomMetadata(null);
        setDicomPreviewError(null);
        return;
      }

      try {
        const [{ readFile }, { join }] = await Promise.all([
          import('@tauri-apps/plugin-fs'),
          import('@tauri-apps/api/path'),
        ]);
        const absolutePath = await join(activeCase.storagePath, selectedAsset.relativePath);
        const bytes = await readFile(absolutePath);
        const { parseDicomInfo } = await import('@/utils/dicomMetadata');
        const parsed = parseDicomInfo(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength), 1);

        if (!cancelled) {
          setDicomMetadata(parsed?.metadata ?? null);
          setDicomPreviewError(parsed ? null : 'No DICOM metadata available.');
        }
      } catch (error) {
        if (!cancelled) {
          setDicomMetadata(null);
          setDicomPreviewError(error instanceof Error ? error.message : 'Could not parse DICOM metadata.');
        }
      }
    };

    void loadDicomMetadata();
    return () => {
      cancelled = true;
    };
  }, [activeCase.storagePath, selectedAsset]);

  const selectedAssetUrl = selectedAsset ? assetPreviewUrls[selectedAsset.id] : null;

  const focusChecklistRoles = (roles: TlantiCaseAssetRole[]) => {
    const firstMatch = assets.find((asset) => roles.includes(asset.role));
    if (firstMatch) {
      setSelectedAssetId(firstMatch.id);
      setCollapsedRoles((prev) => ({ ...prev, [firstMatch.role]: false }));
    }
  };

  const toggleRoleGroup = (role: TlantiCaseAssetRole) => {
    setCollapsedRoles((prev) => ({ ...prev, [role]: !prev[role] }));
  };

  const saveMetadata = () => {
    if (!selectedAsset) return;
    onUpdateAssetMetadata(selectedAsset.id, {
      name: draftName.trim() || selectedAsset.name,
      role: draftRole,
      tags: normalizeAssetTags(draftTags),
      classificationSource: 'manual',
    });
  };

  const autoClassifySelectedAsset = () => {
    if (!selectedAsset) return;
    const inferredName = draftName.trim() || selectedAsset.name;
    const role = inferClinicalAssetRole(inferredName, selectedAsset.category);
    const tags = inferClinicalAssetTags(inferredName, selectedAsset.category);
    setDraftRole(role);
    setDraftTags(tags.join(', '));
    onUpdateAssetMetadata(selectedAsset.id, {
      name: inferredName,
      role,
      tags,
      classificationSource: 'auto',
    });
  };

  const handleDrop = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    setIsDragOver(false);
    const files = Array.from(event.dataTransfer.files ?? []);
    if (files.length) onDropAssets(files);
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between gap-3">
        <div>
          <p className="text-xs uppercase text-text-secondary">Clinical assets</p>
          <p className="text-sm text-text-primary">Preview images, scan evidence and attached documents inside the case folder.</p>
        </div>
        <Badge className="border border-border bg-card text-text-primary">{assets.length} files</Badge>
      </div>

      <div className="flex flex-wrap gap-2">
        {FILTERS.map((filter) => (
          <button
            key={filter.value}
            type="button"
            onClick={() => setAssetFilter(filter.value)}
            className={cn(
              'rounded-2xl border px-3 py-1.5 text-xs transition-colors',
              assetFilter === filter.value ? 'border-text-display bg-surface text-text-primary' : 'border-border bg-card text-text-secondary hover:text-text-primary',
            )}
          >
            {filter.label}
          </button>
        ))}
      </div>

      <div
        onDragOver={(event) => {
          event.preventDefault();
          setIsDragOver(true);
        }}
        onDragLeave={() => setIsDragOver(false)}
        onDrop={handleDrop}
        className={cn('rounded-2xl border border-dashed px-4 py-4 transition-colors', isDragOver ? 'border-text-display bg-surface' : 'border-border bg-card')}
      >
        <div className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="flex size-11 items-center justify-center rounded-2xl border border-border bg-surface text-text-secondary">
              <UploadCloud className="size-5" />
            </div>
            <div>
              <p className="text-sm text-text-display">Drop assets into this case</p>
              <p className="text-xs text-text-secondary">Import models, DICOM, clinical photos or documents directly into `.tlanticad`.</p>
            </div>
          </div>
          <button type="button" onClick={onImportAssets} className="rounded-2xl border border-border bg-surface px-4 py-2 text-sm text-text-primary transition-colors hover:bg-surface-raised">
            Browse files
          </button>
        </div>
      </div>

      <div className="grid gap-4 xl:grid-cols-[1.12fr_0.88fr]">
        <div className="rounded-2xl border border-border bg-card p-4">
          <div className="mb-3 flex items-center justify-between gap-3">
            <p className="text-xs uppercase text-text-secondary">Preview</p>
            {selectedAsset ? <Badge className="border border-border bg-surface text-text-primary">{selectedAsset.category}</Badge> : null}
          </div>

          {selectedAsset ? (
            <div className="mb-3 flex flex-wrap gap-2">
              <button type="button" onClick={() => onOpenAsset(selectedAsset)} className="inline-flex items-center gap-2 rounded-2xl border border-border bg-surface px-3 py-2 text-xs text-text-primary transition-colors hover:bg-surface-raised"><ExternalLink className="size-3.5" />Open</button>
              <button type="button" onClick={() => onReplaceAsset(selectedAsset)} className="inline-flex items-center gap-2 rounded-2xl border border-border bg-surface px-3 py-2 text-xs text-text-primary transition-colors hover:bg-surface-raised"><RefreshCcw className="size-3.5" />Replace</button>
              <button type="button" onClick={() => onRelinkAsset(selectedAsset)} className="inline-flex items-center gap-2 rounded-2xl border border-border bg-surface px-3 py-2 text-xs text-text-primary transition-colors hover:bg-surface-raised"><Link2 className="size-3.5" />Relink</button>
              <AlertDialog>
                <AlertDialogTrigger asChild>
                  <button type="button" className="inline-flex items-center gap-2 rounded-2xl border border-border bg-surface px-3 py-2 text-xs text-text-primary transition-colors hover:bg-surface-raised"><Trash2 className="size-3.5" />Delete</button>
                </AlertDialogTrigger>
                <AlertDialogContent>
                  <AlertDialogHeader>
                    <AlertDialogTitle>Delete asset</AlertDialogTitle>
                    <AlertDialogDescription>
                      Remove `{selectedAsset.name}` from the clinical case and delete the copied file from `.tlanticad` when available.
                    </AlertDialogDescription>
                  </AlertDialogHeader>
                  <AlertDialogFooter>
                    <AlertDialogCancel>Cancel</AlertDialogCancel>
                    <AlertDialogAction onClick={() => onDeleteAsset(selectedAsset)}>Delete asset</AlertDialogAction>
                  </AlertDialogFooter>
                </AlertDialogContent>
              </AlertDialog>
            </div>
          ) : null}

          {selectedAsset?.category === 'image' && selectedAssetUrl ? (
            <button type="button" onClick={() => onOpenAsset(selectedAsset)} className="block w-full overflow-hidden rounded-2xl border border-border bg-surface text-left">
              <img src={selectedAssetUrl} alt={selectedAsset.name} className="h-56 w-full object-cover" />
              <div className="border-t border-border px-3 py-3">
                <p className="truncate text-sm text-text-display">{selectedAsset.name}</p>
                <p className="truncate text-xs text-text-secondary">{selectedAsset.relativePath}</p>
              </div>
            </button>
          ) : selectedAsset?.mimeType === 'application/pdf' && selectedAssetUrl ? (
            <div className="overflow-hidden rounded-2xl border border-border bg-surface">
              <iframe src={`${selectedAssetUrl}#toolbar=1&navpanes=0`} title={selectedAsset.name} className="h-64 w-full border-0" />
              <div className="grid gap-3 border-t border-border px-3 py-3 md:grid-cols-2">
                <div>
                  <p className="truncate text-sm text-text-display">{selectedAsset.name}</p>
                  <p className="truncate text-xs text-text-secondary">Clinical document preview</p>
                </div>
                <div className="grid grid-cols-2 gap-2 text-xs text-text-secondary">
                  <div className="rounded-xl border border-border bg-card px-3 py-2">
                    <p className="uppercase">Role</p>
                    <p className="mt-1 text-text-primary">{CLINICAL_ASSET_ROLE_LABELS[selectedAsset.role]}</p>
                  </div>
                  <div className="rounded-xl border border-border bg-card px-3 py-2">
                    <p className="uppercase">Size</p>
                    <p className="mt-1 text-text-primary">{formatSize(selectedAsset.fileSize)}</p>
                  </div>
                </div>
              </div>
            </div>
          ) : selectedAsset?.category === 'dicom' ? (
            <div className="flex min-h-64 flex-col justify-between rounded-2xl border border-border bg-surface p-4">
              <div>
                <div className="flex size-12 items-center justify-center rounded-2xl border border-border bg-card text-text-secondary">
                  <ScanLine className="size-5" />
                </div>
                <p className="mt-4 text-sm text-text-display">DICOM study attached</p>
                <p className="mt-1 text-sm text-text-secondary">{selectedAsset.name}</p>
              </div>
              <div className="grid gap-3 text-xs text-text-secondary md:grid-cols-2">
                <div className="rounded-xl border border-border bg-card px-3 py-2">
                  <p className="uppercase">Modality</p>
                  <p className="mt-1 text-text-primary">{dicomMetadata?.modality ?? 'DICOM'}</p>
                </div>
                <div className="rounded-xl border border-border bg-card px-3 py-2">
                  <p className="uppercase">Study date</p>
                  <p className="mt-1 text-text-primary">{dicomMetadata?.studyDate ?? '—'}</p>
                </div>
                <div className="rounded-xl border border-border bg-card px-3 py-2">
                  <p className="uppercase">Series</p>
                  <p className="mt-1 truncate text-text-primary">{dicomMetadata?.seriesDescription ?? '—'}</p>
                </div>
                <div className="rounded-xl border border-border bg-card px-3 py-2">
                  <p className="uppercase">Dimensions</p>
                  <p className="mt-1 text-text-primary">{dicomMetadata?.dimensions ?? formatSize(selectedAsset.fileSize)}</p>
                </div>
              </div>
              {dicomPreviewError ? <p className="mt-3 text-xs text-text-secondary">{dicomPreviewError}</p> : null}
            </div>
          ) : selectedAsset?.category === 'model' ? (
            <div className="flex h-56 flex-col justify-between rounded-2xl border border-border bg-surface p-4">
              <div>
                <div className="flex size-12 items-center justify-center rounded-2xl border border-border bg-card text-text-secondary">
                  <Box className="size-5" />
                </div>
                <p className="mt-4 text-sm text-text-display">3D model attached</p>
                <p className="mt-1 text-sm text-text-secondary">{selectedAsset.name}</p>
              </div>
              <div className="grid grid-cols-2 gap-3 text-xs text-text-secondary">
                <div className="rounded-xl border border-border bg-card px-3 py-2">
                  <p className="uppercase">Format</p>
                  <p className="mt-1 text-text-primary">{selectedAsset.name.split('.').pop()?.toUpperCase() ?? 'MODEL'}</p>
                </div>
                <div className="rounded-xl border border-border bg-card px-3 py-2">
                  <p className="uppercase">Size</p>
                  <p className="mt-1 text-text-primary">{formatSize(selectedAsset.fileSize)}</p>
                </div>
              </div>
            </div>
          ) : selectedAsset ? (
            <button type="button" onClick={() => onOpenAsset(selectedAsset)} className="flex h-56 w-full flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-surface px-4 text-center">
              {React.createElement(getAssetIcon(selectedAsset.category), { className: 'size-10 text-text-secondary' })}
              <p className="mt-4 text-sm text-text-display">{selectedAsset.name}</p>
              <p className="mt-1 text-xs text-text-secondary">{selectedAsset.relativePath}</p>
              <p className="mt-2 text-[11px] uppercase text-text-secondary">{formatSize(selectedAsset.fileSize)}</p>
            </button>
          ) : (
            <div className="flex h-56 items-center justify-center rounded-2xl border border-dashed border-border bg-surface px-4 text-center text-sm text-text-secondary">
              No assets attached yet. Import images, DICOM, models or documents into the active case.
            </div>
          )}
        </div>

        <div className="space-y-4">
          {nextClinicalAction ? (
            <div className="rounded-2xl border border-border bg-card p-4">
              <div className="mb-3 flex items-center justify-between gap-3">
                <div>
                  <p className="text-xs uppercase text-text-secondary">Guided workflow</p>
                  <p className="text-sm text-text-primary">Next recommended step based on what is still missing in the case.</p>
                </div>
                <Badge className="border border-border bg-surface text-text-primary">{nextClinicalAction.stage}</Badge>
              </div>
              <div className="rounded-2xl border border-border bg-surface px-3 py-3">
                <p className="text-sm text-text-display">{nextClinicalAction.label}</p>
                <p className="mt-1 text-xs text-text-secondary">{nextClinicalAction.description}</p>
                <div className="mt-3 flex flex-wrap gap-2">
                  {nextClinicalAction.roles.map((role) => (
                    <Badge key={role} className="border border-border bg-card text-text-primary">{CLINICAL_ASSET_ROLE_LABELS[role]}</Badge>
                  ))}
                </div>
                <div className="mt-3 flex flex-wrap gap-2">
                  <button type="button" onClick={() => onGuideImport(nextClinicalAction.roles)} className="rounded-2xl border border-border bg-card px-3 py-2 text-xs text-text-primary transition-colors hover:bg-surface-raised">Import for this step</button>
                  <button type="button" onClick={() => focusChecklistRoles(nextClinicalAction.roles)} className="rounded-2xl border border-border bg-card px-3 py-2 text-xs text-text-primary transition-colors hover:bg-surface-raised">Focus matching assets</button>
                </div>
              </div>
            </div>
          ) : null}

          <div className="rounded-2xl border border-border bg-card p-4">
            <div className="mb-3 flex items-center justify-between">
              <p className="text-xs uppercase text-text-secondary">Clinical checklist</p>
              <Badge className="border border-border bg-surface text-text-primary">{clinicalChecklist.filter((item) => item.completed).length}/{clinicalChecklist.length}</Badge>
            </div>
            <div className="grid gap-2">
              {clinicalChecklist.map((item) => (
                <div key={item.id} className="rounded-2xl border border-border bg-surface px-3 py-3">
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <p className="text-sm text-text-display">{item.label}</p>
                      <p className="text-xs text-text-secondary">{item.description}</p>
                    </div>
                    <Badge className={cn('border border-border', item.completed ? 'bg-surface text-text-primary' : 'bg-card text-text-secondary')}>
                      {item.completed ? 'Done' : item.required ? 'Required' : 'Optional'}
                    </Badge>
                  </div>
                  {!item.completed ? (
                    <div className="mt-3 flex flex-wrap gap-2">
                      <button type="button" onClick={() => onGuideImport(item.roles)} className="rounded-2xl border border-border bg-card px-3 py-2 text-xs text-text-primary transition-colors hover:bg-surface-raised">Import missing asset</button>
                      <button type="button" onClick={() => focusChecklistRoles(item.roles)} className="rounded-2xl border border-border bg-card px-3 py-2 text-xs text-text-primary transition-colors hover:bg-surface-raised">Focus existing matches</button>
                    </div>
                  ) : null}
                </div>
              ))}
            </div>
          </div>

          <div className="rounded-2xl border border-border bg-card p-4">
            <div className="mb-3 flex items-center justify-between">
              <p className="text-xs uppercase text-text-secondary">Suggested assets by stage</p>
              <Badge className="border border-border bg-surface text-text-primary">{stageSuggestions.length}</Badge>
            </div>
            <div className="grid gap-2">
              {stageSuggestions.map((suggestion) => (
                <div key={suggestion.id} className="rounded-2xl border border-border bg-surface px-3 py-3">
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <p className="text-sm text-text-display">{suggestion.label}</p>
                      <p className="text-xs text-text-secondary">{suggestion.description}</p>
                    </div>
                    <Badge className={cn('border border-border', suggestion.completed ? 'bg-surface text-text-primary' : 'bg-card text-text-secondary')}>{suggestion.stage}</Badge>
                  </div>
                  <div className="mt-3 flex flex-wrap gap-2">
                    {suggestion.roles.map((role) => (
                      <Badge key={`${suggestion.id}-${role}`} className="border border-border bg-card text-text-primary">{CLINICAL_ASSET_ROLE_LABELS[role]}</Badge>
                    ))}
                  </div>
                  {!suggestion.completed ? (
                    <div className="mt-3">
                      <button type="button" onClick={() => onGuideImport(suggestion.roles)} className="rounded-2xl border border-border bg-card px-3 py-2 text-xs text-text-primary transition-colors hover:bg-surface-raised">Guide import</button>
                    </div>
                  ) : null}
                </div>
              ))}
            </div>
          </div>

          {selectedAsset ? (
            <div className="rounded-2xl border border-border bg-card p-4">
              <div className="mb-3 flex items-center justify-between gap-3">
                <div>
                  <p className="text-xs uppercase text-text-secondary">Clinical classification</p>
                  <p className="text-sm text-text-primary">Rename the asset, assign a clinical role and keep structured tags.</p>
                </div>
                <Badge className="border border-border bg-surface text-text-primary">{selectedAsset.classificationSource ?? 'auto'}</Badge>
              </div>
              <div className="grid gap-3">
                <label className="grid gap-2">
                  <span className="text-[11px] uppercase text-text-secondary">Asset name</span>
                  <input value={draftName} onChange={(event) => setDraftName(event.target.value)} className="rounded-xl border border-border bg-surface px-3 py-2 text-sm text-text-primary outline-none focus:border-text-primary" />
                </label>
                <label className="grid gap-2">
                  <span className="text-[11px] uppercase text-text-secondary">Clinical role</span>
                  <Select value={draftRole} onValueChange={(value) => setDraftRole(value as TlantiCaseAssetRole)}>
                    <SelectTrigger className="w-full bg-surface">
                      <SelectValue placeholder="Select clinical role" />
                    </SelectTrigger>
                    <SelectContent>
                      {Object.entries(CLINICAL_ASSET_ROLE_LABELS).map(([value, label]) => (
                        <SelectItem key={value} value={value}>{label}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </label>
                <label className="grid gap-2">
                  <span className="flex items-center gap-2 text-[11px] uppercase text-text-secondary"><Tag className="size-3.5" />Tags</span>
                  <input value={draftTags} onChange={(event) => setDraftTags(event.target.value)} placeholder="prep, upper, implant" className="rounded-xl border border-border bg-surface px-3 py-2 text-sm text-text-primary outline-none focus:border-text-primary" />
                </label>
                <div className="flex flex-wrap gap-2">
                  {(selectedAsset.tags ?? []).map((tag) => (
                    <Badge key={tag} className="border border-border bg-surface text-text-primary">{tag}</Badge>
                  ))}
                </div>
                <div className="flex flex-wrap gap-2">
                  <button type="button" onClick={saveMetadata} className="inline-flex items-center gap-2 rounded-2xl border border-border bg-surface px-3 py-2 text-xs text-text-primary transition-colors hover:bg-surface-raised"><Save className="size-3.5" />Save metadata</button>
                  <button type="button" onClick={autoClassifySelectedAsset} className="inline-flex items-center gap-2 rounded-2xl border border-border bg-surface px-3 py-2 text-xs text-text-primary transition-colors hover:bg-surface-raised"><Sparkles className="size-3.5" />Auto classify</button>
                </div>
              </div>
            </div>
          ) : null}

          <div className="rounded-2xl border border-border bg-card p-4">
            <div className="mb-3 flex items-center justify-between">
              <p className="text-xs uppercase text-text-secondary">Assets by clinical role</p>
              <Badge className="border border-border bg-surface text-text-primary">{filteredAssets.length}</Badge>
            </div>
            {groupedAssets.length ? (
              <div className="grid gap-3 max-h-72 overflow-y-auto pr-1">
                {groupedAssets.map(([role, roleAssets]) => (
                  <div key={role} className="grid gap-2">
                    <button
                      type="button"
                      onClick={() => toggleRoleGroup(role)}
                      aria-expanded={!collapsedRoles[role]}
                      className="flex items-center justify-between rounded-2xl border border-border bg-surface px-3 py-2 text-left transition-colors hover:bg-surface-raised"
                    >
                      <div className="flex items-center gap-2">
                        {collapsedRoles[role] ? <ChevronRight className="size-4 text-text-secondary" /> : <ChevronDown className="size-4 text-text-secondary" />}
                        <p className="text-[11px] uppercase text-text-secondary">{CLINICAL_ASSET_ROLE_LABELS[role]}</p>
                      </div>
                      <Badge className="border border-border bg-card text-text-primary">{roleAssets.length}</Badge>
                    </button>
                    {!collapsedRoles[role] ? roleAssets.map((asset) => {
                      const Icon = getAssetIcon(asset.category);
                      return (
                        <button
                          key={asset.id}
                          type="button"
                          onClick={() => setSelectedAssetId(asset.id)}
                          className={cn(
                            'flex items-center gap-3 rounded-2xl border px-3 py-3 text-left transition-colors hover:bg-surface-raised',
                            selectedAsset?.id === asset.id ? 'border-text-display bg-surface' : 'border-border bg-surface',
                          )}
                        >
                          <div className="flex size-10 items-center justify-center rounded-xl border border-border bg-card text-text-secondary">
                            <Icon className="size-4" />
                          </div>
                          <div className="min-w-0 flex-1">
                            <p className="truncate text-sm text-text-display">{asset.name}</p>
                            <p className="truncate text-xs text-text-secondary">{asset.relativePath}</p>
                          </div>
                          <div className="text-right">
                            <Badge className="border border-border bg-card text-text-primary">{asset.classificationSource ?? 'auto'}</Badge>
                            <p className="mt-1 text-[11px] text-text-secondary">{formatSize(asset.fileSize)}</p>
                          </div>
                        </button>
                      );
                    }) : null}
                  </div>
                ))}
              </div>
            ) : (
              <div className="rounded-2xl border border-dashed border-border px-4 py-6 text-sm text-text-secondary">No assets match the current filter.</div>
            )}
          </div>

          <div className="grid grid-cols-2 gap-3">
            <button type="button" onClick={onImportAssets} className="flex items-center justify-center gap-2 rounded-2xl border border-border bg-card px-4 py-3 text-sm text-text-primary transition-colors hover:bg-surface-raised">
              <Import className="size-4" />
              Import assets
            </button>
            <button type="button" onClick={onRevealCaseFolder} disabled={!activeCase.storagePath} className="flex items-center justify-center gap-2 rounded-2xl border border-border bg-card px-4 py-3 text-sm text-text-primary transition-colors hover:bg-surface-raised disabled:cursor-not-allowed disabled:opacity-40">
              <FolderSearch2 className="size-4" />
              Case folder
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
