// Generated by Copilot
import React from 'react';
import { CircleDot, ScanSearch, Settings2 } from 'lucide-react';

import { getToothNumberingLegend, type DentalNumberingSystem } from '@/lib/dental-numbering';
import type { PublicAssetLibraryItem } from '@/lib/public-asset-library';
import { inferDentalLibraryDefaults } from '@/lib/public-asset-dental-defaults';
import { IMPLANT_MODE_OPTIONS, MATERIAL_OPTIONS, PRODUCTION_OPTIONS, RESTORATION_OPTIONS, getRestorationColor, getRestorationLabel } from '@/lib/dental-workflow';
import type { TlantiToothState } from '@/stores/tlantidb-case-store';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/interfaces-select';
import { Switch } from '@/components/ui/interfaces-switch';
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from '@/components/ui/sheet';

interface ToothWorkflowSheetProps {
  open: boolean;
  toothNumber: string | null;
  numberingSystem: DentalNumberingSystem;
  toothState?: TlantiToothState;
  libraryAsset?: PublicAssetLibraryItem | null;
  onOpenChange: (open: boolean) => void;
  onPatchTooth: (toothNumber: string, patch: Partial<TlantiToothState>) => void;
  onApplyLibraryDefaults?: (toothNumber: string) => void;
  onClearTooth: (toothNumber: string) => void;
}

const SHADES = ['A1', 'A2', 'A3', 'B1', 'C1', 'BL1'];

function DetailRow({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="grid gap-2">
      <span className="text-[11px] uppercase text-text-secondary">{label}</span>
      {children}
    </label>
  );
}

export function ToothWorkflowSheet({ open, toothNumber, numberingSystem, toothState, libraryAsset, onOpenChange, onPatchTooth, onApplyLibraryDefaults, onClearTooth }: ToothWorkflowSheetProps) {
  const isOpen = open && Boolean(toothNumber);
  const safeToothNumber = toothNumber ?? '';
  const numberingLegend = safeToothNumber ? getToothNumberingLegend(safeToothNumber, numberingSystem) : '';
  const restorationType = toothState?.restorationType ?? (toothState?.antagonist ? 'antagonist' : 'anatomic-coping');
  const material = toothState?.material ?? 'zirconia';
  const productionMethod = toothState?.productionMethod ?? 'inhouse-milling';
  const implantMode = toothState?.implantMode ?? 'none';
  const shade = toothState?.shade ?? 'A1';
  const libraryDefaults = libraryAsset ? inferDentalLibraryDefaults(libraryAsset) : null;

  return (
    <Sheet open={isOpen} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="w-full border-l border-border bg-surface p-0 sm:max-w-[28rem]">
        <SheetHeader className="border-b border-border px-5 py-5">
          <div className="flex items-start gap-3">
            <div className="flex size-12 items-center justify-center rounded-2xl border border-border bg-card" style={{ color: getRestorationColor(restorationType, toothState?.antagonist) }}>
              <CircleDot className="size-5" />
            </div>
            <div>
              <SheetTitle className="text-balance text-xl text-text-display">{numberingLegend || `Tooth ${safeToothNumber}`}</SheetTitle>
              <SheetDescription className="text-pretty text-sm text-text-secondary">
                {getRestorationLabel(restorationType)} · define material, shade, production and scan options for the selected tooth.
              </SheetDescription>
            </div>
          </div>
        </SheetHeader>

        <div className="flex flex-1 flex-col gap-4 overflow-y-auto px-5 py-5">
          {libraryAsset && libraryDefaults ? (
            <section className="rounded-2xl border border-border bg-card p-4">
              <div className="mb-3 flex items-center gap-2">
                <CircleDot className="size-4 text-text-display" />
                <h3 className="text-sm font-semibold text-text-display">Active dental library</h3>
              </div>

              <div className="grid gap-3 text-sm text-text-secondary">
                <div>
                  <p className="text-sm text-text-primary">{libraryDefaults.title}</p>
                  <p className="mt-1 text-xs text-text-secondary">{libraryAsset.label}</p>
                </div>
                {libraryDefaults.notes.map((note) => (
                  <div key={note} className="rounded-2xl border border-border bg-surface-raised p-3 text-xs text-text-secondary">
                    {note}
                  </div>
                ))}
                <button type="button" onClick={() => onApplyLibraryDefaults?.(safeToothNumber)} className="rounded-2xl border border-border px-4 py-2 text-sm text-text-primary transition-colors hover:bg-surface-raised">
                  Apply library defaults to this tooth
                </button>
              </div>
            </section>
          ) : null}

          <section className="rounded-2xl border border-border bg-card p-4">
            <div className="mb-3 flex items-center gap-2">
              <Settings2 className="size-4 text-text-secondary" />
              <h3 className="text-sm font-semibold text-text-display">Restoration setup</h3>
            </div>

            <div className="grid gap-4">
              <DetailRow label="Restoration type">
                <Select value={restorationType} onValueChange={(value) => onPatchTooth(safeToothNumber, { restorationType: value as TlantiToothState['restorationType'], antagonist: value === 'antagonist', adjacentTooth: value === 'adjacent-tooth', omitInBridge: value === 'omit-in-bridge', selected: true, condition: value })}>
                  <SelectTrigger className="w-full bg-surface-raised">
                    <SelectValue placeholder="Select restoration" />
                  </SelectTrigger>
                  <SelectContent>
                    {RESTORATION_OPTIONS.map((option) => (
                      <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </DetailRow>

              <DetailRow label="Material">
                <Select value={material} onValueChange={(value) => onPatchTooth(safeToothNumber, { material: value as TlantiToothState['material'] })}>
                  <SelectTrigger className="w-full bg-surface-raised">
                    <SelectValue placeholder="Select material" />
                  </SelectTrigger>
                  <SelectContent>
                    {MATERIAL_OPTIONS.map((option) => (
                      <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </DetailRow>

              <div className="grid grid-cols-2 gap-3">
                <DetailRow label="Shade">
                  <Select value={shade} onValueChange={(value) => onPatchTooth(safeToothNumber, { shade: value })}>
                    <SelectTrigger className="w-full bg-surface-raised">
                      <SelectValue placeholder="Shade" />
                    </SelectTrigger>
                    <SelectContent>
                      {SHADES.map((value) => (
                        <SelectItem key={value} value={value}>{value}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </DetailRow>

                <DetailRow label="Production">
                  <Select value={productionMethod} onValueChange={(value) => onPatchTooth(safeToothNumber, { productionMethod: value as TlantiToothState['productionMethod'] })}>
                    <SelectTrigger className="w-full bg-surface-raised">
                      <SelectValue placeholder="Production" />
                    </SelectTrigger>
                    <SelectContent>
                      {PRODUCTION_OPTIONS.map((option) => (
                        <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </DetailRow>
              </div>
            </div>
          </section>

          <section className="rounded-2xl border border-border bg-card p-4">
            <div className="mb-3 flex items-center gap-2">
              <ScanSearch className="size-4 text-text-secondary" />
              <h3 className="text-sm font-semibold text-text-display">Clinical options</h3>
            </div>

            <div className="grid gap-4">
              <DetailRow label="Implant mode">
                <Select value={implantMode} onValueChange={(value) => onPatchTooth(safeToothNumber, { implantMode: value as TlantiToothState['implantMode'] })}>
                  <SelectTrigger className="w-full bg-surface-raised">
                    <SelectValue placeholder="Implant mode" />
                  </SelectTrigger>
                  <SelectContent>
                    {IMPLANT_MODE_OPTIONS.map((option) => (
                      <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </DetailRow>

              <div className="space-y-3 rounded-2xl border border-border bg-surface-raised p-4">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <p className="text-sm text-text-primary">Pre-op model</p>
                    <p className="text-xs text-text-secondary">Use pre-op scan for waxup/mockup workflows.</p>
                  </div>
                  <Switch checked={Boolean(toothState?.usePreOpModel)} onCheckedChange={(checked) => onPatchTooth(safeToothNumber, { usePreOpModel: checked })} aria-label="Use pre-op model" />
                </div>
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <p className="text-sm text-text-primary">Extra gingiva scan</p>
                    <p className="text-xs text-text-secondary">Enable gingiva mask or soft tissue support.</p>
                  </div>
                  <Switch checked={Boolean(toothState?.useExtraGingivaScan)} onCheckedChange={(checked) => onPatchTooth(safeToothNumber, { useExtraGingivaScan: checked })} aria-label="Use extra gingiva scan" />
                </div>
              </div>
            </div>
          </section>

          <section className="rounded-2xl border border-border bg-card p-4">
            <div className="mb-3 flex items-center gap-2">
              <CircleDot className="size-4 text-text-secondary" />
              <h3 className="text-sm font-semibold text-text-display">Bridge helpers</h3>
            </div>

            <div className="grid gap-3 text-sm text-text-secondary">
              <div className="rounded-2xl border border-border bg-surface-raised p-3">
                <p className="font-medium text-text-primary">Omit in bridge</p>
                <p className="mt-1 text-xs text-text-secondary">Use this when a tooth is missing and should act as a bridge gap so connectors can span across it.</p>
              </div>
              <div className="rounded-2xl border border-border bg-surface-raised p-3">
                <p className="font-medium text-text-primary">Adjacent tooth</p>
                <p className="mt-1 text-xs text-text-secondary">Marks a healthy scanned neighbor for context without restoring it.</p>
              </div>
              <div className="rounded-2xl border border-border bg-surface-raised p-3">
                <p className="font-medium text-text-primary">Antagonist</p>
                <p className="mt-1 text-xs text-text-secondary">Marks the opposing tooth used for occlusion and antagonist scan workflows.</p>
              </div>
            </div>
          </section>
        </div>

        <SheetFooter className="border-t border-border px-5 py-4">
          <div className="flex w-full items-center justify-between gap-3">
            <button type="button" onClick={() => onClearTooth(safeToothNumber)} className="rounded-2xl border border-border px-4 py-2 text-sm text-text-secondary transition-colors hover:text-text-primary">
              Clear tooth
            </button>
            <button type="button" onClick={() => onOpenChange(false)} className="rounded-2xl bg-text-display px-4 py-2 text-sm font-semibold text-black">
              Apply setup
            </button>
          </div>
        </SheetFooter>
      </SheetContent>
    </Sheet>
  );
}
