//! Patient domain model

use chrono::{NaiveDate, DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use validator::Validate;

use crate::enums::{Gender, IdDocumentType};

/// Patient entity - core clinical subject
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct Patient {
    pub id: Uuid,
    
    /// Unique patient number (e.g., PAC-2024-00001)
    #[validate(length(min = 1, max = 50))]
    pub patient_number: String,
    
    #[validate(length(min = 1, max = 100))]
    pub first_name: String,
    
    #[validate(length(min = 1, max = 100))]
    pub last_name: String,
    
    /// Optional middle name
    pub middle_name: Option<String>,
    
    pub birth_date: NaiveDate,
    
    pub gender: Gender,
    
    /// Primary phone number
    #[validate(length(min = 10, max = 20))]
    pub phone: String,
    
    /// Secondary phone number
    pub phone_secondary: Option<String>,
    
    #[validate(email)]
    pub email: Option<String>,
    
    /// Full address
    pub address: Option<PatientAddress>,
    
    /// ID Document number (INE, Passport, etc.)
    pub id_document: Option<String>,
    
    /// Type of ID document
    pub id_document_type: Option<IdDocumentType>,
    
    /// Occupation/Profession
    pub occupation: Option<String>,
    
    /// Workplace
    pub workplace: Option<String>,
    
    /// Emergency contact information
    pub emergency_contact: Option<EmergencyContact>,
    
    /// Known allergies (comma-separated or JSON array)
    pub allergies: Option<String>,
    
    /// Medical conditions and history
    pub medical_history: Option<MedicalHistory>,
    
    /// Referring doctor or source
    pub referral_source: Option<String>,
    
    /// General notes
    pub notes: Option<String>,
    
    /// Patient photo URL or path
    pub photo_url: Option<String>,
    
    /// Insurance information
    pub insurance: Option<InsuranceInfo>,
    
    /// Preferred reminder channel
    pub preferred_reminder: Option<String>,
    
    /// Active status
    pub active: bool,
    
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl Patient {
    pub fn new(
        first_name: String,
        last_name: String,
        birth_date: NaiveDate,
        gender: Gender,
        phone: String,
    ) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            patient_number: String::new(), // Generated by system
            first_name,
            last_name,
            middle_name: None,
            birth_date,
            gender,
            phone,
            phone_secondary: None,
            email: None,
            address: None,
            id_document: None,
            id_document_type: None,
            occupation: None,
            workplace: None,
            emergency_contact: None,
            allergies: None,
            medical_history: None,
            referral_source: None,
            notes: None,
            photo_url: None,
            insurance: None,
            preferred_reminder: None,
            active: true,
            created_at: now,
            updated_at: now,
        }
    }
    
    pub fn full_name(&self) -> String {
        match &self.middle_name {
            Some(middle) => format!("{} {} {}", self.first_name, middle, self.last_name),
            None => format!("{} {}", self.first_name, self.last_name),
        }
    }
    
    pub fn age(&self) -> i32 {
        let today = Utc::now().date_naive();
        let mut age = today.year() - self.birth_date.year();
        if today.ordinal() < self.birth_date.ordinal() {
            age -= 1;
        }
        age
    }
}

/// Patient address
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct PatientAddress {
    pub street: String,
    pub number: Option<String>,
    pub interior: Option<String>,
    pub neighborhood: Option<String>,
    pub city: String,
    pub state: String,
    pub postal_code: String,
    pub country: String,
}

/// Emergency contact
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmergencyContact {
    pub name: String,
    pub relationship: String,
    pub phone: String,
    pub phone_secondary: Option<String>,
}

/// Medical history
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct MedicalHistory {
    /// Current medications
    pub medications: Vec<String>,
    
    /// Medical conditions (diabetes, hypertension, etc.)
    pub conditions: Vec<String>,
    
    /// Previous surgeries
    pub surgeries: Vec<String>,
    
    /// Blood type
    pub blood_type: Option<String>,
    
    /// Is pregnant (for female patients)
    pub pregnant: Option<bool>,
    
    /// Is nursing (for female patients)
    pub nursing: Option<bool>,
    
    /// Has heart problems
    pub heart_problems: bool,
    
    /// Has bleeding disorders
    pub bleeding_disorders: bool,
    
    /// Recent hospitalizations
    pub hospitalizations: Option<String>,
    
    /// Physician name
    pub physician_name: Option<String>,
    
    /// Physician phone
    pub physician_phone: Option<String>,
    
    /// Additional notes
    pub notes: Option<String>,
}

/// Insurance information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InsuranceInfo {
    pub provider: String,
    pub policy_number: String,
    pub group_number: Option<String>,
    pub holder_name: String,
    pub relationship: String,
    pub phone: Option<String>,
    pub valid_until: Option<NaiveDate>,
}

/// Patient list item (for lists and search results)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PatientListItem {
    pub id: Uuid,
    pub patient_number: String,
    pub full_name: String,
    pub phone: String,
    pub email: Option<String>,
    pub age: i32,
    pub last_visit: Option<DateTime<Utc>>,
    pub next_appointment: Option<DateTime<Utc>>,
    pub balance: rust_decimal::Decimal,
    pub active: bool,
}

/// Create patient DTO
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct CreatePatient {
    #[validate(length(min = 1, max = 100))]
    pub first_name: String,
    
    #[validate(length(min = 1, max = 100))]
    pub last_name: String,
    
    pub middle_name: Option<String>,
    
    pub birth_date: NaiveDate,
    
    pub gender: Gender,
    
    #[validate(length(min = 10, max = 20))]
    pub phone: String,
    
    pub phone_secondary: Option<String>,
    
    #[validate(email)]
    pub email: Option<String>,
    
    pub address: Option<PatientAddress>,
    
    pub id_document: Option<String>,
    
    pub id_document_type: Option<IdDocumentType>,
    
    pub occupation: Option<String>,
    
    pub emergency_contact: Option<EmergencyContact>,
    
    pub allergies: Option<String>,
    
    pub medical_history: Option<MedicalHistory>,
    
    pub notes: Option<String>,
}

/// Update patient DTO
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct UpdatePatient {
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub middle_name: Option<String>,
    pub birth_date: Option<NaiveDate>,
    pub gender: Option<Gender>,
    pub phone: Option<String>,
    pub phone_secondary: Option<String>,
    pub email: Option<String>,
    pub address: Option<PatientAddress>,
    pub id_document: Option<String>,
    pub id_document_type: Option<IdDocumentType>,
    pub occupation: Option<String>,
    pub workplace: Option<String>,
    pub emergency_contact: Option<EmergencyContact>,
    pub allergies: Option<String>,
    pub medical_history: Option<MedicalHistory>,
    pub referral_source: Option<String>,
    pub notes: Option<String>,
    pub photo_url: Option<String>,
    pub insurance: Option<InsuranceInfo>,
    pub preferred_reminder: Option<String>,
    pub active: Option<bool>,
}

/// Patient search filters
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct PatientFilters {
    pub query: Option<String>,          // Search in name, phone, email
    pub patient_number: Option<String>,
    pub active_only: Option<bool>,
    pub gender: Option<Gender>,
    pub age_min: Option<i32>,
    pub age_max: Option<i32>,
    pub has_upcoming_appointment: Option<bool>,
    pub has_balance: Option<bool>,
    pub created_after: Option<DateTime<Utc>>,
    pub created_before: Option<DateTime<Utc>>,
}

use chrono::Datelike;
