// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AngleUnit } from "./AngleUnit"

/**
 * An angle value with its unit
 */
export type Angle = {
  /**
   * Value in the specified unit
   */
  value: number
  /**
   * The unit of the value
   */
  unit: AngleUnit
}
