// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vec3 } from "./Vec3"

/**
 * Bounding box
 */
export type BoundingBox = { min: Vec3; max: Vec3 }
