// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SurfaceType } from "./SurfaceType"
import type { Vec3 } from "./Vec3"

/**
 * Information about a face in the shape topology
 */
export type FaceInfo = {
  /**
   * Face index (0-based)
   */
  index: number
  /**
   * Type of surface
   */
  surfaceType: SurfaceType
  /**
   * Normal direction at face center
   */
  normal: Vec3
  /**
   * Is the face orientation reversed
   */
  isReversed: boolean
  /**
   * Surface area of the face
   */
  area: number
  /**
   * Number of edges bounding this face
   */
  numEdges: number
  /**
   * Semantic label: "top", "bottom", "side", "front", "back", "left", "right", "curved_side", "spherical", "toroidal", "freeform"
   */
  label: string
}
