// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LengthUnit } from "./LengthUnit"

/**
 * A length value with its unit
 */
export type Length = {
  /**
   * Value in the specified unit
   */
  value: number
  /**
   * The unit of the value
   */
  unit: LengthUnit
}
