// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FaceInfo } from "./FaceInfo"

/**
 * Mesh data for visualization
 */
export type MeshData = {
  /**
   * Optional ID of the node that generated this mesh
   */
  nodeId?: string
  vertices: Array<number>
  normals: Array<number>
  indices: Array<number>
  /**
   * Face index for each triangle (which face generated this triangle)
   */
  faceIds?: Array<number>
  /**
   * Information about each face in the mesh
   */
  faces?: Array<FaceInfo>
}
