// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vec3 } from "./Vec3"

/**
 * Plane definition
 */
export type Plane = { origin: Vec3; normal: Vec3; x_axis: Vec3 }
