// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AngleUnit } from "./AngleUnit"
import type { LengthUnit } from "./LengthUnit"

/**
 * Unit system configuration for a document/project
 */
export type UnitSystem = {
  /**
   * Primary length unit for display
   */
  length: LengthUnit
  /**
   * Primary angle unit for display
   */
  angle: AngleUnit
  /**
   * Precision for length display (decimal places)
   */
  length_precision: number
  /**
   * Precision for angle display (decimal places)
   */
  angle_precision: number
}
