// Generated by Copilot
import React, { lazy, Suspense, useCallback, useEffect, useMemo, useState } from 'react';
import { MotionConfig } from 'framer-motion';
import { ThemeMode } from './types';
import { TitleBarDragRegion } from './components/TitleBarDragRegion';
import { TlantiWorkspacePreloader } from './components/preloaders/TlantiWorkspacePreloader';
import { ToastProvider } from './components/ui/use-toast';
import { WorkspaceErrorBoundary } from './components/workspaces/WorkspaceErrorBoundary';
import { AppWorkspaceId, WORKSPACE_TITLES } from './components/workspaces/workspace.config';
import { buildWorkspaceUrl, getWorkspaceLaunchContext, type WorkspaceLaunchContext } from './lib/workspace-routing';
import type { WorkspaceContextSyncRequest } from './lib/workspace-shell-contract';
import { CommandPalette, commandRegistry } from './features/command-palette';
import { HotkeyHelpOverlay, hotkeyRegistry } from './features/hotkeys';
import { I18nProvider } from './lib/i18n';

const TlantiDbWorkspace = lazy(() => import('./components/workspaces/tlanti-db/TlantiDbWorkspace').then((module) => ({ default: module.TlantiDbWorkspace })));
const TlantiCadWorkspace = lazy(() => import('./components/workspaces/tlanti-cad/TlantiCadWorkspace').then((module) => ({ default: module.TlantiCadWorkspace })));

const BOOT_PRELOADER_MIN_MS = 320;
const WORKSPACE_TRANSITION_MS = 420;

const App: React.FC = () => {
  const initialLaunchContext = useMemo(() => getWorkspaceLaunchContext(), []);
  const [language, setLanguage] = useState<'en' | 'es' | 'fr' | 'it' | 'pt' | 'ru'>('es');
  const [themeMode, setThemeMode] = useState<ThemeMode>('dark');
  const [workspaceContext, setWorkspaceContext] = useState<WorkspaceLaunchContext>(initialLaunchContext);
  const [activeWorkspace, setActiveWorkspace] = useState<AppWorkspaceId>(initialLaunchContext.workspace);
  const [bootReady, setBootReady] = useState(false);
  const [preloaderSubtitle, setPreloaderSubtitle] = useState<string>(WORKSPACE_TITLES.boot);
  const [showPreloader, setShowPreloader] = useState(true);

  useEffect(() => {
    // Apply theme to body
    if (themeMode === 'light') {
      document.documentElement.classList.add('light');
      document.documentElement.classList.remove('dark');
      document.documentElement.style.setProperty('--bg-color', '#f5f5f5');
      document.documentElement.style.setProperty('--text-color', '#000000');
    } else {
      document.documentElement.classList.remove('light');
      document.documentElement.classList.add('dark');
      document.documentElement.style.setProperty('--bg-color', '#000000');
      document.documentElement.style.setProperty('--text-color', '#ffffff');
    }
  }, [themeMode]);

  useEffect(() => {
    const startedAt = performance.now();
    let timeoutId: number | null = null;
    let cancelled = false;

    const completeBoot = () => {
      const elapsed = performance.now() - startedAt;
      const remaining = Math.max(0, BOOT_PRELOADER_MIN_MS - elapsed);

      timeoutId = window.setTimeout(() => {
        if (cancelled) {
          return;
        }

        setBootReady(true);
        setShowPreloader(false);
      }, remaining);
    };

    if (document.readyState === 'complete') {
      completeBoot();
    } else {
      window.addEventListener('load', completeBoot, { once: true });
    }

    return () => {
      cancelled = true;
      if (timeoutId !== null) {
        window.clearTimeout(timeoutId);
      }
      window.removeEventListener('load', completeBoot);
    };
  }, []);

  const runWorkspaceTransition = useCallback((subtitle: string, complete: () => void) => {
    setPreloaderSubtitle(subtitle);
    setShowPreloader(true);

    window.setTimeout(() => {
      complete();
      setShowPreloader(false);
    }, WORKSPACE_TRANSITION_MS);
  }, []);

  const handleEnterCad = useCallback((options?: { caseId?: string; moduleId?: string }) => {
    const nextContext: WorkspaceLaunchContext = {
      ...workspaceContext,
      workspace: 'tlanticad',
      caseId: options?.caseId ?? workspaceContext.caseId,
      module: options?.moduleId ?? undefined,
      title: undefined,
    };

    window.history.replaceState({}, '', buildWorkspaceUrl(nextContext));
    runWorkspaceTransition(WORKSPACE_TITLES.tlanticad, () => {
      setWorkspaceContext(nextContext);
      setActiveWorkspace('tlanticad');
    });
  }, [runWorkspaceTransition, workspaceContext]);

  const handleBackToDb = useCallback(() => {
    const nextContext: WorkspaceLaunchContext = {
      ...workspaceContext,
      workspace: 'tlantidb',
      module: undefined,
      title: undefined,
    };

    window.history.replaceState({}, '', buildWorkspaceUrl(nextContext));
    runWorkspaceTransition(WORKSPACE_TITLES.tlantidb, () => {
      setWorkspaceContext(nextContext);
      setActiveWorkspace('tlantidb');
    });
  }, [runWorkspaceTransition, workspaceContext]);

  const handleSyncWorkspaceContext = useCallback((request: WorkspaceContextSyncRequest) => {
    const nextContext: WorkspaceLaunchContext = {
      ...workspaceContext,
      workspace: 'tlantidb',
      caseId: request.caseId ?? workspaceContext.caseId,
      module: request.moduleId,
      title: undefined,
    };

    window.history.replaceState({}, '', buildWorkspaceUrl(nextContext));
    setWorkspaceContext(nextContext);
    setActiveWorkspace('tlantidb');
  }, [workspaceContext]);

  const suspenseSubtitle = useMemo(() => {
    return activeWorkspace === 'tlanticad' ? WORKSPACE_TITLES.tlanticad : WORKSPACE_TITLES.tlantidb;
  }, [activeWorkspace]);

  // V203 — register exocad-faithful global hotkeys.
  useEffect(() => {
    const disposers = [
      hotkeyRegistry.register({
        chord: 'ctrl+1',
        label: 'Switch to TlantiCAD Workspace',
        context: 'global',
        run: () => handleBackToDb(),
      }),
      hotkeyRegistry.register({
        chord: 'ctrl+2',
        label: 'Switch to CAD workspace',
        context: 'global',
        run: () => handleEnterCad(),
      }),
      hotkeyRegistry.register({
        chord: 'ctrl+,',
        label: 'Toggle theme',
        context: 'global',
        run: () => setThemeMode((mode) => (mode === 'light' ? 'dark' : 'light')),
        paletteAction: {
          id: 'app.theme.toggle.hotkey',
          label: 'Toggle theme (Ctrl + ,)',
          kind: 'toggle',
          keywords: ['theme', 'dark', 'light'],
        },
      }),
    ];
    return () => {
      for (const dispose of disposers) dispose();
    };
  }, [handleBackToDb, handleEnterCad, setThemeMode]);

  // Seed core navigation actions into the global command palette so Cmd/Ctrl+K
  // is useful from boot. Feature panels register their own contextual actions
  // when they mount.
  useEffect(() => {
    const dispose = commandRegistry.registerAll([
      {
        id: 'app.workspace.tlantidb',
        label: 'Switch to TlantiCAD Workspace',
        kind: 'navigation',
        keywords: ['workspace', 'patients', 'cases', 'launcher', 'db'],
        hotkey: '⌘1',
        icon: 'workflow.module',
        run: () => handleBackToDb(),
      },
      {
        id: 'app.workspace.tlanticad',
        label: 'Switch to CAD workspace',
        kind: 'navigation',
        keywords: ['cad', 'design', 'wizard'],
        hotkey: '⌘2',
        icon: 'workflow.module',
        run: () => handleEnterCad(),
      },
      {
        id: 'app.theme.toggle',
        label: themeMode === 'light' ? 'Switch to dark theme' : 'Switch to light theme',
        kind: 'toggle',
        keywords: ['theme', 'dark', 'light'],
        run: () => setThemeMode((mode) => (mode === 'light' ? 'dark' : 'light')),
      },
    ]);
    return dispose;
  }, [handleBackToDb, handleEnterCad, themeMode, setThemeMode]);

  return (
    <I18nProvider>
    <MotionConfig reducedMotion="user">
      <ToastProvider>
      <TitleBarDragRegion />
      <CommandPalette />
      <HotkeyHelpOverlay />
      <TlantiWorkspacePreloader
        visible={showPreloader}
        title={WORKSPACE_TITLES.app}
        subtitle={preloaderSubtitle}
        themeMode={themeMode}
      />

      {bootReady && (
        <Suspense
          fallback={
            <TlantiWorkspacePreloader
              visible
              title={WORKSPACE_TITLES.app}
              subtitle={suspenseSubtitle}
              themeMode={themeMode}
            />
          }
        >
          <WorkspaceErrorBoundary activeWorkspace={activeWorkspace} themeMode={themeMode} onBackToDb={handleBackToDb}>
            {activeWorkspace === 'tlantidb' ? (
              <TlantiDbWorkspace
                onEnter={handleEnterCad}
                onSyncWorkspaceContext={handleSyncWorkspaceContext}
                language={language} 
                setLanguage={setLanguage} 
                themeMode={themeMode}
                setThemeMode={setThemeMode}
                caseId={workspaceContext.caseId}
                moduleId={workspaceContext.module}
              />
            ) : (
              <TlantiCadWorkspace
                language={language} 
                setLanguage={setLanguage} 
                themeMode={themeMode}
                setThemeMode={setThemeMode}
                caseId={workspaceContext.caseId}
                moduleId={workspaceContext.module}
                onBackToDb={handleBackToDb}
              />
            )}
          </WorkspaceErrorBoundary>
        </Suspense>
      )}
      </ToastProvider>
    </MotionConfig>
    </I18nProvider>
  );
};

export default App;
