// Generated by Copilot
import React, { useMemo, useState } from 'react';
import { ChevronDown, ChevronRight, Eye, EyeOff, Layers3, ScanSearch, Sparkles, FolderOpen } from 'lucide-react';

import type { FileData } from '@/types';
import { cn } from '@/lib/utils';
import { CadResponsivePanel } from './CadResponsivePanel';

interface CadGroupSelectorPanelProps {
  files: FileData[];
  setFiles: React.Dispatch<React.SetStateAction<FileData[]>>;
  compact: boolean;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
}

type SelectorGroup = {
  id: string;
  label: string;
  description: string;
  ids: string[];
};

const TRANSPARENT_OPACITY = 0.35;

export function CadGroupSelectorPanel({ files, setFiles, compact, open = true, onOpenChange }: CadGroupSelectorPanelProps) {
  const [expandedGroups, setExpandedGroups] = useState<Record<string, boolean>>({
    scans: true,
    constructions: true,
    overlays: true,
    hidden: false,
  });

  const groups = useMemo<SelectorGroup[]>(() => {
    const models = files.filter((file) => file.type === 'MODEL').map((file) => file.id);
    const scans = files
      .filter((file) => file.type === 'DICOM' || /scan|dicom|jaw|gingiva|model/i.test(file.name))
      .map((file) => file.id);
    const overlays = files.filter((file) => file.semanticUsage === 'overlay' || file.type === 'IMAGE').map((file) => file.id);
    const hidden = files.filter((file) => !file.visible).map((file) => file.id);

    return [
      { id: 'scans', label: 'Datos de escaneo', description: 'Escaneos, DICOM, mandíbula y encía', ids: scans },
      { id: 'constructions', label: 'Construcciones', description: 'Coronas, waxups, modelos y partes CAD', ids: models },
      { id: 'overlays', label: 'Overlays / Smile', description: 'Imágenes guía, overlays y referencias', ids: overlays },
      { id: 'hidden', label: 'Ocultos', description: 'Objetos actualmente ocultos', ids: hidden },
    ].filter((group) => group.ids.length > 0);
  }, [files]);

  const setVisibility = (ids: string[], visible: boolean) => {
    setFiles((prev) => prev.map((file) => (ids.includes(file.id) ? { ...file, visible } : file)));
  };

  const toggleTransparency = (ids: string[]) => {
    setFiles((prev) => {
      const targetFiles = prev.filter((file) => ids.includes(file.id));
      const shouldUseTransparency = !targetFiles.every((file) => file.opacity <= TRANSPARENT_OPACITY + 0.01);
      return prev.map((file) => {
        if (!ids.includes(file.id)) return file;
        return { ...file, opacity: shouldUseTransparency ? TRANSPARENT_OPACITY : 1 };
      });
    });
  };

  const showAll = () => {
    setFiles((prev) => prev.map((file) => ({ ...file, visible: true })));
  };

  const toggleExpanded = (groupId: string) => {
    setExpandedGroups((prev) => ({ ...prev, [groupId]: !prev[groupId] }));
  };

  const getGroupIcon = (groupId: string) => {
    switch (groupId) {
      case 'scans':
        return <ScanSearch className="size-4 text-text-secondary" />;
      case 'constructions':
        return <Layers3 className="size-4 text-text-secondary" />;
      case 'overlays':
        return <Sparkles className="size-4 text-text-secondary" />;
      default:
        return <FolderOpen className="size-4 text-text-secondary" />;
    }
  };

  return (
    <CadResponsivePanel
      title="Selector de grupos"
      compact={compact}
      open={open}
      onOpenChange={onOpenChange}
      desktopClassName="left-6 top-24 bottom-[28rem] w-72"
      contentClassName="space-y-3"
      headerAction={
        <button
          type="button"
          onClick={showAll}
          className="rounded-lg px-2 py-1 text-[11px] uppercase text-text-secondary transition-colors hover:bg-surface-raised hover:text-text-primary"
        >
          Mostrar todo
        </button>
      }
    >
      <p className="text-pretty text-xs text-text-secondary">
        Muestre u oculte grupos completos del visor y active transparencia rápida como en el selector de grupos de DentalCAD.
      </p>

      <div className="space-y-2">
        {groups.map((group) => {
          const expanded = expandedGroups[group.id] ?? false;
          const groupFiles = files.filter((file) => group.ids.includes(file.id));
          const allVisible = groupFiles.every((file) => file.visible);
          const partiallyVisible = groupFiles.some((file) => file.visible) && !allVisible;

          return (
            <div key={group.id} className="rounded-2xl border border-border bg-card">
              <div className="flex items-center gap-2 px-3 py-2">
                <button
                  type="button"
                  onClick={() => toggleExpanded(group.id)}
                  className="rounded-md p-1 text-text-secondary transition-colors hover:bg-surface-raised hover:text-text-primary"
                  aria-label={`Expandir ${group.label}`}
                >
                  {expanded ? <ChevronDown className="size-4" /> : <ChevronRight className="size-4" />}
                </button>
                {getGroupIcon(group.id)}
                <div className="min-w-0 flex-1">
                  <p className="truncate text-sm font-medium text-text-primary">{group.label}</p>
                  <p className="truncate text-xs text-text-secondary">{group.description}</p>
                </div>
                <button
                  type="button"
                  onClick={() => setVisibility(group.ids, !allVisible)}
                  className={cn(
                    'rounded-md p-1 transition-colors',
                    allVisible || partiallyVisible
                      ? 'text-text-primary hover:bg-surface-raised'
                      : 'text-text-secondary hover:bg-surface-raised hover:text-text-primary',
                  )}
                  aria-label={`Alternar visibilidad de ${group.label}`}
                >
                  {allVisible || partiallyVisible ? <Eye className="size-4" /> : <EyeOff className="size-4" />}
                </button>
              </div>

              {expanded ? (
                <div className="border-t border-border px-3 py-3">
                  <div className="mb-3 flex items-center justify-between gap-2 text-[11px] uppercase text-text-secondary">
                    <span>{groupFiles.length} elementos</span>
                    <button
                      type="button"
                      onClick={() => toggleTransparency(group.ids)}
                      className="rounded-full border border-border px-2 py-1 transition-colors hover:bg-surface-raised hover:text-text-primary"
                    >
                      Transparente
                    </button>
                  </div>
                  <div className="space-y-1.5">
                    {groupFiles.map((file) => (
                      <div key={file.id} className="flex items-center justify-between gap-2 rounded-xl border border-border bg-surface px-3 py-2">
                        <div className="min-w-0">
                          <p className="truncate text-xs text-text-primary">{file.name}</p>
                          <p className="text-[11px] text-text-secondary">{file.type}</p>
                        </div>
                        <button
                          type="button"
                          onClick={() => setVisibility([file.id], !file.visible)}
                          className="rounded-md p-1 text-text-secondary transition-colors hover:bg-surface-raised hover:text-text-primary"
                          aria-label={`Alternar ${file.name}`}
                        >
                          {file.visible ? <Eye className="size-4" /> : <EyeOff className="size-4" />}
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              ) : null}
            </div>
          );
        })}
      </div>
    </CadResponsivePanel>
  );
}
