// Generated by Copilot
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { cn } from '@/lib/utils';

interface CadResponsivePanelProps {
  title: string;
  compact: boolean;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  desktopClassName?: string;
  contentClassName?: string;
  headerAction?: React.ReactNode;
  children: React.ReactNode;
}

export function CadResponsivePanel({
  title,
  compact,
  open = true,
  onOpenChange,
  desktopClassName,
  contentClassName,
  headerAction,
  children,
}: CadResponsivePanelProps) {
  const content = (
    <ScrollArea className="h-full">
      <div className={cn('p-4', contentClassName)}>{children}</div>
    </ScrollArea>
  );

  if (compact) {
    return (
      <Sheet open={open} onOpenChange={onOpenChange}>
        <SheetContent
          side="bottom"
          className="h-[min(70dvh,34rem)] rounded-t-2xl border-border bg-surface p-0 text-text-primary"
        >
          <SheetHeader className="border-b border-border px-4 py-3">
            <div className="flex items-center justify-between gap-4 pr-8">
              <SheetTitle className="font-mono text-sm uppercase tracking-widest text-text-primary">
                {title}
              </SheetTitle>
              {headerAction}
            </div>
            <SheetDescription className="sr-only">
              Responsive workspace panel for {title.toLowerCase()}.
            </SheetDescription>
          </SheetHeader>
          {content}
        </SheetContent>
      </Sheet>
    );
  }

  return (
    <Card className={cn('absolute z-40 overflow-hidden border-border bg-surface text-text-primary shadow-2xl', desktopClassName)}>
      <CardHeader className="border-b border-border px-4 py-3">
        <div className="flex items-center justify-between gap-4">
          <CardTitle className="font-mono text-sm uppercase tracking-widest text-text-secondary">
            {title}
          </CardTitle>
          {headerAction}
        </div>
      </CardHeader>
      <CardContent className="p-0">{content}</CardContent>
    </Card>
  );
}
