// Generated by Copilot
import { useEffect } from 'react'
import { useThree } from '@react-three/fiber'
import * as THREE from 'three'

import type { ThemeMode } from '@/types'

interface OrbitLikeControls {
  target: THREE.Vector3
  update: () => void
}

interface CameraControllerProps {
  zoomTrigger: number
  selectedMesh: THREE.Object3D | null
}

export function CameraController({ zoomTrigger, selectedMesh }: CameraControllerProps) {
  const { camera, controls, scene } = useThree()

  useEffect(() => {
    if (zoomTrigger <= 0) return

    const box = new THREE.Box3()

    if (selectedMesh) {
      box.setFromObject(selectedMesh)
    } else {
      scene.traverse((child) => {
        if ((child as THREE.Mesh).isMesh && child.visible) box.expandByObject(child)
      })
    }

    if (box.isEmpty()) return

    const size = box.getSize(new THREE.Vector3())
    const center = box.getCenter(new THREE.Vector3())
    const maxDim = Math.max(size.x, size.y, size.z)
    const fov = (camera as THREE.PerspectiveCamera).fov * (Math.PI / 180)
    let cameraZ = Math.abs(maxDim / 2 / Math.tan(fov / 2))
    cameraZ *= 1.5

    camera.position.set(center.x, center.y, center.z + cameraZ)
    camera.lookAt(center)

    if (controls) {
      const orbitControls = controls as unknown as OrbitLikeControls
      orbitControls.target.copy(center)
      orbitControls.update()
    }
  }, [zoomTrigger, selectedMesh, camera, controls, scene])

  return null
}

interface CropManagerProps {
  cropStart: { x: number; y: number } | null
  cropEnd: { x: number; y: number } | null
  setCropPlanes: (planes: THREE.Plane[]) => void
}

export function CropManager({ cropStart, cropEnd, setCropPlanes }: CropManagerProps) {
  const { camera, size, gl } = useThree()

  useEffect(() => {
    gl.localClippingEnabled = true
  }, [gl])

  useEffect(() => {
    if (!cropStart || !cropEnd) return

    const xMin = (Math.min(cropStart.x, cropEnd.x) / size.width) * 2 - 1
    const xMax = (Math.max(cropStart.x, cropEnd.x) / size.width) * 2 - 1
    const yMin = -(Math.max(cropStart.y, cropEnd.y) / size.height) * 2 + 1
    const yMax = -(Math.min(cropStart.y, cropEnd.y) / size.height) * 2 + 1

    const tl = new THREE.Vector3(xMin, yMax, -1).unproject(camera)
    const tr = new THREE.Vector3(xMax, yMax, -1).unproject(camera)
    const bl = new THREE.Vector3(xMin, yMin, -1).unproject(camera)
    const br = new THREE.Vector3(xMax, yMin, -1).unproject(camera)
    const cp = camera.position

    const leftPlane = new THREE.Plane().setFromCoplanarPoints(cp, tl, bl)
    const rightPlane = new THREE.Plane().setFromCoplanarPoints(cp, br, tr)
    const topPlane = new THREE.Plane().setFromCoplanarPoints(cp, tr, tl)
    const bottomPlane = new THREE.Plane().setFromCoplanarPoints(cp, bl, br)

    setCropPlanes([leftPlane, rightPlane, topPlane, bottomPlane])
  }, [cropStart, cropEnd, camera, size, setCropPlanes])

  return null
}

interface CadSceneLightingProps {
  themeMode: ThemeMode
}

export function CadSceneLighting({ themeMode }: CadSceneLightingProps) {
  const isDark = themeMode === 'dark'

  return (
    <>
      <ambientLight intensity={isDark ? 0.75 : 0.95} color={isDark ? '#f5f5f5' : '#ffffff'} />
      <hemisphereLight
        intensity={isDark ? 0.65 : 0.8}
        color={isDark ? '#dfe7ff' : '#ffffff'}
        groundColor={isDark ? '#1a1a1a' : '#d9d9d9'}
      />
      <directionalLight
        position={[8, 12, 10]}
        intensity={isDark ? 1.15 : 1}
        color={isDark ? '#ffffff' : '#f8fbff'}
      />
      <directionalLight
        position={[-6, 5, -8]}
        intensity={isDark ? 0.45 : 0.35}
        color={isDark ? '#9fb7ff' : '#ffd7b3'}
      />
    </>
  )
}