// Generated by Copilot
import React, { useState } from 'react';
import {
  Boxes,
  Eye,
  HelpCircle,
  MousePointer2,
  Save,
  Search,
  Settings2,
  Sparkles,
  View,
  Wand2,
} from 'lucide-react';

import { cn } from '@/lib/utils';
import { CadResponsivePanel } from './CadResponsivePanel';

interface CadWorkflowGuidePanelProps {
  compact: boolean;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  expertMode: boolean;
}

type GuideSection = {
  id: string;
  title: string;
  icon: React.ComponentType<{ className?: string }>;
  summary: string;
  bullets: string[];
};

const GUIDE_SECTIONS: GuideSection[] = [
  {
    id: 'navigate',
    title: 'Navegar en 3D',
    icon: MousePointer2,
    summary: 'Rotar, mover, hacer zoom y recentrar el centro de rotación desde el visor.',
    bullets: [
      'Botón derecho + arrastre: rota alrededor del centro de rotación.',
      'Rueda del mouse: zoom hacia la posición del cursor.',
      'Botón central: recentra la vista en el punto seleccionado.',
      'Las flechas de vista permiten saltar entre las seis direcciones principales.',
    ],
  },
  {
    id: 'visibility',
    title: 'Mostrar / ocultar objetos',
    icon: Eye,
    summary: 'Controle grupos de escaneo, construcciones y overlays sin perder foco en el caso.',
    bullets: [
      'Use el Selector de grupos para mostrar u ocultar familias completas de objetos.',
      'Puede abrir un grupo para controlar la visibilidad objeto por objeto.',
      'La opción transparente ayuda a inspeccionar estructuras internas y overlays.',
    ],
  },
  {
    id: 'menu',
    title: 'Menú CAD y guardado',
    icon: Save,
    summary: 'File, Edit, Modules, View y Settings concentran las funciones permanentes del flujo CAD.',
    bullets: [
      'Import / Export / Asset Library están disponibles desde File y la barra principal.',
      'Guardar se entiende como snapshot/export de escena del estado actual.',
      'En modo experto el menú contextual se amplía con operaciones avanzadas.',
    ],
  },
  {
    id: 'expert',
    title: 'Modo experto / asistente',
    icon: Sparkles,
    summary: 'El asistente simplifica decisiones; el modo experto desbloquea opciones por diente y por contexto.',
    bullets: [
      'Asistente: secuencia guiada con valores razonables y foco en avanzar.',
      'Experto: menús contextuales más amplios y selecciones más granulares.',
      'Use CTRL para seleccionar múltiples dientes u objetos cuando proceda.',
    ],
  },
  {
    id: 'tools',
    title: 'Herramientas y selecciones',
    icon: Wand2,
    summary: 'Medición, corte, captura, DICOM, CAM y funciones clínicas pueden activarse según el caso.',
    bullets: [
      'Measurement, Clip, Crop, Segment y Sculpt viven en el dock inferior.',
      'Las selecciones funcionales activan vistas clínicas como antagonistas, Smile o cloud.',
      'DICOM y módulos clínicos se lanzan desde Modules o la búsqueda contextual.',
    ],
  },
  {
    id: 'search',
    title: 'Buscar, vistas y menú contextual',
    icon: Search,
    summary: 'Use la búsqueda contextual, agregue vistas personalizadas y aplique funciones desde el contexto correcto.',
    bullets: [
      'Buscar… abre acciones por palabra clave con Ctrl+K o desde el botón superior.',
      'Añadir vista personalizada memoriza cámara y target del punto actual.',
      'Clic derecho en fondo: menú general; clic derecho en objeto: menú específico.',
    ],
  },
  {
    id: 'qa',
    title: 'Preguntas frecuentes',
    icon: HelpCircle,
    summary: 'Respuestas rápidas para casos de múltiples dientes y diferencias entre contexto de fondo y selección.',
    bullets: [
      'Para aplicar una función a varios dientes, selecciónelos y lance el menú contextual adecuado.',
      'El fondo afecta al caso completo; un objeto seleccionado afecta solo a ese objeto o grupo.',
      'La disponibilidad de opciones depende de la etapa del diseño y del modo activo.',
    ],
  },
];

export function CadWorkflowGuidePanel({ compact, open = true, onOpenChange, expertMode }: CadWorkflowGuidePanelProps) {
  const [openSection, setOpenSection] = useState<string>('navigate');

  return (
    <CadResponsivePanel
      title="Guía CAD"
      compact={compact}
      open={open}
      onOpenChange={onOpenChange}
      desktopClassName="left-6 bottom-24 h-[22rem] w-80"
      contentClassName="space-y-3"
      headerAction={<Settings2 className="size-4 text-text-secondary" />}
    >
      <div className="rounded-2xl border border-border bg-card px-3 py-3">
        <p className="text-[11px] uppercase text-text-secondary">Modo actual</p>
        <div className="mt-2 flex flex-wrap gap-2">
          <span className={cn('rounded-full border px-2.5 py-1 text-[11px]', expertMode ? 'border-[#125A2C] bg-[#125A2C]/10 text-[#125A2C]' : 'border-[#B01825] bg-[#B01825]/10 text-[#B01825]')}>
            {expertMode ? 'Experto' : 'Asistente'}
          </span>
          <span className="rounded-full border border-border px-2.5 py-1 text-[11px] text-text-secondary">DentalCAD flow map</span>
        </div>
      </div>

      {GUIDE_SECTIONS.map((section) => {
        const Icon = section.icon;
        const expanded = openSection === section.id;
        return (
          <div key={section.id} className="rounded-2xl border border-border bg-card">
            <button
              type="button"
              onClick={() => setOpenSection(expanded ? '' : section.id)}
              className="flex w-full items-start gap-3 px-3 py-3 text-left"
            >
              <Icon className="mt-0.5 size-4 text-text-secondary" />
              <div className="min-w-0 flex-1">
                <p className="text-sm font-medium text-text-primary">{section.title}</p>
                <p className="mt-1 text-pretty text-xs text-text-secondary">{section.summary}</p>
              </div>
              <View className={cn('mt-0.5 size-4 text-text-secondary transition-transform', expanded && 'rotate-180')} />
            </button>

            {expanded ? (
              <div className="border-t border-border px-3 py-3">
                <ul className="space-y-2 text-xs text-text-secondary">
                  {section.bullets.map((bullet) => (
                    <li key={bullet} className="flex gap-2">
                      <span className="mt-1 size-1.5 rounded-full bg-text-display" />
                      <span className="text-pretty">{bullet}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ) : null}
          </div>
        );
      })}
    </CadResponsivePanel>
  );
}
