// Generated by Copilot
import { useEffect, useMemo, useState } from 'react';

export interface ViewportProfile {
  width: number;
  height: number;
  isCompact: boolean;
  isTablet: boolean;
  isDesktop: boolean;
  isUltraWide: boolean;
  isShort: boolean;
}

function getViewportSize() {
  if (typeof window === 'undefined') {
    return { width: 1440, height: 900 };
  }

  return {
    width: window.innerWidth,
    height: window.innerHeight,
  };
}

export function useViewportProfile(): ViewportProfile {
  const [size, setSize] = useState(getViewportSize);

  useEffect(() => {
    const onResize = () => setSize(getViewportSize());
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  }, []);

  return useMemo(() => {
    const { width, height } = size;
    return {
      width,
      height,
      isCompact: width < 1100,
      isTablet: width >= 1100 && width < 1440,
      isDesktop: width >= 1440,
      isUltraWide: width >= 1920,
      isShort: height < 820,
    };
  }, [size]);
}
