use crate::error::Result;
use crate::extrude::Mesh3D;
use std::io::Write;
use std::path::Path;

/// Export a 3D mesh to Wavefront OBJ format.
pub fn write_obj(mesh: &Mesh3D, path: &Path, mtl_name: Option<&str>) -> Result<()> {
    let mut file = std::fs::File::create(path)?;

    // Header
    writeln!(file, "# Generated by Mimesis (TlantiStudio)")?;
    writeln!(file, "# Vertices: {} Triangles: {}", mesh.vertex_count, mesh.triangle_count)?;

    if let Some(mtl) = mtl_name {
        writeln!(file, "mtllib {}.mtl", mtl)?;
    }

    writeln!(file)?;

    // Vertices
    for v in &mesh.vertices {
        writeln!(file, "v {:.6} {:.6} {:.6}", v.x, v.y, v.z)?;
    }

    writeln!(file)?;

    // Texture coordinates
    for tc in &mesh.tex_coords {
        writeln!(file, "vt {:.6} {:.6}", tc.u, tc.v)?;
    }

    writeln!(file)?;

    // Normals
    for n in &mesh.normals {
        writeln!(file, "vn {:.6} {:.6} {:.6}", n.x, n.y, n.z)?;
    }

    writeln!(file)?;

    if let Some(mtl) = mtl_name {
        writeln!(file, "usemtl {}", mtl)?;
    }

    // Faces (1-indexed in OBJ format)
    for face_tri in mesh.faces.chunks(3) {
        if face_tri.len() == 3 {
            writeln!(
                file,
                "f {}/{}/{} {}/{}/{} {}/{}/{}",
                face_tri[0][0] + 1, face_tri[0][1] + 1, face_tri[0][2] + 1,
                face_tri[1][0] + 1, face_tri[1][1] + 1, face_tri[1][2] + 1,
                face_tri[2][0] + 1, face_tri[2][1] + 1, face_tri[2][2] + 1,
            )?;
        }
    }

    Ok(())
}

/// Write a simple MTL material file referencing the front texture.
pub fn write_mtl(path: &Path, material_name: &str, texture_file: &str) -> Result<()> {
    let mut file = std::fs::File::create(path)?;

    writeln!(file, "# Generated by Mimesis (TlantiStudio)")?;
    writeln!(file, "newmtl {}", material_name)?;
    writeln!(file, "Ka 1.000 1.000 1.000")?;
    writeln!(file, "Kd 1.000 1.000 1.000")?;
    writeln!(file, "Ks 0.000 0.000 0.000")?;
    writeln!(file, "Ns 10.000")?;
    writeln!(file, "d 1.0")?;
    writeln!(file, "illum 2")?;
    writeln!(file, "map_Kd textures/{}", texture_file)?;

    Ok(())
}
