// Generated by Copilot
// Módulo de notaciones dentales y utilidades odontológicas

#![allow(dead_code)]

use serde::{Deserialize, Serialize};

/// Información de un diente
#[derive(Debug, Serialize, Deserialize)]
pub struct ToothInfo {
    pub universal: u8,
    pub fdi: String,
    pub palmer: String,
    pub name: String,
    pub quadrant: u8,
    pub is_primary: bool,
    pub tooth_type: String,
}

/// Resultado de conversión de notación
#[derive(Debug, Serialize, Deserialize)]
pub struct NotationResult {
    pub universal: u8,
    pub fdi: String,
    pub palmer: String,
}

/// Convierte un número de diente entre diferentes notaciones
/// 
/// # Arguments
/// * `value` - Valor del diente en la notación de origen
/// * `from_notation` - Notación de origen: "universal", "fdi", "palmer"
/// * `to_notation` - Notación destino: "universal", "fdi", "palmer"
#[tauri::command]
pub fn convert_tooth_notation(
    value: String,
    from_notation: String,
    to_notation: String,
) -> Result<String, String> {
    // Primero convertir a universal como paso intermedio
    let universal: u8 = match from_notation.to_lowercase().as_str() {
        "universal" => value.parse().map_err(|_| "Número universal inválido")?,
        "fdi" => fdi_to_universal(&value)?,
        "palmer" => palmer_to_universal(&value)?,
        _ => return Err("Notación de origen no soportada".to_string()),
    };
    
    // Convertir de universal a la notación destino
    let result = match to_notation.to_lowercase().as_str() {
        "universal" => universal.to_string(),
        "fdi" => universal_to_fdi(universal)?,
        "palmer" => universal_to_palmer(universal)?,
        _ => return Err("Notación destino no soportada".to_string()),
    };
    
    Ok(result)
}

/// Obtiene información completa de un diente
/// 
/// # Arguments
/// * `tooth_number` - Número de diente en notación universal
#[tauri::command]
pub fn get_tooth_info(tooth_number: u8) -> Result<ToothInfo, String> {
    if tooth_number < 1 || tooth_number > 32 {
        return Err("Número de diente inválido (debe ser 1-32)".to_string());
    }
    
    // Determinar el cuadrante (1-4 para permanentes)
    let quadrant = match tooth_number {
        1..=8 => 1,    // Superior derecho
        9..=16 => 2,   // Superior izquierdo
        17..=24 => 3,  // Inferior izquierdo
        25..=32 => 4,  // Inferior derecho
        _ => 0,
    };
    
    // Determinar tipo de diente
    let tooth_type = get_tooth_type(tooth_number);
    
    // Determinar nombre del diente
    let name = get_tooth_name(tooth_number);
    
    Ok(ToothInfo {
        universal: tooth_number,
        fdi: universal_to_fdi(tooth_number).unwrap_or_default(),
        palmer: universal_to_palmer(tooth_number).unwrap_or_default(),
        name,
        quadrant,
        is_primary: false,
        tooth_type,
    })
}

/// Convierte FDI a Universal
fn fdi_to_universal(fdi: &str) -> Result<u8, String> {
    let num: u8 = fdi.parse().map_err(|_| "Número FDI inválido")?;
    let quadrant = num / 10;
    let tooth = num % 10;
    
    if tooth < 1 || tooth > 8 {
        return Err("Número de diente FDI inválido".to_string());
    }
    
    let universal = match quadrant {
        1 => 9 - tooth,       // Superior derecho: 11->8, 18->1
        2 => 8 + tooth,       // Superior izquierdo: 21->9, 28->16  
        3 => 16 + tooth,      // Inferior izquierdo: 31->17, 38->24
        4 => 41 - tooth,      // Inferior derecho: 41->32, 48->25
        _ => return Err("Cuadrante FDI inválido".to_string()),
    };
    
    Ok(universal)
}

/// Convierte Universal a FDI
fn universal_to_fdi(universal: u8) -> Result<String, String> {
    if universal < 1 || universal > 32 {
        return Err("Número universal inválido".to_string());
    }
    
    let (quadrant, tooth) = match universal {
        1..=8 => (1, 9 - universal),      // Q1: 1->18, 8->11
        9..=16 => (2, universal - 8),     // Q2: 9->21, 16->28
        17..=24 => (3, universal - 16),   // Q3: 17->31, 24->38
        25..=32 => (4, 41 - universal),   // Q4: 25->48, 32->41
        _ => return Err("Número universal inválido".to_string()),
    };
    
    Ok(format!("{}{}", quadrant, tooth))
}

/// Convierte Palmer a Universal (simplificado)
fn palmer_to_universal(palmer: &str) -> Result<u8, String> {
    // Palmer usa símbolos especiales, aquí simplificamos
    // Formato esperado: "UR1", "UL1", "LR1", "LL1" donde U=Upper, L=Lower, R=Right, L=Left
    if palmer.len() < 3 {
        return Err("Notación Palmer inválida".to_string());
    }
    
    let upper = palmer.starts_with('U') || palmer.starts_with('u');
    let right = palmer.chars().nth(1) == Some('R') || palmer.chars().nth(1) == Some('r');
    let tooth: u8 = palmer[2..].parse().map_err(|_| "Número Palmer inválido")?;
    
    if tooth < 1 || tooth > 8 {
        return Err("Número de diente Palmer inválido".to_string());
    }
    
    let universal = match (upper, right) {
        (true, true) => 9 - tooth,      // Superior derecho
        (true, false) => 8 + tooth,     // Superior izquierdo
        (false, false) => 16 + tooth,   // Inferior izquierdo
        (false, true) => 41 - tooth,    // Inferior derecho
    };
    
    Ok(universal)
}

/// Convierte Universal a Palmer
fn universal_to_palmer(universal: u8) -> Result<String, String> {
    if universal < 1 || universal > 32 {
        return Err("Número universal inválido".to_string());
    }
    
    let (prefix, tooth) = match universal {
        1..=8 => ("UR", 9 - universal),
        9..=16 => ("UL", universal - 8),
        17..=24 => ("LL", universal - 16),
        25..=32 => ("LR", 41 - universal),
        _ => return Err("Número universal inválido".to_string()),
    };
    
    Ok(format!("{}{}", prefix, tooth))
}

/// Obtiene el tipo de diente según el número universal
fn get_tooth_type(universal: u8) -> String {
    match universal {
        1 | 16 | 17 | 32 => "Tercer molar".to_string(),
        2 | 15 | 18 | 31 => "Segundo molar".to_string(),
        3 | 14 | 19 | 30 => "Primer molar".to_string(),
        4 | 13 | 20 | 29 => "Segundo premolar".to_string(),
        5 | 12 | 21 | 28 => "Primer premolar".to_string(),
        6 | 11 | 22 | 27 => "Canino".to_string(),
        7 | 10 | 23 | 26 => "Incisivo lateral".to_string(),
        8 | 9 | 24 | 25 => "Incisivo central".to_string(),
        _ => "Desconocido".to_string(),
    }
}

/// Obtiene el nombre completo del diente
fn get_tooth_name(universal: u8) -> String {
    let side = match universal {
        1..=8 | 25..=32 => "derecho",
        9..=16 | 17..=24 => "izquierdo",
        _ => "",
    };
    
    let jaw = match universal {
        1..=16 => "superior",
        17..=32 => "inferior",
        _ => "",
    };
    
    let tooth_type = get_tooth_type(universal);
    
    format!("{} {} {}", tooth_type, jaw, side)
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_convert_fdi_to_universal() {
        let result = convert_tooth_notation(
            "11".to_string(),
            "fdi".to_string(),
            "universal".to_string(),
        );
        assert!(result.is_ok());
        assert_eq!(result.unwrap(), "8");
    }
    
    #[test]
    fn test_get_tooth_info() {
        let info = get_tooth_info(1);
        assert!(info.is_ok());
        let info = info.unwrap();
        assert_eq!(info.quadrant, 1);
    }
}
