// Generated by Copilot
// Módulo para manejo de archivos DICOM (radiografías, tomografías)

#![allow(dead_code)]

use dicom::object::{open_file, DefaultDicomObject};
use dicom::dictionary_std::tags;
use serde::{Deserialize, Serialize};
use std::path::Path;

/// Metadatos extraídos de un archivo DICOM
#[derive(Debug, Serialize, Deserialize)]
pub struct DicomMetadata {
    pub patient_name: Option<String>,
    pub patient_id: Option<String>,
    pub patient_birth_date: Option<String>,
    pub patient_sex: Option<String>,
    pub study_date: Option<String>,
    pub study_description: Option<String>,
    pub series_description: Option<String>,
    pub modality: Option<String>,
    pub manufacturer: Option<String>,
    pub institution_name: Option<String>,
    pub referring_physician: Option<String>,
    pub accession_number: Option<String>,
    pub study_id: Option<String>,
    pub series_number: Option<String>,
    pub instance_number: Option<String>,
    pub image_rows: Option<u16>,
    pub image_columns: Option<u16>,
    pub bits_allocated: Option<u16>,
    pub bits_stored: Option<u16>,
    pub pixel_spacing: Option<[f32; 2]>,
    pub slice_thickness: Option<f32>,
    pub window_center: Option<f32>,
    pub window_width: Option<f32>,
}

/// Información de imagen DICOM
#[derive(Debug, Serialize, Deserialize)]
pub struct DicomImageInfo {
    pub file_path: String,
    pub metadata: DicomMetadata,
    pub width: u32,
    pub height: u32,
    pub has_pixel_data: bool,
}

/// Carga un archivo DICOM y retorna sus metadatos
/// 
/// # Arguments
/// * `file_path` - Ruta al archivo DICOM
#[tauri::command]
pub fn load_dicom_file(file_path: String) -> Result<DicomImageInfo, String> {
    let path = Path::new(&file_path);
    
    if !path.exists() {
        return Err("El archivo no existe".to_string());
    }
    
    let obj = open_file(path).map_err(|e| format!("Error al abrir DICOM: {}", e))?;
    let metadata = extract_metadata(&obj);
    let width = metadata.image_columns.unwrap_or(0) as u32;
    let height = metadata.image_rows.unwrap_or(0) as u32;
    let has_pixel_data = obj.element(tags::PIXEL_DATA).is_ok();
    
    Ok(DicomImageInfo {
        file_path,
        metadata,
        width,
        height,
        has_pixel_data,
    })
}

/// Obtiene metadatos detallados de un archivo DICOM
/// 
/// # Arguments
/// * `file_path` - Ruta al archivo DICOM
#[tauri::command]
pub fn get_dicom_metadata(file_path: String) -> Result<DicomMetadata, String> {
    let path = Path::new(&file_path);
    
    if !path.exists() {
        return Err("El archivo no existe".to_string());
    }
    
    let obj = open_file(path).map_err(|e| format!("Error al abrir DICOM: {}", e))?;
    Ok(extract_metadata(&obj))
}

/// Imprime una imagen DICOM (stub)
#[tauri::command]
pub fn print_dicom_image(file_path: String) -> Result<bool, String> {
    let path = Path::new(&file_path);
    
    if !path.exists() {
        return Err("El archivo no existe".to_string());
    }
    
    // TODO: Implementar impresión real
    Ok(true)
}

/// Extrae metadatos de un objeto DICOM
fn extract_metadata(obj: &DefaultDicomObject) -> DicomMetadata {
    DicomMetadata {
        patient_name: get_string_value(obj, tags::PATIENT_NAME),
        patient_id: get_string_value(obj, tags::PATIENT_ID),
        patient_birth_date: get_string_value(obj, tags::PATIENT_BIRTH_DATE),
        patient_sex: get_string_value(obj, tags::PATIENT_SEX),
        study_date: get_string_value(obj, tags::STUDY_DATE),
        study_description: get_string_value(obj, tags::STUDY_DESCRIPTION),
        series_description: get_string_value(obj, tags::SERIES_DESCRIPTION),
        modality: get_string_value(obj, tags::MODALITY),
        manufacturer: get_string_value(obj, tags::MANUFACTURER),
        institution_name: get_string_value(obj, tags::INSTITUTION_NAME),
        referring_physician: get_string_value(obj, tags::REFERRING_PHYSICIAN_NAME),
        accession_number: get_string_value(obj, tags::ACCESSION_NUMBER),
        study_id: get_string_value(obj, tags::STUDY_ID),
        series_number: get_string_value(obj, tags::SERIES_NUMBER),
        instance_number: get_string_value(obj, tags::INSTANCE_NUMBER),
        image_rows: get_u16_value(obj, tags::ROWS),
        image_columns: get_u16_value(obj, tags::COLUMNS),
        bits_allocated: get_u16_value(obj, tags::BITS_ALLOCATED),
        bits_stored: get_u16_value(obj, tags::BITS_STORED),
        pixel_spacing: get_f32_pair(obj, tags::PIXEL_SPACING),
        slice_thickness: get_f32_value(obj, tags::SLICE_THICKNESS),
        window_center: get_f32_value(obj, tags::WINDOW_CENTER),
        window_width: get_f32_value(obj, tags::WINDOW_WIDTH),
    }
}

/// Obtiene un valor string de un tag DICOM
fn get_string_value(obj: &DefaultDicomObject, tag: dicom::core::Tag) -> Option<String> {
    obj.element(tag)
        .ok()
        .and_then(|e| e.to_str().ok())
        .map(|s| s.trim().to_string())
}

/// Obtiene un valor u16 de un tag DICOM
fn get_u16_value(obj: &DefaultDicomObject, tag: dicom::core::Tag) -> Option<u16> {
    obj.element(tag)
        .ok()
        .and_then(|e| e.to_int::<u16>().ok())
}

/// Obtiene un valor f32 de un tag DICOM (toma el primer valor si es múltiple)
fn get_f32_value(obj: &DefaultDicomObject, tag: dicom::core::Tag) -> Option<f32> {
    obj.element(tag)
        .ok()
        .and_then(|e| e.to_str().ok())
        .and_then(|s| s.split('\\').next().map(|v| v.trim().to_string()))
        .and_then(|v| v.parse::<f32>().ok())
}

/// Obtiene un par de valores f32 (pixel spacing) de un tag DICOM
fn get_f32_pair(obj: &DefaultDicomObject, tag: dicom::core::Tag) -> Option<[f32; 2]> {
    let raw = obj.element(tag).ok().and_then(|e| e.to_str().ok())?;
    let values: Vec<f32> = raw
        .split('\\')
        .filter_map(|v| v.trim().parse::<f32>().ok())
        .collect();
    
    if values.len() >= 2 {
        Some([values[0], values[1]])
    } else {
        None
    }
}

/// Tipos de modalidad DICOM comunes en odontología
#[derive(Debug, Serialize, Deserialize)]
pub enum DentalModality {
    /// Radiografía intraoral
    IO,
    /// Radiografía panorámica
    PX,
    /// Tomografía computarizada Cone Beam
    CT,
    /// Fotografía digital
    XC,
    /// Otro
    Other(String),
}

impl From<&str> for DentalModality {
    fn from(s: &str) -> Self {
        match s.to_uppercase().as_str() {
            "IO" => DentalModality::IO,
            "PX" => DentalModality::PX,
            "CT" => DentalModality::CT,
            "XC" => DentalModality::XC,
            other => DentalModality::Other(other.to_string()),
        }
    }
}

/// Resultado de upload de DICOM
/// Generated by Copilot
#[derive(Debug, Serialize, Deserialize)]
pub struct DicomUploadResult {
    pub document_id: String,
    pub file_path: String,
    pub metadata: DicomMetadata,
}

/// Subir archivo DICOM y guardarlo asociado a un paciente
/// Generated by Copilot
#[tauri::command]
pub async fn upload_dicom_file(
    patient_id: String,
    source_path: String,
    description: Option<String>
) -> Result<DicomUploadResult, String> {
    log::info!("IPC: upload_dicom_file patient={} source={}", patient_id, source_path);
    
    let source = Path::new(&source_path);
    if !source.exists() {
        return Err("Archivo fuente no encontrado".to_string());
    }
    
    // Validar que es un archivo DICOM válido
    let obj = open_file(source).map_err(|e| format!("No es un archivo DICOM válido: {}", e))?;
    let metadata = extract_metadata(&obj);
    
    // Obtener directorio de documentos de la app
    let app_docs = dirs::document_dir()
        .unwrap_or_else(|| std::path::PathBuf::from("."))
        .join("Tlanti4Dental")
        .join("dicom")
        .join(&patient_id);
    
    std::fs::create_dir_all(&app_docs)
        .map_err(|e| format!("Error creando directorio: {}", e))?;
    
    // Generar nombre único para el archivo
    let doc_id = uuid::Uuid::new_v4().to_string();
    let timestamp = chrono::Utc::now().format("%Y%m%d_%H%M%S");
    let extension = source.extension()
        .and_then(|e| e.to_str())
        .unwrap_or("dcm");
    
    let dest_filename = format!("{}_{}.{}", doc_id, timestamp, extension);
    let dest_path = app_docs.join(&dest_filename);
    
    // Copiar archivo
    std::fs::copy(source, &dest_path)
        .map_err(|e| format!("Error copiando archivo: {}", e))?;
    
    // Guardar en base de datos con sqlx
    let pool = tlanti_db::get_pool().await?;
    let now = chrono::Utc::now().to_rfc3339();
    let modality = metadata.modality.clone().unwrap_or_else(|| "Unknown".to_string());
    let file_size = std::fs::metadata(&dest_path).map(|m| m.len()).unwrap_or(0) as i64;
    let desc = description.clone().unwrap_or_else(|| metadata.study_description.clone().unwrap_or_default());
    let path_str = dest_path.to_string_lossy().to_string();
    
    sqlx::query(
        "INSERT INTO documents (id, patient_id, type, category, name, description, file_path, file_type, file_size, created_at, updated_at)
         VALUES (?, ?, 'dicom', ?, ?, ?, ?, 'application/dicom', ?, ?, ?)"
    )
    .bind(&doc_id)
    .bind(&patient_id)
    .bind(&modality)
    .bind(&dest_filename)
    .bind(&desc)
    .bind(&path_str)
    .bind(file_size)
    .bind(&now)
    .bind(&now)
    .execute(&pool)
    .await
    .map_err(|e| format!("Error guardando en DB: {}", e))?;
    
    log::info!("DICOM guardado: {} -> {:?}", doc_id, dest_path);
    
    Ok(DicomUploadResult {
        document_id: doc_id,
        file_path: dest_path.to_string_lossy().to_string(),
        metadata,
    })
}

/// Listar archivos DICOM de un paciente
/// Generated by Copilot
#[tauri::command]
pub async fn list_patient_dicom_files(patient_id: String) -> Result<Vec<DicomImageInfo>, String> {
    log::info!("IPC: list_patient_dicom_files patient={}", patient_id);
    
    let pool = tlanti_db::get_pool().await?;
    
    let rows: Vec<(String, String)> = sqlx::query_as(
        "SELECT id, file_path FROM documents WHERE patient_id = ? AND type = 'dicom' ORDER BY created_at DESC"
    )
    .bind(&patient_id)
    .fetch_all(&pool)
    .await
    .unwrap_or_default();
    
    let mut results = Vec::new();
    for (doc_id, file_path) in rows {
        if let Ok(info) = load_dicom_file(file_path.clone()) {
            results.push(DicomImageInfo {
                file_path: doc_id,  // Usar doc_id como referencia
                ..info
            });
        }
    }
    
    Ok(results)
}

/// Eliminar archivo DICOM
/// Generated by Copilot
#[tauri::command]
pub async fn delete_dicom_file(document_id: String) -> Result<bool, String> {
    log::info!("IPC: delete_dicom_file id={}", document_id);
    
    let pool = tlanti_db::get_pool().await?;
    
    // Obtener ruta del archivo
    let file_path: Option<String> = sqlx::query_scalar(
        "SELECT file_path FROM documents WHERE id = ? AND type = 'dicom'"
    )
    .bind(&document_id)
    .fetch_optional(&pool)
    .await
    .ok()
    .flatten();
    
    // Eliminar archivo físico
    if let Some(path) = file_path {
        let _ = std::fs::remove_file(&path);
    }
    
    // Eliminar de la base de datos
    sqlx::query("DELETE FROM documents WHERE id = ?")
        .bind(&document_id)
        .execute(&pool)
        .await
        .map_err(|e| e.to_string())?;
    
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_modality_conversion() {
        let modality: DentalModality = "PX".into();
        matches!(modality, DentalModality::PX);
    }
}
