// Generated by Copilot
// Módulo de GPU y Machine Learning
// Soporte para Metal (macOS) y DirectX 12/CUDA (Windows)

use serde::{Deserialize, Serialize};
use std::fs;
use std::sync::{Mutex, OnceLock};
use std::time::Instant;

/// Información del GPU detectado
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GpuInfo {
    pub name: String,
    pub vendor: String,
    pub backend: String,
    pub memory_mb: u64,
    pub supports_compute: bool,
}

/// Información detallada del GPU para ML
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GpuInfoDetailed {
    pub name: String,
    pub vendor: String,
    pub driver_info: Option<String>,
    pub backend: String,
    pub memory_total: Option<u64>,
    pub memory_available: Option<u64>,
    pub features: Vec<String>,
    pub is_supported: bool,
}

/// Modelo ML registrado
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MlModel {
    pub id: String,
    pub name: String,
    pub description: Option<String>,
    pub model_type: String,
    pub version: String,
    pub file_path: String,
    pub file_size: u64,
    pub input_shape: Vec<i64>,
    pub output_shape: Vec<i64>,
    pub labels: Option<Vec<String>>,
    pub created_at: String,
    pub is_loaded: bool,
}

/// Resultado de análisis ML
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnalysisResult {
    pub id: String,
    pub image_path: String,
    pub model_id: String,
    pub model_name: String,
    pub detections: Vec<Detection>,
    pub processing_time_ms: u64,
    pub gpu_used: bool,
    pub timestamp: String,
    pub metadata: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Detection {
    pub id: String,
    pub label: String,
    pub confidence: f32,
    pub bounding_box: Option<BoundingBox>,
    pub mask: Option<Vec<Vec<f32>>>,
    pub tooth_id: Option<String>,
    pub severity: Option<String>,
    pub description: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BoundingBox {
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnalysisHistory {
    pub id: String,
    pub patient_id: String,
    pub patient_name: String,
    pub image_path: String,
    pub model_type: String,
    pub detections_count: i32,
    pub analyzed_by: String,
    pub analyzed_at: String,
    pub reviewed: bool,
    pub reviewed_by: Option<String>,
    pub reviewed_at: Option<String>,
    pub notes: Option<String>,
}

// ============================================================================
// ESTADO EN MEMORIA (STUB)
// ============================================================================

static ML_MODELS: OnceLock<Mutex<Vec<MlModel>>> = OnceLock::new();
static ANALYSIS_HISTORY: OnceLock<Mutex<Vec<AnalysisHistory>>> = OnceLock::new();

fn models_store() -> &'static Mutex<Vec<MlModel>> {
    ML_MODELS.get_or_init(|| Mutex::new(Vec::new()))
}

fn history_store() -> &'static Mutex<Vec<AnalysisHistory>> {
    ANALYSIS_HISTORY.get_or_init(|| Mutex::new(Vec::new()))
}

// ============================================================================
// COMANDOS TAURI
// ============================================================================

/// Obtiene información del GPU actual
#[tauri::command]
pub fn get_gpu_info() -> Result<GpuInfo, String> {
    #[cfg(target_os = "macos")]
    {
        get_metal_gpu_info()
    }
    
    #[cfg(target_os = "windows")]
    {
        get_dx12_gpu_info()
    }
    
    #[cfg(not(any(target_os = "macos", target_os = "windows")))]
    {
        Err("Plataforma no soportada - Solo Windows y macOS".to_string())
    }
}

// ============================================================================
// macOS - Metal GPU
// ============================================================================

#[cfg(target_os = "macos")]
fn get_metal_gpu_info() -> Result<GpuInfo, String> {
    use metal::Device;
    
    let device = Device::system_default()
        .ok_or("No se encontró dispositivo Metal")?;
    
    let name = device.name().to_string();
    let supports_ml = device.supports_family(metal::MTLGPUFamily::Apple7);
    
    Ok(GpuInfo {
        name: name.clone(),
        vendor: "Apple".to_string(),
        backend: "metal".to_string(),
        memory_mb: 0,
        supports_compute: supports_ml,
    })
}

// ============================================================================
// Windows - DirectX 12
// ============================================================================

#[cfg(target_os = "windows")]
fn get_dx12_gpu_info() -> Result<GpuInfo, String> {
    // Usar wgpu para detectar adaptadores
    let instance = wgpu::Instance::new(&wgpu::InstanceDescriptor {
        backends: wgpu::Backends::DX12,
        ..Default::default()
    });
    
    let adapters: Vec<_> = instance.enumerate_adapters(wgpu::Backends::DX12);
    
    if let Some(adapter) = adapters.first() {
        let info = adapter.get_info();
        
        let vendor = match info.vendor {
            0x10DE => "NVIDIA".to_string(),
            0x1002 => "AMD".to_string(),
            0x8086 => "Intel".to_string(),
            _ => format!("Vendor {:X}", info.vendor),
        };
        
        Ok(GpuInfo {
            name: info.name.clone(),
            vendor,
            backend: "directx12".to_string(),
            memory_mb: 0,
            supports_compute: true,
        })
    } else {
        Err("No se encontró adaptador DirectX 12".to_string())
    }
}

// ============================================================================
// COMANDOS TAURI - GPU/ML
// ============================================================================

#[tauri::command]
pub fn detect_gpu() -> Result<GpuInfoDetailed, String> {
    Ok(build_gpu_detail())
}

#[tauri::command]
pub fn get_gpu_status() -> Result<GpuInfoDetailed, String> {
    Ok(build_gpu_detail())
}

fn build_gpu_detail() -> GpuInfoDetailed {
    let info = get_gpu_info().ok();
    let (name, vendor, backend, memory_total, is_supported) = match info {
        Some(gpu) => {
            let backend = match gpu.backend.as_str() {
                "directx12" => "dx12".to_string(),
                "metal" => "metal".to_string(),
                other => other.to_string(),
            };
            (
                gpu.name,
                gpu.vendor,
                backend,
                Some(gpu.memory_mb),
                gpu.supports_compute,
            )
        }
        None => (
            "CPU".to_string(),
            "Generic".to_string(),
            "cpu".to_string(),
            None,
            false,
        ),
    };

    let mut features = vec![];
    if is_supported {
        features.push("compute".to_string());
    }

    GpuInfoDetailed {
        name,
        vendor,
        driver_info: None,
        backend,
        memory_total,
        memory_available: None,
        features,
        is_supported,
    }
}

#[tauri::command]
pub fn get_ml_models(model_type: Option<String>) -> Result<Vec<MlModel>, String> {
    let models = models_store()
        .lock()
        .map_err(|_| "Error al bloquear modelos".to_string())?;

    let list = match model_type {
        Some(ref mtype) => models.iter().cloned().filter(|m| &m.model_type == mtype).collect(),
        None => models.clone(),
    };

    Ok(list)
}

#[tauri::command]
pub fn load_ml_model(model_id: String) -> Result<bool, String> {
    let mut models = models_store()
        .lock()
        .map_err(|_| "Error al bloquear modelos".to_string())?;

    if let Some(model) = models.iter_mut().find(|m| m.id == model_id) {
        model.is_loaded = true;
        return Ok(true);
    }

    Err("Modelo no encontrado".to_string())
}

#[tauri::command]
pub fn unload_ml_model(model_id: String) -> Result<bool, String> {
    let mut models = models_store()
        .lock()
        .map_err(|_| "Error al bloquear modelos".to_string())?;

    if let Some(model) = models.iter_mut().find(|m| m.id == model_id) {
        model.is_loaded = false;
        return Ok(true);
    }

    Ok(false)
}

#[tauri::command]
pub fn import_ml_model(
    file_path: String,
    name: String,
    model_type: String,
    labels: Option<Vec<String>>,
) -> Result<MlModel, String> {
    let id = uuid::Uuid::new_v4().to_string();
    let now = chrono::Utc::now().to_rfc3339();
    let file_size = fs::metadata(&file_path).map(|m| m.len()).unwrap_or(0);

    let model = MlModel {
        id,
        name,
        description: None,
        model_type,
        version: "1.0.0".to_string(),
        file_path,
        file_size,
        input_shape: vec![],
        output_shape: vec![],
        labels,
        created_at: now,
        is_loaded: false,
    };

    let mut models = models_store()
        .lock()
        .map_err(|_| "Error al bloquear modelos".to_string())?;
    models.push(model.clone());

    Ok(model)
}

#[tauri::command]
pub fn delete_ml_model(model_id: String) -> Result<bool, String> {
    let mut models = models_store()
        .lock()
        .map_err(|_| "Error al bloquear modelos".to_string())?;
    let before = models.len();
    models.retain(|m| m.id != model_id);
    Ok(models.len() != before)
}

#[tauri::command]
pub fn analyze_dental_image(
    image_path: String,
    model_id: String,
    confidence_threshold: f32,
    max_detections: i32,
    use_gpu: bool,
) -> Result<AnalysisResult, String> {
    let start = Instant::now();
    let models = models_store()
        .lock()
        .map_err(|_| "Error al bloquear modelos".to_string())?;
    let model = models.iter().find(|m| m.id == model_id);
    let model_name = model.map(|m| m.name.clone()).unwrap_or_else(|| "Modelo".to_string());

    let is_gpu_supported = build_gpu_detail().is_supported;
    let gpu_used = use_gpu && is_gpu_supported;

    let mut detections = vec![];
    if max_detections > 0 && confidence_threshold < 0.95 {
        detections.push(Detection {
            id: uuid::Uuid::new_v4().to_string(),
            label: "Hallazgo".to_string(),
            confidence: confidence_threshold.max(0.6),
            bounding_box: Some(BoundingBox {
                x: 0.25,
                y: 0.25,
                width: 0.4,
                height: 0.4,
            }),
            mask: None,
            tooth_id: None,
            severity: Some("medium".to_string()),
            description: Some("Detección simulada".to_string()),
        });
    }

    let processing_time_ms = start.elapsed().as_millis() as u64;

    Ok(AnalysisResult {
        id: uuid::Uuid::new_v4().to_string(),
        image_path,
        model_id,
        model_name,
        detections,
        processing_time_ms,
        gpu_used,
        timestamp: chrono::Utc::now().to_rfc3339(),
        metadata: None,
    })
}

#[tauri::command]
pub fn get_analysis_history(
    patient_id: Option<String>,
    model_type: Option<String>,
    _from_date: Option<String>,
    _to_date: Option<String>,
    reviewed: Option<bool>,
) -> Result<Vec<AnalysisHistory>, String> {
    let history = history_store()
        .lock()
        .map_err(|_| "Error al bloquear historial".to_string())?;

    let list = history
        .iter()
        .cloned()
        .filter(|h| patient_id.as_ref().map(|p| &h.patient_id == p).unwrap_or(true))
        .filter(|h| model_type.as_ref().map(|m| &h.model_type == m).unwrap_or(true))
        .filter(|h| reviewed.map(|r| h.reviewed == r).unwrap_or(true))
        .collect();

    Ok(list)
}

#[tauri::command]
pub fn save_analysis_result(
    patient_id: String,
    result: AnalysisResult,
    analyzed_by: String,
) -> Result<AnalysisHistory, String> {
    let history_entry = AnalysisHistory {
        id: uuid::Uuid::new_v4().to_string(),
        patient_id,
        patient_name: "".to_string(),
        image_path: result.image_path,
        model_type: result.model_id,
        detections_count: result.detections.len() as i32,
        analyzed_by,
        analyzed_at: chrono::Utc::now().to_rfc3339(),
        reviewed: false,
        reviewed_by: None,
        reviewed_at: None,
        notes: None,
    };

    let mut history = history_store()
        .lock()
        .map_err(|_| "Error al bloquear historial".to_string())?;
    history.push(history_entry.clone());

    Ok(history_entry)
}

#[tauri::command]
pub fn mark_analysis_reviewed(
    history_id: String,
    reviewed_by: String,
    notes: Option<String>,
) -> Result<AnalysisHistory, String> {
    let mut history = history_store()
        .lock()
        .map_err(|_| "Error al bloquear historial".to_string())?;

    if let Some(entry) = history.iter_mut().find(|h| h.id == history_id) {
        entry.reviewed = true;
        entry.reviewed_by = Some(reviewed_by);
        entry.reviewed_at = Some(chrono::Utc::now().to_rfc3339());
        entry.notes = notes;
        return Ok(entry.clone());
    }

    Err("Registro no encontrado".to_string())
}

#[tauri::command]
pub fn enhance_dental_image(
    image_path: String,
    _denoise: bool,
    _sharpen: bool,
    _contrast: bool,
) -> Result<String, String> {
    Ok(image_path)
}

#[tauri::command]
pub fn generate_analysis_heatmap(
    _result: AnalysisResult,
    output_path: String,
) -> Result<String, String> {
    Ok(output_path)
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_gpu_info_struct() {
        let info = GpuInfo {
            name: "Test GPU".to_string(),
            vendor: "Test".to_string(),
            backend: "metal".to_string(),
            memory_mb: 1024,
            supports_compute: true,
        };
        assert!(info.supports_compute);
    }
}
