// Generated by Copilot
import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { once } from 'node:events';
import process from 'node:process';
import { setTimeout as delay } from 'node:timers/promises';

import puppeteer from 'puppeteer';

const BASE_URL = process.env.SMOKE_BASE_URL ?? 'http://localhost:3000/';
const SHOULD_SPAWN_TAURI = process.argv.includes('--spawn-tauri');

async function waitForServer(url: string, attempts = 120) {
  for (let index = 0; index < attempts; index += 1) {
    try {
      const response = await fetch(url);
      if (response.ok) {
        return;
      }
    } catch {
      // noop
    }

    await delay(1000);
  }

  throw new Error(`Smoke server did not become ready: ${url}`);
}

function pipeLogs(child: ChildProcessWithoutNullStreams) {
  child.stdout.on('data', (chunk) => process.stdout.write(chunk));
  child.stderr.on('data', (chunk) => process.stderr.write(chunk));
}

function startViteDev() {
  const viteCommand = process.platform === 'win32' ? 'node_modules/.bin/vite.cmd' : 'node_modules/.bin/vite';
  const child = spawn(viteCommand, ['--host', '127.0.0.1', '--port', '3000', '--strictPort'], {
    cwd: process.cwd(),
    env: process.env,
    stdio: 'pipe',
  });

  pipeLogs(child);

  return child;
}

function startTauriRuntime() {
  const child = spawn('cargo', ['run', '--manifest-path', 'src-tauri/Cargo.toml', '--no-default-features', '--color', 'always', '--'], {
    cwd: process.cwd(),
    env: process.env,
    stdio: 'pipe',
  });

  pipeLogs(child);

  return child;
}

async function runSmoke() {
  const browser = await puppeteer.launch({
    headless: true,
    defaultViewport: { width: 1440, height: 900 },
  });

  try {
    const page = await browser.newPage();
    await page.goto(BASE_URL, { waitUntil: 'domcontentloaded', timeout: 45_000 });
    await page.waitForSelector('text/Workspace', { timeout: 15000 });
    await page.waitForSelector('text/Quick actions', { timeout: 15000 });
    await page.waitForSelector('text/CAD Module', { timeout: 15000 });

    const backendText = await page.$('::-p-text(Backend integrations)');
    if (backendText) {
      throw new Error('Backend integrations should not be visible in TlantiDB.');
    }

    const cadUrl = new URL(BASE_URL);
    cadUrl.searchParams.set('workspace', 'tlanticad');
    cadUrl.searchParams.set('caseId', 'puppeteer-smoke');
    cadUrl.searchParams.set('module', 'cad');
    await page.goto(cadUrl.toString(), { waitUntil: 'domcontentloaded', timeout: 45_000 });

    await page.waitForSelector('[data-testid="cad-desktop-shell"]', { timeout: 30000 });
    await page.waitForSelector('[data-testid="cad-three-viewport"] canvas', { timeout: 30000 });

    console.log('Puppeteer smoke test passed.');
  } finally {
    await browser.close();
  }
}

async function main() {
  let viteProcess: ChildProcessWithoutNullStreams | null = null;
  let tauriProcess: ChildProcessWithoutNullStreams | null = null;

  try {
    if (SHOULD_SPAWN_TAURI) {
      viteProcess = startViteDev();
      await waitForServer(BASE_URL);
      tauriProcess = startTauriRuntime();
      await delay(1500);
    }

    await runSmoke();
  } finally {
    if (tauriProcess) {
      tauriProcess.kill('SIGTERM');
      await Promise.race([once(tauriProcess, 'exit'), delay(4000)]);
    }

    if (viteProcess) {
      viteProcess.kill('SIGTERM');
      await Promise.race([once(viteProcess, 'exit'), delay(4000)]);
    }
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
