// Generated by Copilot
import { init as coreInit } from '@cornerstonejs/core';
import { init as dicomImageLoaderInit } from '@cornerstonejs/dicom-image-loader';
import {
  init as toolsInit,
  addTool,
  LengthTool,
  PanTool,
  WindowLevelTool,
  ZoomTool,
} from '@cornerstonejs/tools';

let cornerstoneReadyPromise: Promise<void> | null = null;
let toolsRegistered = false;

const registerToolsOnce = () => {
  if (toolsRegistered) {
    return;
  }

  addTool(WindowLevelTool);
  addTool(PanTool);
  addTool(ZoomTool);
  addTool(LengthTool);

  toolsRegistered = true;
};

export const ensureCornerstoneReady = async () => {
  if (!cornerstoneReadyPromise) {
    cornerstoneReadyPromise = (async () => {
      await coreInit();
      await dicomImageLoaderInit({
        maxWebWorkers: Math.max(1, Math.min(4, navigator.hardwareConcurrency || 1)),
      });
      await toolsInit();
      registerToolsOnce();
    })();
  }

  return cornerstoneReadyPromise;
};
