"use client";

// Generated by Copilot
import {
  Activity,
  BrainCircuit,
  FileCode2,
  FilePlus,
  FolderOpen,
  FolderSearch,
  Layers3,
  ScanSearch,
  Settings,
  Share2,
  Workflow,
} from "lucide-react";

import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarSeparator,
  MenubarSub,
  MenubarSubContent,
  MenubarSubTrigger,
  MenubarTrigger,
} from "@/components/ui/menubar";

interface AppMenuBarProps {
  className?: string;
  onCreateCase: () => void;
  onOpenCase: () => void;
  onOpenDicom: () => void;
  onOpenCad: () => void;
  onOpenAiDesign: () => void;
  onOpenImplant: () => void;
  onOpenSplint: () => void;
  onOpenManufacture: () => void;
  onExportCase: () => void;
  onGenerateInteropXml: () => void;
  onRevealCaseFolder: () => void;
  onOpenSettings: () => void;
}

export default function AppMenuBar({
  className,
  onCreateCase,
  onOpenCase,
  onOpenDicom,
  onOpenCad,
  onOpenAiDesign,
  onOpenImplant,
  onOpenSplint,
  onOpenManufacture,
  onExportCase,
  onGenerateInteropXml,
  onRevealCaseFolder,
  onOpenSettings,
}: AppMenuBarProps) {
  return (
    <Menubar className={className}>
      <MenubarMenu>
        <MenubarTrigger className="flex items-center gap-2">
          <FilePlus className="size-4" />
          Cases
        </MenubarTrigger>
        <MenubarContent className="w-60">
          <MenubarItem className="flex items-center gap-2" onClick={onCreateCase}>
            <FilePlus className="size-4" />
            New case
          </MenubarItem>
          <MenubarItem className="flex items-center gap-2" onClick={onOpenCase}>
            <FolderOpen className="size-4" />
            Open existing case
          </MenubarItem>
        </MenubarContent>
      </MenubarMenu>

      <MenubarMenu>
        <MenubarTrigger className="flex items-center gap-2">
          <ScanSearch className="size-4" />
          DICOM
        </MenubarTrigger>
        <MenubarContent className="w-60">
          <MenubarItem className="flex items-center gap-2" onClick={onOpenDicom}>
            <ScanSearch className="size-4" />
            Open DICOM viewer
          </MenubarItem>
          <MenubarSeparator />
          <MenubarItem className="flex items-center gap-2" onClick={onOpenAiDesign}>
            <BrainCircuit className="size-4" />
            AI segmentation route
          </MenubarItem>
        </MenubarContent>
      </MenubarMenu>

      <MenubarMenu>
        <MenubarTrigger className="flex items-center gap-2">
          <Layers3 className="size-4" />
          CAD
        </MenubarTrigger>
        <MenubarContent className="w-60">
          <MenubarItem className="flex items-center gap-2" onClick={onOpenCad}>
            <Layers3 className="size-4" />
            Open CAD Design
          </MenubarItem>
          <MenubarSub>
            <MenubarSubTrigger className="flex items-center gap-2">
              <Workflow className="size-4" />
              Clinical modules
            </MenubarSubTrigger>
            <MenubarSubContent className="w-52">
              <MenubarItem className="flex items-center gap-2" onClick={onOpenAiDesign}>
                <BrainCircuit className="size-4" />
                AI design
              </MenubarItem>
              <MenubarItem className="flex items-center gap-2" onClick={onOpenImplant}>
                <Activity className="size-4" />
                Implant planning
              </MenubarItem>
              <MenubarItem className="flex items-center gap-2" onClick={onOpenSplint}>
                <Workflow className="size-4" />
                Splint workflow
              </MenubarItem>
              <MenubarItem className="flex items-center gap-2" onClick={onOpenManufacture}>
                <Share2 className="size-4" />
                Manufacture prep
              </MenubarItem>
            </MenubarSubContent>
          </MenubarSub>
        </MenubarContent>
      </MenubarMenu>

      <MenubarMenu>
        <MenubarTrigger className="flex items-center gap-2">
          <FileCode2 className="size-4" />
          Files
        </MenubarTrigger>
        <MenubarContent className="w-60">
          <MenubarItem className="flex items-center gap-2" onClick={onExportCase}>
            <Share2 className="size-4" />
            Export case snapshot
          </MenubarItem>
          <MenubarItem className="flex items-center gap-2" onClick={onGenerateInteropXml}>
            <FileCode2 className="size-4" />
            Generate XML interop
          </MenubarItem>
          <MenubarItem className="flex items-center gap-2" onClick={onRevealCaseFolder}>
            <FolderSearch className="size-4" />
            Reveal case folder
          </MenubarItem>
        </MenubarContent>
      </MenubarMenu>

      <MenubarMenu>
        <MenubarTrigger className="flex items-center gap-2">
          <Settings className="size-4" />
          Workspace
        </MenubarTrigger>
        <MenubarContent className="w-56">
          <MenubarItem className="flex items-center gap-2" onClick={onOpenSettings}>
            <Settings className="size-4" />
            Runtime and preferences
          </MenubarItem>
        </MenubarContent>
      </MenubarMenu>
    </Menubar>
  );
}
