// Generated by Copilot
import React from 'react';

import HoverGradientNavBar from '@/components/ui/hover-gradient-nav-bar';

export default function HoverGradientNavBarDemo() {
  return <HoverGradientNavBar />;
}
