'use client';

// Generated by Copilot
import React from 'react';
import { motion, type Variants } from 'framer-motion';
import { Bell, HelpCircle, LogOut, Settings, User } from 'lucide-react';

import { cn } from '@/lib/utils';

export interface HoverGradientNavItem {
  id: string;
  icon: React.ReactNode;
  label: string;
  onClick?: () => void;
  href?: string;
  gradient?: string;
  iconClassName?: string;
}

interface HoverGradientNavBarProps {
  items?: HoverGradientNavItem[];
  className?: string;
  embedded?: boolean;
  showLabels?: boolean;
}

const defaultItems: HoverGradientNavItem[] = [
  {
    id: 'notifications',
    icon: <Bell className="size-4" />,
    label: 'Notifications',
    href: '#',
    gradient: 'radial-gradient(circle, rgba(91,155,246,0.18) 0%, rgba(91,155,246,0.06) 52%, rgba(91,155,246,0) 100%)',
    iconClassName: 'group-hover:text-[#5b9bf6]',
  },
  {
    id: 'settings',
    icon: <Settings className="size-4" />,
    label: 'Settings',
    href: '#',
    gradient: 'radial-gradient(circle, rgba(215,25,33,0.18) 0%, rgba(215,25,33,0.06) 52%, rgba(215,25,33,0) 100%)',
    iconClassName: 'group-hover:text-[#d71921]',
  },
  {
    id: 'profile',
    icon: <User className="size-4" />,
    label: 'Profile',
    href: '#',
    gradient: 'radial-gradient(circle, rgba(255,255,255,0.14) 0%, rgba(255,255,255,0.05) 52%, rgba(255,255,255,0) 100%)',
    iconClassName: 'group-hover:text-white',
  },
  {
    id: 'help',
    icon: <HelpCircle className="size-4" />,
    label: 'Help',
    href: '#',
    gradient: 'radial-gradient(circle, rgba(212,168,67,0.18) 0%, rgba(212,168,67,0.06) 52%, rgba(212,168,67,0) 100%)',
    iconClassName: 'group-hover:text-[#d4a843]',
  },
  {
    id: 'logout',
    icon: <LogOut className="size-4" />,
    label: 'Logout',
    href: '#',
    gradient: 'radial-gradient(circle, rgba(153,153,153,0.18) 0%, rgba(153,153,153,0.06) 52%, rgba(153,153,153,0) 100%)',
    iconClassName: 'group-hover:text-text-primary',
  },
];

const frontVariants: Variants = {
  initial: { rotateX: 0, opacity: 1 },
  hover: { rotateX: -90, opacity: 0 },
};

const backVariants: Variants = {
  initial: { rotateX: 90, opacity: 0 },
  hover: { rotateX: 0, opacity: 1 },
};

const glowVariants: Variants = {
  initial: { opacity: 0, scale: 0.8 },
  hover: { opacity: 1, scale: 1.8 },
};

const sharedTransition = {
  type: 'spring' as const,
  stiffness: 220,
  damping: 22,
  duration: 0.18,
};

export default function HoverGradientNavBar({
  items = defaultItems,
  className,
  embedded = false,
  showLabels = true,
}: HoverGradientNavBarProps) {
  return (
    <div className={cn(embedded ? 'w-full' : 'fixed bottom-0 left-0 z-50 w-full md:bottom-4 md:left-1/2 md:w-fit md:-translate-x-1/2', className)}>
      <motion.nav
        className={cn(
          'relative border border-border bg-surface/95 backdrop-blur-sm',
          embedded ? 'w-full rounded-[1.75rem] px-2 py-2 shadow-sm' : 'mx-auto rounded-none px-2 py-2 shadow-lg md:rounded-[1.75rem] md:px-4 md:py-3',
        )}
        initial="initial"
        whileHover="hover"
      >
        <ul className={cn('relative z-10 flex items-center', embedded ? 'justify-between gap-1' : 'justify-around gap-1 md:justify-center md:gap-3')}>
          {items.map((item) => {
            const Component = item.href ? 'a' : 'button';

            return (
              <motion.li key={item.id} className={cn('relative', embedded ? 'flex-1' : 'flex-1 md:flex-none')}>
                <motion.div className="group relative block overflow-visible rounded-2xl" initial="initial" whileHover="hover" style={{ perspective: 600 }}>
                  <motion.div
                    className="pointer-events-none absolute inset-0 z-0 rounded-2xl"
                    variants={glowVariants}
                    transition={sharedTransition}
                    style={{ background: item.gradient ?? defaultItems[0].gradient }}
                  />

                  <Component
                    {...(item.href ? { href: item.href } : { type: 'button', onClick: item.onClick })}
                    className="absolute inset-0 z-20"
                    aria-label={item.label}
                  />

                  <motion.div
                    className={cn(
                      'relative z-10 flex items-center justify-center gap-2 rounded-2xl px-3 py-2 text-text-secondary transition-colors',
                      embedded ? 'min-h-12 flex-col' : 'min-h-11 flex-col md:flex-row',
                    )}
                    variants={frontVariants}
                    transition={sharedTransition}
                    style={{ transformStyle: 'preserve-3d', transformOrigin: 'center bottom' }}
                  >
                    <span className={cn('transition-colors duration-150', item.iconClassName)}>{item.icon}</span>
                    {showLabels ? <span className="text-[11px] font-medium text-pretty md:text-xs">{item.label}</span> : null}
                  </motion.div>

                  <motion.div
                    className={cn(
                      'absolute inset-0 z-10 flex items-center justify-center gap-2 rounded-2xl px-3 py-2 text-text-secondary transition-colors',
                      embedded ? 'min-h-12 flex-col' : 'min-h-11 flex-col md:flex-row',
                    )}
                    variants={backVariants}
                    transition={sharedTransition}
                    style={{ transformStyle: 'preserve-3d', transformOrigin: 'center top' }}
                  >
                    <span className={cn('transition-colors duration-150', item.iconClassName)}>{item.icon}</span>
                    {showLabels ? <span className="text-[11px] font-medium text-pretty md:text-xs">{item.label}</span> : null}
                  </motion.div>
                </motion.div>
              </motion.li>
            );
          })}
        </ul>
      </motion.nav>
    </div>
  );
}
