"use client";

// Generated by Copilot
import React, { useMemo, useState } from 'react';
import {
  Analytics,
  Calendar,
  ChevronDown,
  Dashboard,
  DocumentAdd,
  Folder,
  Search,
  Settings,
  Task,
  UserMultiple,
} from '@carbon/icons-react';
import { Check, PanelLeftClose, PanelLeftOpen, StretchHorizontal } from 'lucide-react';

import { cn } from '@/lib/utils';
import { Menu, MenuItem, MenuPopup, MenuTrigger } from '@/components/ui/menu';

export type SidebarIconComponent = React.ComponentType<{ size?: number; className?: string }>;

export interface SidebarComponentSection {
  id: string;
  title?: string;
  content: React.ReactNode;
}

export interface SidebarComponentPanel {
  id: string;
  title: string;
  subtitle?: string;
  icon: SidebarIconComponent;
  accent?: string;
  searchSlot?: React.ReactNode;
  sections: SidebarComponentSection[];
}

interface SidebarComponentProps {
  panels: SidebarComponentPanel[];
  initialPanelId?: string;
  className?: string;
  footerSlot?: React.ReactNode;
}

type SidebarWidthPreset = 'compact' | 'default' | 'wide';

const DETAIL_PANEL_WIDTHS: Record<SidebarWidthPreset, string> = {
  compact: '15.5rem',
  default: '18.5rem',
  wide: '21rem',
};

function SidebarRailButton({
  icon: Icon,
  active,
  onClick,
  label,
}: {
  icon: SidebarIconComponent;
  active: boolean;
  onClick: () => void;
  label: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-label={label}
      title={label}
      className={cn(
        'flex size-9 items-center justify-center rounded-md border transition-colors',
        active
          ? 'border-border-visible bg-card text-text-display shadow-sm'
          : 'border-transparent bg-transparent text-text-secondary hover:border-border hover:bg-surface-raised hover:text-text-primary',
      )}
    >
      <Icon size={18} className="shrink-0" />
    </button>
  );
}

export function SidebarComponent({
  panels,
  initialPanelId,
  className,
  footerSlot,
}: SidebarComponentProps) {
  const [activePanelId, setActivePanelId] = useState(initialPanelId ?? panels[0]?.id ?? '');
  const [collapsed, setCollapsed] = useState(false);
  const [widthPreset, setWidthPreset] = useState<SidebarWidthPreset>('default');

  const activePanel = useMemo(
    () => panels.find((panel) => panel.id === activePanelId) ?? panels[0],
    [activePanelId, panels],
  );
  const detailPanelWidth = DETAIL_PANEL_WIDTHS[widthPreset];

  if (!activePanel) {
    return null;
  }

  return (
    <div className={cn('flex h-full min-h-0 overflow-hidden rounded-md border border-border bg-surface shadow-sm', className)}>
      <aside className="flex w-12 shrink-0 flex-col items-center gap-2 border-r border-border bg-surface px-1.5 py-2">
        <div className="flex size-9 items-center justify-center rounded-md border border-border bg-card text-text-display shadow-sm">
          <Dashboard size={18} />
        </div>

        <div className="flex flex-1 flex-col items-center gap-1.5">
          {panels.map((panel) => (
            <SidebarRailButton
              key={panel.id}
              icon={panel.icon}
              active={panel.id === activePanel.id}
              onClick={() => setActivePanelId(panel.id)}
              label={panel.title}
            />
          ))}
        </div>

        <Menu>
          <MenuTrigger
            className="flex size-9 items-center justify-center rounded-md border border-border bg-card text-text-secondary transition-colors hover:text-text-primary"
            aria-label="Sidebar width"
            title="Sidebar width"
          >
            <StretchHorizontal className="size-4" />
          </MenuTrigger>
          <MenuPopup side="inline-end" align="start" sideOffset={10} className="min-w-44">
            <MenuItem onClick={() => setWidthPreset('compact')}>
              <span className="flex flex-1 items-center justify-between gap-3">
                Compact
                {widthPreset === 'compact' ? <Check className="size-4" /> : null}
              </span>
            </MenuItem>
            <MenuItem onClick={() => setWidthPreset('default')}>
              <span className="flex flex-1 items-center justify-between gap-3">
                Default
                {widthPreset === 'default' ? <Check className="size-4" /> : null}
              </span>
            </MenuItem>
            <MenuItem onClick={() => setWidthPreset('wide')}>
              <span className="flex flex-1 items-center justify-between gap-3">
                Wide
                {widthPreset === 'wide' ? <Check className="size-4" /> : null}
              </span>
            </MenuItem>
          </MenuPopup>
        </Menu>

        <button
          type="button"
          onClick={() => setCollapsed((value) => !value)}
          aria-label={collapsed ? 'Expand sidebar detail panel' : 'Collapse sidebar detail panel'}
          className="flex size-9 items-center justify-center rounded-md border border-border bg-card text-text-secondary transition-colors hover:text-text-primary"
        >
          {collapsed ? <PanelLeftOpen className="size-4" /> : <PanelLeftClose className="size-4" />}
        </button>
      </aside>

      <section
        className={cn('min-h-0 flex-none overflow-hidden transition-opacity duration-200', collapsed ? 'p-0 opacity-0' : 'opacity-100')}
        style={{ width: collapsed ? 0 : detailPanelWidth }}
      >
        {!collapsed && (
          <div className="flex h-full min-h-0 flex-col bg-surface-raised/60">
            <div className="border-b border-border px-3 py-3">
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <div className="flex items-center gap-2.5">
                    <div className="flex size-8 shrink-0 items-center justify-center rounded-md border border-border bg-card text-text-display shadow-sm">
                      <activePanel.icon size={18} />
                    </div>
                    <div className="min-w-0">
                      <h2 className="truncate text-sm font-semibold text-text-display">{activePanel.title}</h2>
                      {activePanel.subtitle ? (
                        <p className="truncate text-xs text-text-secondary">{activePanel.subtitle}</p>
                      ) : null}
                    </div>
                  </div>
                </div>

                {activePanel.searchSlot ? <div className="shrink-0">{activePanel.searchSlot}</div> : null}
              </div>
            </div>

            <div className="flex min-h-0 flex-1 flex-col gap-3 overflow-y-auto px-3 py-3">
              {activePanel.sections.map((section) => (
                <section key={section.id} className="rounded-md border border-border bg-surface p-3">
                  {section.title ? (
                    <div className="mb-3 flex items-center justify-between gap-2 border-b border-border pb-2">
                      <h3 className="text-xs font-semibold uppercase text-text-primary">{section.title}</h3>
                    </div>
                  ) : null}
                  {section.content}
                </section>
              ))}
            </div>

            {footerSlot ? <div className="border-t border-border px-4 py-3">{footerSlot}</div> : null}
          </div>
        )}
      </section>
    </div>
  );
}

export const sidebarComponentIconSet = {
  dashboard: Dashboard,
  tasks: Task,
  folders: Folder,
  calendar: Calendar,
  people: UserMultiple,
  analytics: Analytics,
  document: DocumentAdd,
  settings: Settings,
  search: Search,
  chevronDown: ChevronDown,
};

export default SidebarComponent;
