-- Generated by Copilot
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS laboratories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT UNIQUE,
  country_code TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  laboratory_id TEXT REFERENCES laboratories(id) ON DELETE SET NULL,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('admin', 'designer', 'technician', 'reviewer')),
  email TEXT,
  locale TEXT NOT NULL DEFAULT 'es-MX',
  timezone TEXT NOT NULL DEFAULT 'America/Mexico_City',
  numbering_system TEXT NOT NULL DEFAULT 'FDI' CHECK(numbering_system IN ('FDI', 'UNIVERSAL')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS workstations (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  hostname TEXT NOT NULL,
  os_family TEXT NOT NULL,
  app_version TEXT NOT NULL,
  last_seen_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS cases (
  id TEXT PRIMARY KEY,
  laboratory_id TEXT REFERENCES laboratories(id) ON DELETE SET NULL,
  owner_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  case_number TEXT NOT NULL UNIQUE,
  patient_alias TEXT NOT NULL,
  patient_external_id TEXT,
  title TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('draft', 'in-progress', 'ready', 'archived')),
  shade TEXT,
  occlusion_scan_type TEXT,
  active_jaw TEXT NOT NULL DEFAULT 'upper' CHECK(active_jaw IN ('upper', 'lower')),
  notes TEXT,
  interop_xml_path TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS case_assets (
  id TEXT PRIMARY KEY,
  case_id TEXT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  asset_type TEXT NOT NULL CHECK(asset_type IN ('dicom', 'stl', 'obj', 'ply', 'gltf', 'xml', 'preview', 'report')),
  storage_path TEXT NOT NULL,
  filename TEXT NOT NULL,
  mime_type TEXT,
  checksum_sha256 TEXT,
  file_size_bytes INTEGER,
  metadata_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS odontogram_entries (
  id TEXT PRIMARY KEY,
  case_id TEXT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  tooth_code TEXT NOT NULL,
  jaw TEXT NOT NULL CHECK(jaw IN ('upper', 'lower')),
  is_selected INTEGER NOT NULL DEFAULT 0,
  is_antagonist INTEGER NOT NULL DEFAULT 0,
  condition_code TEXT NOT NULL DEFAULT 'anatomic-coping',
  notes TEXT,
  updated_at TEXT NOT NULL,
  UNIQUE(case_id, tooth_code)
);

CREATE TABLE IF NOT EXISTS case_modules (
  id TEXT PRIMARY KEY,
  case_id TEXT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  module_code TEXT NOT NULL,
  window_label TEXT,
  sync_enabled INTEGER NOT NULL DEFAULT 1,
  state_json TEXT,
  updated_at TEXT NOT NULL,
  UNIQUE(case_id, module_code)
);

CREATE TABLE IF NOT EXISTS sync_events (
  id TEXT PRIMARY KEY,
  case_id TEXT REFERENCES cases(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  source_window TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
  id TEXT PRIMARY KEY,
  actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  case_id TEXT REFERENCES cases(id) ON DELETE SET NULL,
  action_code TEXT NOT NULL,
  payload_json TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_cases_owner ON cases(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_case_assets_case ON case_assets(case_id);
CREATE INDEX IF NOT EXISTS idx_odontogram_case ON odontogram_entries(case_id);
CREATE INDEX IF NOT EXISTS idx_modules_case ON case_modules(case_id);
CREATE INDEX IF NOT EXISTS idx_sync_events_case ON sync_events(case_id);
