// Generated by Copilot
import { saveWindowState, StateFlags } from '@tauri-apps/plugin-window-state';

function isTauriRuntime() {
  return typeof window !== 'undefined' && ('__TAURI_INTERNALS__' in window || '__TAURI__' in window);
}

export async function copyTextToClipboard(value: string) {
  if (!isTauriRuntime()) {
    await navigator.clipboard.writeText(value);
    return true;
  }

  const { writeText } = await import('@tauri-apps/plugin-clipboard-manager');
  await writeText(value);
  return true;
}

export async function showDesktopNotification(title: string, body: string) {
  if (!isTauriRuntime()) {
    return;
  }

  const notification = await import('@tauri-apps/plugin-notification');
  const permission = await notification.requestPermission();

  if (permission === 'granted') {
    await notification.sendNotification({ title, body });
  }
}

export async function persistCurrentWindowState() {
  if (!isTauriRuntime()) {
    return;
  }

  await saveWindowState(StateFlags.ALL);
}

export async function revealPathInSystem(path: string) {
  if (!path) {
    return;
  }

  if (!isTauriRuntime()) {
    return;
  }

  const { revealItemInDir } = await import('@tauri-apps/plugin-opener');
  await revealItemInDir(path);
}

export async function openPathInSystem(path: string) {
  if (!path) {
    return;
  }

  if (!isTauriRuntime()) {
    return;
  }

  const { openPath } = await import('@tauri-apps/plugin-opener');
  await openPath(path);
}

export { isTauriRuntime };
