// Generated by Copilot
import { buildWorkspaceUrl, type WorkspaceLaunchContext } from '@/lib/workspace-routing';

function slugify(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

export async function openWorkspaceWindow(context: WorkspaceLaunchContext) {
  const url = buildWorkspaceUrl(context);

  if (typeof window === 'undefined') {
    return null;
  }

  const label = slugify(`${context.workspace}-${context.module ?? 'workspace'}-${context.caseId ?? crypto.randomUUID()}`);
  const title = context.title ?? (context.workspace === 'tlanticad' ? 'TlantiCAD Studio · CAD' : 'TlantiCAD Studio · DB');

  if ('__TAURI_INTERNALS__' in window || '__TAURI__' in window) {
    const { invoke } = await import('@tauri-apps/api/core');
    await invoke('open_workspace_window', {
      request: {
        label,
        workspace: context.workspace,
        caseId: context.caseId,
        module: context.module,
        title,
      },
    });

    return { label };
  }

  window.open(url, '_blank', 'noopener,noreferrer');
  return null;
}
