// Generated by Copilot
// Módulo de base de datos SQLite para Tlanti4Dental
// Proporciona acceso a la base de datos desde comandos Rust

use sqlx::{sqlite::SqlitePoolOptions, Pool, Sqlite};
use std::sync::Arc;
use tokio::sync::RwLock;
use once_cell::sync::Lazy;

pub mod migrations;

pub type DbPool = Pool<Sqlite>;

// Pool global de conexiones
static DB_POOL: Lazy<Arc<RwLock<Option<DbPool>>>> = Lazy::new(|| Arc::new(RwLock::new(None)));

/// Inicializa el pool de conexiones a SQLite
pub async fn init_db(app_dir: &std::path::Path) -> Result<(), String> {
    let db_path = app_dir.join("tlanti4dental.db");
    let db_url = format!("sqlite:{}?mode=rwc", db_path.display());
    
    log::info!("Conectando a base de datos: {}", db_path.display());
    
    let pool = SqlitePoolOptions::new()
        .max_connections(5)
        .connect(&db_url)
        .await
        .map_err(|e| format!("Error conectando a SQLite: {}", e))?;
    
    // Generated by Copilot: esquema legado deshabilitado; usar migraciones
    let use_legacy_schema = false;

    if use_legacy_schema {
    // Ejecutar migraciones básicas si la tabla no existe
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS patients (
            id TEXT PRIMARY KEY NOT NULL,
            expedient_number TEXT NOT NULL,
            first_name TEXT NOT NULL,
            last_name TEXT NOT NULL,
            middle_name TEXT,
            second_last_name TEXT,
            date_of_birth TEXT NOT NULL,
            gender TEXT NOT NULL,
            phone TEXT,
            mobile TEXT,
            email TEXT,
            address TEXT,
            city TEXT,
            state TEXT,
            zip_code TEXT,
            country TEXT DEFAULT 'México',
            blood_type TEXT,
            photo TEXT,
            occupation TEXT,
            marital_status TEXT,
            referred_by TEXT,
            emergency_contact_name TEXT,
            emergency_contact_phone TEXT,
            emergency_contact_relationship TEXT,
            insurance_provider TEXT,
            insurance_policy_number TEXT,
            balance REAL DEFAULT 0,
            status TEXT DEFAULT 'active',
            notes TEXT,
            tags TEXT,
            allergies TEXT,
            medications TEXT,
            medical_conditions TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla patients: {}", e))?;
    
    // Crear tabla de citas
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS appointments (
            id TEXT PRIMARY KEY NOT NULL,
            patient_id TEXT NOT NULL,
            doctor_id TEXT,
            treatment_id TEXT,
            title TEXT NOT NULL,
            description TEXT,
            date TEXT NOT NULL,
            start_time TEXT NOT NULL,
            end_time TEXT NOT NULL,
            duration INTEGER NOT NULL,
            status TEXT DEFAULT 'scheduled',
            type TEXT DEFAULT 'consultation',
            room TEXT,
            color TEXT,
            reminder_sent INTEGER DEFAULT 0,
            confirmed_at TEXT,
            arrived_at TEXT,
            started_at TEXT,
            completed_at TEXT,
            cancelled_at TEXT,
            cancellation_reason TEXT,
            notes TEXT,
            created_by TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (patient_id) REFERENCES patients(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla appointments: {}", e))?;

    // Crear tabla de pagos
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS payments (
            id TEXT PRIMARY KEY NOT NULL,
            patient_id TEXT NOT NULL,
            treatment_plan_id TEXT,
            invoice_id TEXT,
            amount REAL NOT NULL,
            method TEXT NOT NULL,
            reference_number TEXT,
            notes TEXT,
            received_by TEXT NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY (patient_id) REFERENCES patients(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla payments: {}", e))?;

    // Crear tabla de notas clínicas
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS clinical_notes (
            id TEXT PRIMARY KEY NOT NULL,
            patient_id TEXT NOT NULL,
            treatment_id TEXT,
            appointment_id TEXT,
            note_type TEXT DEFAULT 'general',
            title TEXT NOT NULL,
            content TEXT NOT NULL,
            content_format TEXT DEFAULT 'text',
            is_private INTEGER DEFAULT 0,
            created_by TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (patient_id) REFERENCES patients(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla clinical_notes: {}", e))?;

    // Crear tabla de odontogramas
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS odontograms (
            id TEXT PRIMARY KEY NOT NULL,
            patient_id TEXT NOT NULL,
            type TEXT DEFAULT 'adult',
            is_current INTEGER DEFAULT 1,
            teeth TEXT NOT NULL,
            observations TEXT,
            created_by TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (patient_id) REFERENCES patients(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla odontograms: {}", e))?;

    // Crear tabla de configuración
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS app_config (
            key TEXT PRIMARY KEY NOT NULL,
            value TEXT NOT NULL,
            type TEXT DEFAULT 'string',
            updated_at TEXT
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla app_config: {}", e))?;

    // Crear tabla de tratamientos
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS treatments (
            id TEXT PRIMARY KEY NOT NULL,
            patient_id TEXT NOT NULL,
            doctor_id TEXT,
            tooth_id INTEGER,
            plan_id TEXT,
            treatment_type TEXT NOT NULL,
            description TEXT,
            status TEXT DEFAULT 'planned',
            priority TEXT DEFAULT 'medium',
            start_date TEXT,
            completion_date TEXT,
            estimated_duration INTEGER,
            cost REAL NOT NULL DEFAULT 0,
            discount REAL DEFAULT 0,
            paid REAL DEFAULT 0,
            notes TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (patient_id) REFERENCES patients(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla treatments: {}", e))?;

    // Crear tabla de catálogo de tratamientos
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS treatment_catalog (
            id TEXT PRIMARY KEY NOT NULL,
            code TEXT,
            name TEXT NOT NULL,
            description TEXT,
            category TEXT,
            default_price REAL NOT NULL DEFAULT 0,
            estimated_duration INTEGER,
            is_active INTEGER DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla treatment_catalog: {}", e))?;

    // Crear tabla de planes de tratamiento
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS treatment_plans (
            id TEXT PRIMARY KEY NOT NULL,
            patient_id TEXT NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            status TEXT DEFAULT 'active',
            total_cost REAL DEFAULT 0,
            total_paid REAL DEFAULT 0,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (patient_id) REFERENCES patients(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla treatment_plans: {}", e))?;

    // Crear tabla de inventario
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS inventory (
            id TEXT PRIMARY KEY NOT NULL,
            sku TEXT,
            name TEXT NOT NULL,
            description TEXT,
            category TEXT,
            unit TEXT DEFAULT 'pza',
            current_stock INTEGER DEFAULT 0,
            min_stock INTEGER DEFAULT 0,
            max_stock INTEGER,
            cost_price REAL NOT NULL DEFAULT 0,
            sale_price REAL NOT NULL DEFAULT 0,
            supplier TEXT,
            location TEXT,
            expiration_date TEXT,
            is_active INTEGER DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla inventory: {}", e))?;

    // Crear tabla de movimientos de inventario
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS stock_movements (
            id TEXT PRIMARY KEY NOT NULL,
            item_id TEXT NOT NULL,
            movement_type TEXT NOT NULL,
            quantity INTEGER NOT NULL,
            previous_stock INTEGER NOT NULL,
            new_stock INTEGER NOT NULL,
            reason TEXT,
            reference TEXT,
            created_by TEXT,
            created_at TEXT NOT NULL,
            FOREIGN KEY (item_id) REFERENCES inventory(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla stock_movements: {}", e))?;

    // Crear tabla de usuarios
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS users (
            id TEXT PRIMARY KEY NOT NULL,
            username TEXT UNIQUE NOT NULL,
            email TEXT UNIQUE,
            password_hash TEXT NOT NULL,
            first_name TEXT NOT NULL,
            last_name TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'staff',
            is_active INTEGER DEFAULT 1,
            last_login TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla users: {}", e))?;

    // Crear tabla de sesiones
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS sessions (
            id TEXT PRIMARY KEY NOT NULL,
            user_id TEXT NOT NULL,
            token TEXT UNIQUE NOT NULL,
            expires_at TEXT NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla sessions: {}", e))?;

    // Crear tabla de empleados
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS employees (
            id TEXT PRIMARY KEY NOT NULL,
            user_id TEXT,
            first_name TEXT NOT NULL,
            last_name TEXT NOT NULL,
            email TEXT,
            phone TEXT,
            position TEXT NOT NULL,
            department TEXT,
            specialty TEXT,
            license_number TEXT,
            hire_date TEXT,
            salary REAL,
            commission_rate REAL,
            schedule TEXT,
            is_active INTEGER DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla employees: {}", e))?;

    // Crear tabla de control de tiempo
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS time_entries (
            id TEXT PRIMARY KEY NOT NULL,
            employee_id TEXT NOT NULL,
            date TEXT NOT NULL,
            clock_in TEXT NOT NULL,
            clock_out TEXT,
            break_minutes INTEGER DEFAULT 0,
            total_hours REAL DEFAULT 0,
            notes TEXT,
            created_at TEXT NOT NULL,
            FOREIGN KEY (employee_id) REFERENCES employees(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla time_entries: {}", e))?;

    // Crear tabla de solicitudes de permisos
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS leave_requests (
            id TEXT PRIMARY KEY NOT NULL,
            employee_id TEXT NOT NULL,
            leave_type TEXT NOT NULL,
            start_date TEXT NOT NULL,
            end_date TEXT NOT NULL,
            status TEXT DEFAULT 'pending',
            notes TEXT,
            approved_by TEXT,
            created_at TEXT NOT NULL,
            FOREIGN KEY (employee_id) REFERENCES employees(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla leave_requests: {}", e))?;

    // Crear tabla de categorías POS
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS pos_categories (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            color TEXT,
            icon TEXT,
            sort_order INTEGER DEFAULT 0,
            is_active INTEGER DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla pos_categories: {}", e))?;

    // Crear tabla de items POS
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS pos_items (
            id TEXT PRIMARY KEY NOT NULL,
            code TEXT UNIQUE NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            category_id TEXT,
            price REAL NOT NULL DEFAULT 0,
            cost REAL,
            tax_rate REAL DEFAULT 0,
            is_service INTEGER DEFAULT 0,
            inventory_item_id TEXT,
            treatment_id TEXT,
            image TEXT,
            is_active INTEGER DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (category_id) REFERENCES pos_categories(id),
            FOREIGN KEY (inventory_item_id) REFERENCES inventory(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla pos_items: {}", e))?;

    // Crear tabla de ventas
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS sales (
            id TEXT PRIMARY KEY NOT NULL,
            sale_number TEXT UNIQUE NOT NULL,
            patient_id TEXT,
            subtotal REAL DEFAULT 0,
            tax_total REAL DEFAULT 0,
            discount_total REAL DEFAULT 0,
            total REAL DEFAULT 0,
            amount_paid REAL DEFAULT 0,
            change_given REAL DEFAULT 0,
            status TEXT DEFAULT 'draft',
            sold_by TEXT NOT NULL,
            session_id TEXT,
            notes TEXT,
            created_at TEXT NOT NULL,
            completed_at TEXT,
            FOREIGN KEY (patient_id) REFERENCES patients(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla sales: {}", e))?;

    // Crear tabla de items de venta
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS sale_items (
            id TEXT PRIMARY KEY NOT NULL,
            sale_id TEXT NOT NULL,
            pos_item_id TEXT,
            code TEXT NOT NULL,
            name TEXT NOT NULL,
            quantity REAL NOT NULL DEFAULT 1,
            unit_price REAL NOT NULL,
            tax_rate REAL DEFAULT 0,
            tax_amount REAL DEFAULT 0,
            discount_percent REAL DEFAULT 0,
            discount_amount REAL DEFAULT 0,
            subtotal REAL NOT NULL,
            total REAL NOT NULL,
            notes TEXT,
            FOREIGN KEY (sale_id) REFERENCES sales(id),
            FOREIGN KEY (pos_item_id) REFERENCES pos_items(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla sale_items: {}", e))?;

    // Crear tabla de pagos de venta
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS sale_payments (
            id TEXT PRIMARY KEY NOT NULL,
            sale_id TEXT NOT NULL,
            payment_method TEXT NOT NULL,
            amount REAL NOT NULL,
            reference TEXT,
            received_at TEXT NOT NULL,
            FOREIGN KEY (sale_id) REFERENCES sales(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla sale_payments: {}", e))?;

    // Crear tabla de proveedores
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS suppliers (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            contact_name TEXT,
            email TEXT,
            phone TEXT,
            address TEXT,
            city TEXT,
            state TEXT,
            country TEXT,
            postal_code TEXT,
            tax_id TEXT,
            website TEXT,
            category TEXT,
            payment_terms TEXT,
            credit_limit REAL,
            current_balance REAL DEFAULT 0,
            rating INTEGER,
            notes TEXT,
            is_active INTEGER DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla suppliers: {}", e))?;

    // Crear tabla de órdenes de compra
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS purchase_orders (
            id TEXT PRIMARY KEY NOT NULL,
            order_number TEXT UNIQUE NOT NULL,
            supplier_id TEXT NOT NULL,
            order_date TEXT NOT NULL,
            expected_delivery TEXT,
            actual_delivery TEXT,
            subtotal REAL DEFAULT 0,
            tax REAL DEFAULT 0,
            shipping REAL DEFAULT 0,
            discount REAL DEFAULT 0,
            total REAL DEFAULT 0,
            status TEXT DEFAULT 'draft',
            payment_status TEXT DEFAULT 'unpaid',
            notes TEXT,
            created_by TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla purchase_orders: {}", e))?;

    // Crear tabla de items de orden de compra
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS purchase_order_items (
            id TEXT PRIMARY KEY NOT NULL,
            purchase_order_id TEXT NOT NULL,
            inventory_item_id TEXT,
            description TEXT NOT NULL,
            quantity REAL NOT NULL,
            unit TEXT DEFAULT 'pcs',
            unit_price REAL NOT NULL,
            tax_rate REAL DEFAULT 0,
            discount REAL DEFAULT 0,
            total REAL NOT NULL,
            received_quantity REAL DEFAULT 0,
            FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla purchase_order_items: {}", e))?;

    // Crear tabla de pagos a proveedores
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS supplier_payments (
            id TEXT PRIMARY KEY NOT NULL,
            supplier_id TEXT NOT NULL,
            purchase_order_id TEXT,
            amount REAL NOT NULL,
            payment_method TEXT NOT NULL,
            reference TEXT,
            payment_date TEXT NOT NULL,
            notes TEXT,
            created_at TEXT NOT NULL,
            FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla supplier_payments: {}", e))?;

    // Crear tabla de cajas registradoras
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS cash_registers (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            location TEXT,
            is_active INTEGER DEFAULT 1,
            current_session_id TEXT,
            created_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla cash_registers: {}", e))?;

    // Crear tabla de sesiones de caja
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS cash_sessions (
            id TEXT PRIMARY KEY NOT NULL,
            register_id TEXT NOT NULL,
            opened_by TEXT NOT NULL,
            opened_at TEXT NOT NULL,
            closed_by TEXT,
            closed_at TEXT,
            opening_balance REAL NOT NULL,
            closing_balance REAL,
            expected_balance REAL,
            difference REAL,
            status TEXT DEFAULT 'open',
            notes TEXT,
            FOREIGN KEY (register_id) REFERENCES cash_registers(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla cash_sessions: {}", e))?;

    // Crear tabla de movimientos de caja
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS cash_movements (
            id TEXT PRIMARY KEY NOT NULL,
            session_id TEXT NOT NULL,
            movement_type TEXT NOT NULL,
            reference_type TEXT,
            reference_id TEXT,
            amount REAL NOT NULL,
            payment_method TEXT NOT NULL,
            description TEXT NOT NULL,
            is_voided INTEGER DEFAULT 0,
            created_by TEXT NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY (session_id) REFERENCES cash_sessions(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla cash_movements: {}", e))?;

    // Crear tabla de notificaciones
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS notifications (
            id TEXT PRIMARY KEY NOT NULL,
            notification_type TEXT NOT NULL,
            channel TEXT NOT NULL,
            recipient_id TEXT NOT NULL,
            recipient_type TEXT NOT NULL,
            title TEXT NOT NULL,
            message TEXT NOT NULL,
            data TEXT,
            priority TEXT DEFAULT 'normal',
            status TEXT DEFAULT 'pending',
            scheduled_at TEXT,
            sent_at TEXT,
            read_at TEXT,
            created_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla notifications: {}", e))?;

    // Crear tabla de plantillas de notificación
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS notification_templates (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            notification_type TEXT NOT NULL,
            channel TEXT NOT NULL,
            subject_template TEXT NOT NULL,
            body_template TEXT NOT NULL,
            variables TEXT,
            is_active INTEGER DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla notification_templates: {}", e))?;

    // Crear tabla de campañas de marketing
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS crm_campaigns (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            campaign_type TEXT NOT NULL,
            status TEXT DEFAULT 'draft',
            target_audience TEXT,
            content TEXT,
            schedule TEXT,
            stats TEXT,
            created_by TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla crm_campaigns: {}", e))?;

    // Crear tabla de segmentos de pacientes
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS patient_segments (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            filters TEXT,
            patient_count INTEGER DEFAULT 0,
            is_dynamic INTEGER DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla patient_segments: {}", e))?;

    // Crear tabla de interacciones con pacientes
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS patient_interactions (
            id TEXT PRIMARY KEY NOT NULL,
            patient_id TEXT NOT NULL,
            interaction_type TEXT NOT NULL,
            direction TEXT NOT NULL,
            subject TEXT,
            notes TEXT,
            outcome TEXT,
            campaign_id TEXT,
            created_by TEXT NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY (patient_id) REFERENCES patients(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla patient_interactions: {}", e))?;

    // Crear tabla de programa de referidos
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS referral_programs (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            referrer_reward TEXT,
            referee_reward TEXT,
            is_active INTEGER DEFAULT 1,
            total_referrals INTEGER DEFAULT 0,
            successful_referrals INTEGER DEFAULT 0,
            created_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla referral_programs: {}", e))?;

    // Crear tabla de referidos
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS referrals (
            id TEXT PRIMARY KEY NOT NULL,
            program_id TEXT NOT NULL,
            referrer_patient_id TEXT NOT NULL,
            referee_name TEXT NOT NULL,
            referee_phone TEXT NOT NULL,
            referee_email TEXT,
            referee_patient_id TEXT,
            status TEXT DEFAULT 'pending',
            referrer_reward_applied INTEGER DEFAULT 0,
            referee_reward_applied INTEGER DEFAULT 0,
            created_at TEXT NOT NULL,
            converted_at TEXT,
            FOREIGN KEY (program_id) REFERENCES referral_programs(id),
            FOREIGN KEY (referrer_patient_id) REFERENCES patients(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla referrals: {}", e))?;

    // Crear tabla de dashboards
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS dashboards (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            owner_id TEXT NOT NULL,
            is_default INTEGER DEFAULT 0,
            is_shared INTEGER DEFAULT 0,
            layout TEXT,
            widgets TEXT,
            filters TEXT,
            refresh_interval_seconds INTEGER,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla dashboards: {}", e))?;

    // Crear tabla de KPIs
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS kpis (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            category TEXT NOT NULL,
            calculation_type TEXT NOT NULL,
            data_source TEXT NOT NULL,
            formula TEXT,
            unit TEXT,
            target_value REAL,
            warning_threshold REAL,
            critical_threshold REAL,
            trend_direction TEXT DEFAULT 'up_is_good',
            is_active INTEGER DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla kpis: {}", e))?;

    // Crear tabla de plantillas de documentos
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS document_templates (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            category TEXT NOT NULL,
            template_type TEXT NOT NULL,
            content TEXT NOT NULL,
            variables TEXT,
            header TEXT,
            footer TEXT,
            is_default INTEGER DEFAULT 0,
            is_active INTEGER DEFAULT 1,
            version INTEGER DEFAULT 1,
            created_by TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla document_templates: {}", e))?;

    // Crear tabla de documentos generados
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS generated_documents (
            id TEXT PRIMARY KEY NOT NULL,
            template_id TEXT NOT NULL,
            template_name TEXT NOT NULL,
            patient_id TEXT,
            patient_name TEXT,
            appointment_id TEXT,
            treatment_id TEXT,
            content TEXT NOT NULL,
            variables_used TEXT,
            signatures TEXT,
            status TEXT DEFAULT 'draft',
            generated_by TEXT NOT NULL,
            generated_at TEXT NOT NULL,
            signed_at TEXT,
            file_path TEXT,
            FOREIGN KEY (template_id) REFERENCES document_templates(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla generated_documents: {}", e))?;

    // Crear tabla de prescripciones
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS prescriptions (
            id TEXT PRIMARY KEY NOT NULL,
            patient_id TEXT NOT NULL,
            patient_name TEXT NOT NULL,
            doctor_id TEXT NOT NULL,
            doctor_name TEXT NOT NULL,
            doctor_license TEXT NOT NULL,
            date TEXT NOT NULL,
            diagnosis TEXT,
            medications TEXT NOT NULL,
            instructions TEXT,
            validity_days INTEGER DEFAULT 30,
            is_controlled INTEGER DEFAULT 0,
            created_at TEXT NOT NULL,
            FOREIGN KEY (patient_id) REFERENCES patients(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla prescriptions: {}", e))?;

    // Crear tabla de cotizaciones
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS treatment_quotes (
            id TEXT PRIMARY KEY NOT NULL,
            quote_number TEXT UNIQUE NOT NULL,
            patient_id TEXT NOT NULL,
            patient_name TEXT NOT NULL,
            treatments TEXT NOT NULL,
            subtotal REAL DEFAULT 0,
            discount REAL DEFAULT 0,
            tax REAL DEFAULT 0,
            total REAL DEFAULT 0,
            valid_until TEXT NOT NULL,
            notes TEXT,
            status TEXT DEFAULT 'draft',
            created_by TEXT NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY (patient_id) REFERENCES patients(id)
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla treatment_quotes: {}", e))?;

    // Crear tabla historial de reportes
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS report_history (
            id TEXT PRIMARY KEY NOT NULL,
            report_type TEXT NOT NULL,
            title TEXT NOT NULL,
            file_path TEXT,
            data TEXT,
            generated_by TEXT,
            generated_at TEXT NOT NULL
        )
        "#
    )
    .execute(&pool)
    .await
    .map_err(|e| format!("Error creando tabla report_history: {}", e))?;

    // ========= NUEVAS TABLAS - Módulos Avanzados =========

    // Multi-clínica: Sucursales
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS clinic_branches (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            code TEXT UNIQUE NOT NULL,
            address TEXT,
            phone TEXT,
            email TEXT,
            manager_id TEXT,
            is_active INTEGER DEFAULT 1,
            settings TEXT,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla clinic_branches: {}", e))?;

    // Multi-clínica: Usuarios por sucursal
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS branch_users (
            id TEXT PRIMARY KEY NOT NULL,
            branch_id TEXT NOT NULL,
            user_id TEXT NOT NULL,
            role TEXT NOT NULL,
            is_primary INTEGER DEFAULT 0,
            created_at TEXT NOT NULL,
            UNIQUE(branch_id, user_id)
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla branch_users: {}", e))?;

    // Seguros: Proveedores
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS insurance_providers (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            code TEXT UNIQUE NOT NULL,
            contact_name TEXT,
            phone TEXT,
            email TEXT,
            address TEXT,
            coverage_details TEXT,
            is_active INTEGER DEFAULT 1,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla insurance_providers: {}", e))?;

    // Seguros: Seguros de pacientes
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS patient_insurances (
            id TEXT PRIMARY KEY NOT NULL,
            patient_id TEXT NOT NULL,
            provider_id TEXT NOT NULL,
            policy_number TEXT NOT NULL,
            group_number TEXT,
            subscriber_name TEXT,
            relationship TEXT DEFAULT 'self',
            effective_date TEXT NOT NULL,
            expiration_date TEXT,
            copay REAL DEFAULT 0,
            deductible REAL DEFAULT 0,
            max_annual REAL,
            is_primary INTEGER DEFAULT 1,
            is_active INTEGER DEFAULT 1,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla patient_insurances: {}", e))?;

    // Seguros: Reclamaciones
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS insurance_claims (
            id TEXT PRIMARY KEY NOT NULL,
            claim_number TEXT UNIQUE NOT NULL,
            patient_id TEXT NOT NULL,
            insurance_id TEXT NOT NULL,
            provider_id TEXT NOT NULL,
            service_date TEXT NOT NULL,
            submission_date TEXT,
            items TEXT NOT NULL,
            total_amount REAL NOT NULL,
            approved_amount REAL DEFAULT 0,
            patient_responsibility REAL DEFAULT 0,
            status TEXT DEFAULT 'draft',
            response_date TEXT,
            notes TEXT,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla insurance_claims: {}", e))?;

    // Laboratorios
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS laboratories (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            contact_name TEXT,
            phone TEXT,
            email TEXT,
            address TEXT,
            specialties TEXT,
            turnaround_days INTEGER DEFAULT 5,
            is_active INTEGER DEFAULT 1,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla laboratories: {}", e))?;

    // Órdenes de laboratorio
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS lab_orders (
            id TEXT PRIMARY KEY NOT NULL,
            order_number TEXT UNIQUE NOT NULL,
            patient_id TEXT NOT NULL,
            laboratory_id TEXT NOT NULL,
            items TEXT NOT NULL,
            shade TEXT,
            special_instructions TEXT,
            status TEXT DEFAULT 'pending',
            sent_date TEXT,
            expected_date TEXT,
            received_date TEXT,
            total_cost REAL DEFAULT 0,
            created_by TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla lab_orders: {}", e))?;

    // Conexiones de calendario
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS calendar_connections (
            id TEXT PRIMARY KEY NOT NULL,
            user_id TEXT NOT NULL,
            provider TEXT NOT NULL,
            account_email TEXT NOT NULL,
            access_token TEXT,
            refresh_token TEXT,
            token_expires TEXT,
            sync_enabled INTEGER DEFAULT 1,
            last_sync TEXT,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla calendar_connections: {}", e))?;

    // Portal de pacientes: usuarios
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS portal_users (
            id TEXT PRIMARY KEY NOT NULL,
            patient_id TEXT NOT NULL UNIQUE,
            email TEXT NOT NULL,
            password_hash TEXT NOT NULL,
            is_verified INTEGER DEFAULT 0,
            is_active INTEGER DEFAULT 1,
            last_login TEXT,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla portal_users: {}", e))?;

    // Portal: mensajes
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS portal_messages (
            id TEXT PRIMARY KEY NOT NULL,
            portal_user_id TEXT NOT NULL,
            direction TEXT NOT NULL,
            subject TEXT,
            content TEXT NOT NULL,
            is_read INTEGER DEFAULT 0,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla portal_messages: {}", e))?;

    // Portal: solicitudes de citas
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS booking_requests (
            id TEXT PRIMARY KEY NOT NULL,
            portal_user_id TEXT NOT NULL,
            patient_id TEXT NOT NULL,
            preferred_date TEXT NOT NULL,
            preferred_time TEXT,
            reason TEXT,
            status TEXT DEFAULT 'pending',
            appointment_id TEXT,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla booking_requests: {}", e))?;

    // Auditoría y compliance
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS audit_logs (
            id TEXT PRIMARY KEY NOT NULL,
            user_id TEXT,
            user_name TEXT,
            action TEXT NOT NULL,
            resource_type TEXT NOT NULL,
            resource_id TEXT,
            details TEXT,
            ip_address TEXT,
            user_agent TEXT,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla audit_logs: {}", e))?;

    // Logs de acceso
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS access_logs (
            id TEXT PRIMARY KEY NOT NULL,
            user_id TEXT NOT NULL,
            user_name TEXT,
            action TEXT NOT NULL,
            patient_id TEXT,
            patient_name TEXT,
            access_reason TEXT,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla access_logs: {}", e))?;

    // Teleodontología: sesiones de video
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS video_sessions (
            id TEXT PRIMARY KEY NOT NULL,
            patient_id TEXT NOT NULL,
            doctor_id TEXT NOT NULL,
            appointment_id TEXT,
            session_type TEXT NOT NULL,
            status TEXT DEFAULT 'scheduled',
            scheduled_at TEXT NOT NULL,
            started_at TEXT,
            ended_at TEXT,
            duration_minutes INTEGER,
            room_url TEXT,
            recording_url TEXT,
            notes TEXT,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla video_sessions: {}", e))?;

    // Flujos de trabajo
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS workflows (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            trigger_type TEXT NOT NULL,
            trigger_config TEXT,
            steps TEXT,
            is_active INTEGER DEFAULT 1,
            execution_count INTEGER DEFAULT 0,
            last_executed TEXT,
            created_by TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla workflows: {}", e))?;

    // Ejecuciones de flujos
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS workflow_executions (
            id TEXT PRIMARY KEY NOT NULL,
            workflow_id TEXT NOT NULL,
            status TEXT NOT NULL,
            trigger_data TEXT,
            results TEXT,
            started_at TEXT NOT NULL,
            completed_at TEXT,
            error TEXT
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla workflow_executions: {}", e))?;

    // Integraciones
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS integrations (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            integration_type TEXT NOT NULL,
            provider TEXT NOT NULL,
            config TEXT,
            status TEXT DEFAULT 'pending',
            last_sync TEXT,
            is_active INTEGER DEFAULT 1,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla integrations: {}", e))?;

    // Webhooks
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS webhooks (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            url TEXT NOT NULL,
            events TEXT,
            secret TEXT,
            is_active INTEGER DEFAULT 1,
            last_triggered TEXT,
            success_count INTEGER DEFAULT 0,
            failure_count INTEGER DEFAULT 0,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla webhooks: {}", e))?;

    // API Keys
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS api_keys (
            id TEXT PRIMARY KEY NOT NULL,
            name TEXT NOT NULL,
            key_hash TEXT NOT NULL,
            key_prefix TEXT NOT NULL,
            permissions TEXT,
            expires_at TEXT,
            last_used TEXT,
            is_active INTEGER DEFAULT 1,
            created_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla api_keys: {}", e))?;

    // Conversaciones IA
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS ai_conversations (
            id TEXT PRIMARY KEY NOT NULL,
            user_id TEXT NOT NULL,
            title TEXT,
            context TEXT,
            messages TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla ai_conversations: {}", e))?;

    // ============================================================================
    // MIGRACIÓN 002: Historia Médica y Consentimientos
    // ============================================================================
    
    // Signos vitales del paciente
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS patient_vitals (
            id TEXT PRIMARY KEY,
            patient_id TEXT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
            date TEXT NOT NULL,
            height_cm REAL,
            weight_kg REAL,
            bmi REAL,
            pulse INTEGER,
            blood_pressure_sys INTEGER,
            blood_pressure_dia INTEGER,
            glucose REAL,
            respiratory_rate INTEGER,
            temperature REAL,
            oxygen_saturation INTEGER,
            notes TEXT,
            recorded_by TEXT,
            created_at TEXT DEFAULT (datetime('now'))
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla patient_vitals: {}", e))?;

    // Antecedentes familiares hereditarios
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS patient_family_history (
            id TEXT PRIMARY KEY,
            patient_id TEXT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
            relative_type TEXT NOT NULL,
            relative_name TEXT,
            diabetes INTEGER,
            hypertension INTEGER,
            hypotension INTEGER,
            heart_disease INTEGER,
            cancer INTEGER,
            epilepsy INTEGER,
            hiv_aids INTEGER,
            kidney_disease INTEGER,
            hepatitis INTEGER,
            arthritis INTEGER,
            mental_illness INTEGER,
            asthma INTEGER,
            other_conditions TEXT,
            is_deceased INTEGER DEFAULT 0,
            cause_of_death TEXT,
            notes TEXT,
            created_at TEXT DEFAULT (datetime('now')),
            updated_at TEXT DEFAULT (datetime('now'))
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla patient_family_history: {}", e))?;

    // Patología personal
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS patient_pathology (
            id TEXT PRIMARY KEY,
            patient_id TEXT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
            sinusitis INTEGER DEFAULT 0,
            seizures INTEGER DEFAULT 0,
            tuberculosis INTEGER DEFAULT 0,
            emphysema INTEGER DEFAULT 0,
            asthma INTEGER DEFAULT 0,
            persistent_cough INTEGER DEFAULT 0,
            kidney_failure INTEGER DEFAULT 0,
            rheumatic_fever INTEGER DEFAULT 0,
            anemia INTEGER DEFAULT 0,
            gastritis INTEGER DEFAULT 0,
            blood_pressure_issues INTEGER DEFAULT 0,
            cancer INTEGER DEFAULT 0,
            leukemia INTEGER DEFAULT 0,
            hiv_aids INTEGER DEFAULT 0,
            heart_attack INTEGER DEFAULT 0,
            stroke INTEGER DEFAULT 0,
            diabetes_type TEXT,
            other_conditions TEXT,
            hospitalization_history TEXT,
            surgical_history TEXT,
            notes TEXT,
            last_updated TEXT,
            created_at TEXT DEFAULT (datetime('now')),
            updated_at TEXT DEFAULT (datetime('now'))
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla patient_pathology: {}", e))?;

    // Antecedentes toxicológicos
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS patient_toxicology (
            id TEXT PRIMARY KEY,
            patient_id TEXT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
            smokes INTEGER DEFAULT 0,
            cigarettes_per_day INTEGER,
            years_smoking INTEGER,
            drinks_alcohol INTEGER DEFAULT 0,
            alcohol_frequency TEXT,
            uses_drugs INTEGER DEFAULT 0,
            drug_types TEXT,
            has_allergies INTEGER DEFAULT 0,
            allergy_to_latex INTEGER DEFAULT 0,
            allergy_to_penicillin INTEGER DEFAULT 0,
            allergy_to_anesthesia INTEGER DEFAULT 0,
            allergy_to_nsaids INTEGER DEFAULT 0,
            other_allergies TEXT,
            allergy_reactions TEXT,
            takes_medication INTEGER DEFAULT 0,
            current_medications TEXT,
            has_pacemaker INTEGER DEFAULT 0,
            has_prosthesis INTEGER DEFAULT 0,
            prosthesis_details TEXT,
            is_pregnant INTEGER DEFAULT 0,
            pregnancy_weeks INTEGER,
            is_breastfeeding INTEGER DEFAULT 0,
            notes TEXT,
            created_at TEXT DEFAULT (datetime('now')),
            updated_at TEXT DEFAULT (datetime('now'))
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla patient_toxicology: {}", e))?;

    // Historial odontológico
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS patient_dental_history (
            id TEXT PRIMARY KEY,
            patient_id TEXT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
            oral_health_rating TEXT,
            last_dental_visit TEXT,
            brushing_frequency TEXT,
            uses_mouthwash INTEGER DEFAULT 0,
            uses_dental_floss INTEGER DEFAULT 0,
            bleeding_gums INTEGER DEFAULT 0,
            bad_breath INTEGER DEFAULT 0,
            tooth_sensitivity INTEGER DEFAULT 0,
            jaw_pain INTEGER DEFAULT 0,
            teeth_grinding INTEGER DEFAULT 0,
            lip_or_cheek_lesions INTEGER DEFAULT 0,
            previous_anesthesia INTEGER DEFAULT 0,
            anesthesia_complications INTEGER DEFAULT 0,
            anesthesia_complication_details TEXT,
            previous_extractions INTEGER DEFAULT 0,
            previous_orthodontics INTEGER DEFAULT 0,
            has_dentures INTEGER DEFAULT 0,
            denture_type TEXT,
            previous_dental_surgeries TEXT,
            dental_phobia INTEGER DEFAULT 0,
            notes TEXT,
            created_at TEXT DEFAULT (datetime('now')),
            updated_at TEXT DEFAULT (datetime('now'))
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla patient_dental_history: {}", e))?;

    // Plantillas de consentimientos
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS consent_templates (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            code TEXT UNIQUE,
            category TEXT DEFAULT 'general',
            description TEXT,
            content TEXT NOT NULL,
            tokens TEXT NOT NULL,
            is_required INTEGER DEFAULT 0,
            requires_witness INTEGER DEFAULT 0,
            version INTEGER DEFAULT 1,
            is_active INTEGER DEFAULT 1,
            created_by TEXT,
            created_at TEXT DEFAULT (datetime('now')),
            updated_at TEXT DEFAULT (datetime('now'))
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla consent_templates: {}", e))?;

    // Consentimientos de pacientes
    sqlx::query(
        r#"
        CREATE TABLE IF NOT EXISTS patient_consents (
            id TEXT PRIMARY KEY,
            patient_id TEXT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
            template_id TEXT NOT NULL REFERENCES consent_templates(id),
            template_name TEXT,
            treatment_id TEXT,
            appointment_id TEXT,
            final_content TEXT NOT NULL,
            patient_signature TEXT,
            patient_signed_at TEXT,
            patient_ip TEXT,
            patient_device TEXT,
            dentist_signature TEXT,
            dentist_signed_at TEXT,
            witness_name TEXT,
            witness_signature TEXT,
            witness_signed_at TEXT,
            latitude REAL,
            longitude REAL,
            status TEXT DEFAULT 'pending',
            expires_at TEXT,
            revoked_at TEXT,
            revoked_reason TEXT,
            pdf_path TEXT,
            pdf_generated_at TEXT,
            notes TEXT,
            created_by TEXT,
            created_at TEXT DEFAULT (datetime('now')),
            updated_at TEXT DEFAULT (datetime('now'))
        )
        "#
    ).execute(&pool).await.map_err(|e| format!("Error creando tabla patient_consents: {}", e))?;

    log::info!("Tablas de historia médica y consentimientos creadas");
    } else {
        apply_migrations(&pool).await?;
    }

    // Guardar pool
    let mut pool_guard = DB_POOL.write().await;
    *pool_guard = Some(pool);
    
    log::info!("Base de datos SQLite inicializada correctamente");
    Ok(())
}

async fn apply_migrations(pool: &DbPool) -> Result<(), String> {
    // Generated by Copilot
    sqlx::query(migrations::CREATE_MIGRATIONS_TABLE)
        .execute(pool)
        .await
        .map_err(|e| format!("Error creando tabla _migrations: {}", e))?;

    let current_version: i64 = sqlx::query_scalar(migrations::GET_CURRENT_VERSION)
        .fetch_one(pool)
        .await
        .map_err(|e| format!("Error leyendo versión actual: {}", e))?;

    let mut pending = migrations::read_migrations();
    pending.retain(|m| (m.version as i64) > current_version);

    for migration in pending {
        log::info!("Aplicando migración {} (v{})", migration.name, migration.version);
        sqlx::query("BEGIN TRANSACTION")
            .execute(pool)
            .await
            .map_err(|e| format!("Error iniciando transacción: {}", e))?;

        execute_sql_script(pool, &migration.sql).await?;

        sqlx::query(migrations::INSERT_MIGRATION)
            .bind(migration.version)
            .bind(&migration.name)
            .execute(pool)
            .await
            .map_err(|e| format!("Error registrando migración: {}", e))?;

        sqlx::query("COMMIT")
            .execute(pool)
            .await
            .map_err(|e| format!("Error cerrando transacción: {}", e))?;
    }

    Ok(())
}

async fn execute_sql_script(pool: &DbPool, sql: &str) -> Result<(), String> {
    let cleaned = sql
        .lines()
        .filter(|line| !line.trim_start().starts_with("--"))
        .collect::<Vec<_>>()
        .join("\n");

    for statement in cleaned
        .split(';')
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
    {
        sqlx::query(statement)
            .execute(pool)
            .await
            .map_err(|e| format!("Error ejecutando migración: {}", e))?;
    }

    Ok(())
}

/// Obtiene el pool de conexiones
pub async fn get_pool() -> Result<DbPool, String> {
    let pool_guard = DB_POOL.read().await;
    pool_guard.clone().ok_or_else(|| "Base de datos no inicializada".to_string())
}

/// Genera un UUID v4
pub fn generate_id() -> String {
    uuid::Uuid::new_v4().to_string()
}

/// Obtiene la fecha/hora actual en formato ISO
pub fn now() -> String {
    chrono::Utc::now().to_rfc3339()
}
