// Generated by Copilot
// Migrador de base de datos SQLite para Tlanti4Dental
// Ejecuta migraciones SQL automáticamente al iniciar

#![allow(dead_code)]

use std::fs;
use std::path::PathBuf;

/// Información de una migración
#[derive(Debug)]
pub struct Migration {
    pub version: i32,
    pub name: String,
    pub sql: String,
}

/// Obtiene el directorio de migraciones
fn get_migrations_dir() -> PathBuf {
    // En desarrollo, las migraciones viven junto al módulo de DB en src/lib/db/migrations
    // En producción, se empaquetan con la app
    let base = std::env::current_dir().unwrap_or_default();

    let mut unified = base.clone();
    unified.push("..");
    unified.push("src");
    unified.push("lib");
    unified.push("db");
    unified.push("migrations");
    if unified.exists() {
        return unified;
    }

    let mut fallback = base;
    fallback.push("migrations");
    fallback
}

/// Lee todas las migraciones disponibles
pub fn read_migrations() -> Vec<Migration> {
    let migrations_dir = get_migrations_dir();
    let mut migrations = Vec::new();

    log::info!("Buscando migraciones en: {:?}", migrations_dir);

    if let Ok(entries) = fs::read_dir(&migrations_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(false, |ext| ext == "sql") {
                if let Some(file_name) = path.file_name().and_then(|n| n.to_str()) {
                    // Parsear versión del nombre del archivo (001_xxxx.sql)
                    if let Some(version) = parse_migration_version(file_name) {
                        if let Ok(sql) = fs::read_to_string(&path) {
                            migrations.push(Migration {
                                version,
                                name: file_name.to_string(),
                                sql,
                            });
                            log::info!("Migración encontrada: {} (v{})", file_name, version);
                        }
                    }
                }
            }
        }
    } else {
        log::warn!("No se encontró el directorio de migraciones: {:?}", migrations_dir);
    }

    // Ordenar por versión
    migrations.sort_by_key(|m| m.version);
    migrations
}

/// Parsea la versión del nombre del archivo de migración
fn parse_migration_version(filename: &str) -> Option<i32> {
    // Formato esperado: 001_name.sql, 002_name.sql, etc.
    let parts: Vec<&str> = filename.splitn(2, '_').collect();
    if parts.len() >= 1 {
        parts[0].parse::<i32>().ok()
    } else {
        None
    }
}

/// SQL para crear la tabla de migraciones
pub const CREATE_MIGRATIONS_TABLE: &str = r#"
    CREATE TABLE IF NOT EXISTS _migrations (
        version INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        applied_at TEXT DEFAULT (datetime('now'))
    );
"#;

/// SQL para verificar versión actual
pub const GET_CURRENT_VERSION: &str = r#"
    SELECT COALESCE(MAX(version), 0) as version FROM _migrations;
"#;

/// SQL para registrar una migración aplicada
pub const INSERT_MIGRATION: &str = r#"
    INSERT INTO _migrations (version, name) VALUES (?, ?);
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_migration_version() {
        assert_eq!(parse_migration_version("001_initial.sql"), Some(1));
        assert_eq!(parse_migration_version("002_add_users.sql"), Some(2));
        assert_eq!(parse_migration_version("010_big_update.sql"), Some(10));
        assert_eq!(parse_migration_version("invalid.sql"), None);
    }
}
