// Generated by Copilot
use serde::Serialize;
use std::path::PathBuf;

#[cfg(feature = "backend-geometry")]
use nalgebra::{Point3, Vector3};
#[cfg(feature = "backend-geometry")]
use parry3d::bounding_volume::Aabb;
#[cfg(feature = "backend-geometry")]
use parry3d::math::Vector as ParryVector;
#[cfg(feature = "backend-geometry")]
use rstar::{PointDistance, RTree, RTreeObject, AABB};

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BackendIntegration {
    pub id: &'static str,
    pub crate_name: &'static str,
    pub category: &'static str,
    pub status: &'static str,
    pub enabled: bool,
    pub feature: &'static str,
    pub route: &'static str,
    pub notes: &'static str,
    pub requires_system_dependencies: bool,
}

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BackendCatalog {
    pub app_surface: &'static str,
    pub active_feature_count: usize,
    pub experimental_feature_count: usize,
    pub integrations: Vec<BackendIntegration>,
}

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GeometryProbe {
    pub centroid: [f32; 3],
    pub bounds_min: [f32; 3],
    pub bounds_max: [f32; 3],
    pub bounds_size: [f32; 3],
    pub nearest_sample_index: usize,
    pub route: &'static str,
}

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DicomInspection {
    pub path: String,
    pub patient_name: Option<String>,
    pub modality: Option<String>,
    pub study_date: Option<String>,
    pub series_description: Option<String>,
    pub route: &'static str,
}

#[cfg(feature = "backend-geometry")]
#[derive(Clone, Copy)]
struct IndexedPoint {
    index: usize,
    point: [f32; 3],
}

#[cfg(feature = "backend-geometry")]
impl RTreeObject for IndexedPoint {
    type Envelope = AABB<[f32; 3]>;

    fn envelope(&self) -> Self::Envelope {
        AABB::from_point(self.point)
    }
}

#[cfg(feature = "backend-geometry")]
impl PointDistance for IndexedPoint {
    fn distance_2(&self, point: &[f32; 3]) -> f32 {
        let dx = self.point[0] - point[0];
        let dy = self.point[1] - point[1];
        let dz = self.point[2] - point[2];
        dx * dx + dy * dy + dz * dz
    }
}

pub fn get_backend_catalog() -> BackendCatalog {
    let integrations = vec![
    BackendIntegration {
      id: "mesh-csg-manifold",
      crate_name: "manifold-csg",
      category: "mesh-processing",
      status: if cfg!(feature = "backend-manifold-csg") { "ready" } else { "planned" },
      enabled: cfg!(feature = "backend-manifold-csg"),
      feature: "backend-manifold-csg",
      route: "workspace/backend/manifold-csg",
      notes: "Safe Rust wrapper over manifold3d for robust mesh booleans, extrude/revolve flows and mesh-first CAD tooling.",
      requires_system_dependencies: true,
    },
    BackendIntegration {
      id: "mesh-csg",
      crate_name: "csgrs",
      category: "mesh-processing",
      status: if cfg!(feature = "backend-csg") { "ready" } else { "optional" },
      enabled: cfg!(feature = "backend-csg"),
      feature: "backend-csg",
      route: "workspace/backend/mesh-csg",
      notes: "Pure-Rust CSG entry point for boolean operations and STL-oriented workflows.",
      requires_system_dependencies: false,
    },
    BackendIntegration {
      id: "dicom-core",
      crate_name: "dicom + dicom-object",
      category: "dicom",
      status: if cfg!(feature = "backend-dicom") { "ready" } else { "optional" },
      enabled: cfg!(feature = "backend-dicom"),
      feature: "backend-dicom",
      route: "workspace/backend/dicom",
      notes: "High-level DICOM tree access for patient/study metadata and future slice pipelines.",
      requires_system_dependencies: false,
    },
    BackendIntegration {
      id: "compression-lzma",
      crate_name: "lzma-rs",
      category: "compression",
      status: if cfg!(feature = "backend-compression") { "ready" } else { "optional" },
      enabled: cfg!(feature = "backend-compression"),
      feature: "backend-compression",
      route: "workspace/backend/compression",
      notes: "Pure-Rust LZMA/XZ decoder path for compressed CAD payloads.",
      requires_system_dependencies: false,
    },
    BackendIntegration {
      id: "geometry-core",
      crate_name: "nalgebra + parry3d + rstar",
      category: "geometry",
      status: if cfg!(feature = "backend-geometry") { "ready" } else { "optional" },
      enabled: cfg!(feature = "backend-geometry"),
      feature: "backend-geometry",
      route: "workspace/backend/geometry",
      notes: "Linear algebra, collision-space bounds and nearest-neighbor queries for CAD tooling.",
      requires_system_dependencies: false,
    },
    BackendIntegration {
      id: "formats-core",
      crate_name: "stl_io + ply-rs + gltf + obj + image",
      category: "cad-formats",
      status: if cfg!(feature = "backend-formats") { "ready" } else { "optional" },
      enabled: cfg!(feature = "backend-formats"),
      feature: "backend-formats",
      route: "workspace/backend/formats",
      notes: "Mesh and asset format support for STL, PLY, glTF, OBJ and raster preprocessing.",
      requires_system_dependencies: false,
    },
    BackendIntegration {
      id: "mesh-optimization",
      crate_name: "meshopt + rapier3d",
      category: "optimization",
      status: if cfg!(feature = "backend-optimization") { "experimental" } else { "planned" },
      enabled: cfg!(feature = "backend-optimization"),
      feature: "backend-optimization",
      route: "workspace/backend/optimization",
      notes: "Reserved for mesh optimization and physical verification passes in future waves.",
      requires_system_dependencies: false,
    },
    BackendIntegration {
      id: "vision-opencv",
      crate_name: "opencv",
      category: "vision",
      status: if cfg!(feature = "backend-vision") { "experimental" } else { "planned" },
      enabled: cfg!(feature = "backend-vision"),
      feature: "backend-vision",
      route: "workspace/backend/vision",
      notes: "Feature-gated because OpenCV requires native system toolchain provisioning.",
      requires_system_dependencies: true,
    },
    BackendIntegration {
      id: "ml-onnx",
      crate_name: "tract-onnx",
      category: "machine-learning",
      status: if cfg!(feature = "backend-ml") { "experimental" } else { "planned" },
      enabled: cfg!(feature = "backend-ml"),
      feature: "backend-ml",
      route: "workspace/backend/ml",
      notes: "Feature-gated for future segmentation and inference workflows.",
      requires_system_dependencies: false,
    },
    BackendIntegration {
      id: "python-sidecar",
      crate_name: "python3 + JSON sidecar",
      category: "python-runtime",
      status: "experimental",
      enabled: true,
      feature: "runtime-default",
      route: "workspace/backend/python/sidecar",
      notes: "Current route for external dental Python tooling such as in-app mesh segmentation sidecars.",
      requires_system_dependencies: true,
    },
    BackendIntegration {
      id: "python-pyo3",
      crate_name: "pyo3",
      category: "python-runtime",
      status: if cfg!(feature = "backend-python-embed") { "experimental" } else { "optional" },
      enabled: cfg!(feature = "backend-python-embed"),
      feature: "backend-python-embed",
      route: "workspace/backend/python/pyo3",
      notes: "Optional embedded Python bridge for runtime inspection and future Rust↔Python adapters.",
      requires_system_dependencies: true,
    },
    BackendIntegration {
      id: "brep-opencascade",
      crate_name: "opencascade",
      category: "industrial-cad",
      status: if cfg!(feature = "backend-opencascade") { "experimental" } else { "planned" },
      enabled: cfg!(feature = "backend-opencascade"),
      feature: "backend-opencascade",
      route: "workspace/backend/opencascade",
      notes: "Feature-gated because OpenCascade adds CMake/C++ toolchain and CAD kernel complexity.",
      requires_system_dependencies: true,
    },
    BackendIntegration {
      id: "brep-occt-wasm-webview",
      crate_name: "OCCT WASM + Tauri WebView",
      category: "industrial-cad-preview",
      status: "planned",
      enabled: false,
      feature: "frontend-occt-wasm",
      route: "workspace/backend/occt-wasm-webview",
      notes: "Offline WebView-hosted OCCT preview path for B-Rep experiments, STEP/IGES inspection and Fumadocs demos. It must exchange handles/manifests, not full mesh buffers over JSON IPC.",
      requires_system_dependencies: false,
    },
  ];

    let active_feature_count = integrations.iter().filter(|item| item.enabled).count();
    let experimental_feature_count = integrations
        .iter()
        .filter(|item| item.status == "experimental" || item.status == "planned")
        .count();

    BackendCatalog {
        app_surface: "Workspace / Settings / Backend Integrations",
        active_feature_count,
        experimental_feature_count,
        integrations,
    }
}

#[cfg(feature = "backend-geometry")]
pub fn run_geometry_probe() -> GeometryProbe {
    let points = [
        Point3::new(-12.0_f32, 4.0_f32, 3.0_f32),
        Point3::new(8.0_f32, -6.0_f32, 2.5_f32),
        Point3::new(4.5_f32, 7.5_f32, 9.0_f32),
        Point3::new(-1.0_f32, 2.0_f32, -4.0_f32),
    ];

    let centroid_sum = points
        .iter()
        .fold(Vector3::zeros(), |acc, point| acc + point.coords);
    let centroid = centroid_sum / points.len() as f32;

    let min = ParryVector::new(
        points
            .iter()
            .map(|point| point.x)
            .fold(f32::INFINITY, f32::min),
        points
            .iter()
            .map(|point| point.y)
            .fold(f32::INFINITY, f32::min),
        points
            .iter()
            .map(|point| point.z)
            .fold(f32::INFINITY, f32::min),
    );
    let max = ParryVector::new(
        points
            .iter()
            .map(|point| point.x)
            .fold(f32::NEG_INFINITY, f32::max),
        points
            .iter()
            .map(|point| point.y)
            .fold(f32::NEG_INFINITY, f32::max),
        points
            .iter()
            .map(|point| point.z)
            .fold(f32::NEG_INFINITY, f32::max),
    );

    let aabb = Aabb::new(min.into(), max.into());
    let size = aabb.maxs - aabb.mins;

    let tree = RTree::bulk_load(
        points
            .iter()
            .enumerate()
            .map(|(index, point)| IndexedPoint {
                index,
                point: [point.x, point.y, point.z],
            })
            .collect(),
    );

    let nearest_sample_index = tree
        .nearest_neighbor(&[0.5_f32, 1.0_f32, 0.0_f32])
        .map(|nearest| nearest.index)
        .unwrap_or_default();

    GeometryProbe {
        centroid: [centroid.x, centroid.y, centroid.z],
        bounds_min: [aabb.mins.x, aabb.mins.y, aabb.mins.z],
        bounds_max: [aabb.maxs.x, aabb.maxs.y, aabb.maxs.z],
        bounds_size: [size.x, size.y, size.z],
        nearest_sample_index,
        route: "workspace/backend/geometry/probe",
    }
}

#[cfg(not(feature = "backend-geometry"))]
pub fn run_geometry_probe() -> GeometryProbe {
    GeometryProbe {
        centroid: [0.0, 0.0, 0.0],
        bounds_min: [0.0, 0.0, 0.0],
        bounds_max: [0.0, 0.0, 0.0],
        bounds_size: [0.0, 0.0, 0.0],
        nearest_sample_index: 0,
        route: "workspace/backend/geometry/probe-disabled",
    }
}

fn validate_existing_file(path: &str) -> Result<PathBuf, String> {
    let path_buf = PathBuf::from(path);

    if !path_buf.exists() {
        return Err(format!("File does not exist: {path}"));
    }

    if !path_buf.is_file() {
        return Err(format!("Path is not a file: {path}"));
    }

    Ok(path_buf)
}

#[cfg(feature = "backend-dicom")]
fn read_dicom_string(obj: &dicom_object::DefaultDicomObject, name: &str) -> Option<String> {
    obj.element_by_name(name)
        .ok()
        .and_then(|element| element.to_str().ok())
        .map(|value| value.into_owned())
}

#[cfg(feature = "backend-dicom")]
pub fn inspect_dicom_metadata(path: String) -> Result<DicomInspection, String> {
    let path_buf = validate_existing_file(&path)?;
    let object = dicom_object::open_file(&path_buf)
        .map_err(|error| format!("Failed to open DICOM file {}: {error}", path_buf.display()))?;

    Ok(DicomInspection {
        path: path_buf.display().to_string(),
        patient_name: read_dicom_string(&object, "PatientName"),
        modality: read_dicom_string(&object, "Modality"),
        study_date: read_dicom_string(&object, "StudyDate"),
        series_description: read_dicom_string(&object, "SeriesDescription"),
        route: "workspace/backend/dicom/inspect",
    })
}

#[cfg(not(feature = "backend-dicom"))]
pub fn inspect_dicom_metadata(path: String) -> Result<DicomInspection, String> {
    let _ = validate_existing_file(&path)?;
    Err("DICOM backend feature is disabled in this build".to_string())
}
