// Generated by Codex
use crate::python_runtime::resolve_default_python_path;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::{
    collections::HashMap,
    fs,
    path::{Path, PathBuf},
    process::Command,
    sync::{Mutex, OnceLock},
    time::{SystemTime, UNIX_EPOCH},
};
use uuid::Uuid;

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DicomImportPrepareRequest {
    pub case_id: String,
    pub source_path: String,
    pub clinical_role: Option<String>,
}

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DicomSeriesImportStartRequest {
    pub case_id: String,
    pub source_path: String,
    pub clinical_role: Option<String>,
}

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DicomVolumeBuildStartRequest {
    pub case_id: String,
    pub series_manifest_path: String,
}

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DicomSeriesManifest {
    pub manifest_id: String,
    pub case_id: String,
    pub source_path: String,
    pub manifest_path: String,
    pub clinical_role: String,
    pub engine: String,
    pub file_count: usize,
    pub bytes: u64,
    pub study_uid: String,
    pub series_uid: String,
    pub modality: String,
    pub rows: u32,
    pub columns: u32,
    pub anonymization_status: String,
    pub raw: Value,
}

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DicomJobStatus {
    pub job_id: String,
    pub kind: String,
    pub state: String,
    pub progress: f32,
    pub message: String,
    pub manifest: Option<DicomSeriesManifest>,
    pub artifact_path: Option<String>,
    pub error: Option<String>,
    pub updated_at: u64,
}

static JOBS: OnceLock<Mutex<HashMap<String, DicomJobStatus>>> = OnceLock::new();

fn jobs() -> &'static Mutex<HashMap<String, DicomJobStatus>> {
    JOBS.get_or_init(|| Mutex::new(HashMap::new()))
}

fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or_default()
}

fn repo_root() -> PathBuf {
    std::env::current_dir()
        .ok()
        .and_then(|cwd| {
            if cwd.join("package.json").exists() {
                Some(cwd)
            } else if cwd
                .parent()
                .map(|parent| parent.join("package.json").exists())
                .unwrap_or(false)
            {
                cwd.parent().map(Path::to_path_buf)
            } else {
                None
            }
        })
        .unwrap_or_else(|| PathBuf::from("."))
}

fn artifact_root(case_id: &str, job_id: &str) -> Result<PathBuf, String> {
    let path = std::env::temp_dir()
        .join("tlanticad")
        .join("dicom")
        .join(case_id)
        .join(job_id);
    fs::create_dir_all(&path)
        .map_err(|error| format!("Could not create DICOM artifact folder: {error}"))?;
    Ok(path)
}

fn manifest_from_value(
    raw: Value,
    manifest_path: &Path,
    case_id: &str,
    clinical_role: &str,
) -> DicomSeriesManifest {
    DicomSeriesManifest {
        manifest_id: raw
            .get("manifestId")
            .and_then(Value::as_str)
            .unwrap_or_else(|| {
                manifest_path
                    .file_stem()
                    .and_then(|value| value.to_str())
                    .unwrap_or("series")
            })
            .to_string(),
        case_id: case_id.to_string(),
        source_path: raw
            .get("sourcePath")
            .and_then(Value::as_str)
            .unwrap_or("")
            .to_string(),
        manifest_path: manifest_path.to_string_lossy().to_string(),
        clinical_role: clinical_role.to_string(),
        engine: raw
            .get("engine")
            .and_then(Value::as_str)
            .unwrap_or("python-pydicom")
            .to_string(),
        file_count: raw
            .get("fileCount")
            .and_then(Value::as_u64)
            .unwrap_or_default() as usize,
        bytes: raw.get("bytes").and_then(Value::as_u64).unwrap_or_default(),
        study_uid: raw
            .get("studyUid")
            .and_then(Value::as_str)
            .unwrap_or("")
            .to_string(),
        series_uid: raw
            .get("seriesUid")
            .and_then(Value::as_str)
            .unwrap_or("")
            .to_string(),
        modality: raw
            .get("modality")
            .and_then(Value::as_str)
            .unwrap_or("")
            .to_string(),
        rows: raw.get("rows").and_then(Value::as_u64).unwrap_or_default() as u32,
        columns: raw
            .get("columns")
            .and_then(Value::as_u64)
            .unwrap_or_default() as u32,
        anonymization_status: raw
            .get("anonymizationStatus")
            .and_then(Value::as_str)
            .unwrap_or("unknown")
            .to_string(),
        raw,
    }
}

fn run_pydicom_manifest(
    case_id: &str,
    source_path: &str,
    clinical_role: &str,
    manifest_path: &Path,
) -> Result<DicomSeriesManifest, String> {
    let python = resolve_default_python_path().unwrap_or_else(|| PathBuf::from("python3"));
    let root = repo_root();
    let script = [
        root.join("Tauri")
            .join("backend")
            .join("python")
            .join("dicom_manifest.py"),
        root.join("backend")
            .join("python")
            .join("dicom_manifest.py"),
    ]
    .into_iter()
    .find(|candidate| candidate.exists())
    .unwrap_or_else(|| {
        root.join("Tauri")
            .join("backend")
            .join("python")
            .join("dicom_manifest.py")
    });
    if !script.exists() {
        return Err(format!(
            "pydicom manifest script is missing: {}",
            script.display()
        ));
    }

    let output = Command::new(&python)
        .arg(&script)
        .arg("--source")
        .arg(source_path)
        .arg("--case-id")
        .arg(case_id)
        .arg("--role")
        .arg(clinical_role)
        .arg("--manifest-path")
        .arg(manifest_path)
        .output()
        .map_err(|error| {
            format!(
                "Could not start Python/pydicom DICOM importer ({}): {error}",
                python.display()
            )
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("Python/pydicom DICOM import failed: {stderr}"));
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    let raw: Value = serde_json::from_str(stdout.trim())
        .map_err(|error| format!("Could not parse pydicom manifest JSON: {error}"))?;
    Ok(manifest_from_value(
        raw,
        manifest_path,
        case_id,
        clinical_role,
    ))
}

#[tauri::command]
pub fn dicom_import_prepare_from_path(
    request: DicomImportPrepareRequest,
) -> Result<DicomSeriesManifest, String> {
    let job_id = Uuid::new_v4().to_string();
    let role = request.clinical_role.as_deref().unwrap_or("dicom");
    let root = artifact_root(&request.case_id, &job_id)?;
    let manifest_path = root.join("series-manifest.json");
    run_pydicom_manifest(&request.case_id, &request.source_path, role, &manifest_path)
}

#[tauri::command]
pub fn dicom_series_import_start(
    request: DicomSeriesImportStartRequest,
) -> Result<DicomJobStatus, String> {
    let job_id = Uuid::new_v4().to_string();
    let role = request.clinical_role.as_deref().unwrap_or("dicom");
    let root = artifact_root(&request.case_id, &job_id)?;
    let manifest_path = root.join("series-manifest.json");
    let status =
        match run_pydicom_manifest(&request.case_id, &request.source_path, role, &manifest_path) {
            Ok(manifest) => DicomJobStatus {
                job_id: job_id.clone(),
                kind: "dicom-series-import".to_string(),
                state: "completed".to_string(),
                progress: 1.0,
                message: "DICOM series manifest persisted with Python/pydicom.".to_string(),
                manifest: Some(manifest),
                artifact_path: Some(manifest_path.to_string_lossy().to_string()),
                error: None,
                updated_at: now_secs(),
            },
            Err(error) => DicomJobStatus {
                job_id: job_id.clone(),
                kind: "dicom-series-import".to_string(),
                state: "failed".to_string(),
                progress: 1.0,
                message: "DICOM import failed before manifest persistence.".to_string(),
                manifest: None,
                artifact_path: None,
                error: Some(error),
                updated_at: now_secs(),
            },
        };

    jobs()
        .lock()
        .map_err(|_| "DICOM job registry lock poisoned".to_string())?
        .insert(job_id, status.clone());
    Ok(status)
}

#[tauri::command]
pub fn dicom_series_job_status(job_id: String) -> Result<DicomJobStatus, String> {
    jobs()
        .lock()
        .map_err(|_| "DICOM job registry lock poisoned".to_string())?
        .get(&job_id)
        .cloned()
        .ok_or_else(|| format!("DICOM import job not found: {job_id}"))
}

#[tauri::command]
pub fn dicom_series_import_cancel(job_id: String) -> Result<DicomJobStatus, String> {
    let mut guard = jobs()
        .lock()
        .map_err(|_| "DICOM job registry lock poisoned".to_string())?;
    let status = guard
        .get_mut(&job_id)
        .ok_or_else(|| format!("DICOM import job not found: {job_id}"))?;
    if status.state == "running" || status.state == "queued" {
        status.state = "cancelled".to_string();
        status.message = "DICOM import cancelled before completion.".to_string();
        status.updated_at = now_secs();
    }
    Ok(status.clone())
}

#[tauri::command]
pub fn dicom_volume_build_start(
    request: DicomVolumeBuildStartRequest,
) -> Result<DicomJobStatus, String> {
    let job_id = Uuid::new_v4().to_string();
    let manifest_text = fs::read_to_string(&request.series_manifest_path)
        .map_err(|error| format!("Could not read DICOM series manifest: {error}"))?;
    let manifest: Value = serde_json::from_str(&manifest_text)
        .map_err(|error| format!("Could not parse DICOM series manifest: {error}"))?;
    let volume_path = artifact_root(&request.case_id, &job_id)?.join("volume-manifest.json");
    let volume_manifest = serde_json::json!({
        "volumeId": job_id,
        "caseId": request.case_id,
        "seriesManifestPath": request.series_manifest_path,
        "engine": "metadata-volume-v1",
        "fileCount": manifest.get("fileCount").and_then(Value::as_u64).unwrap_or_default(),
        "rows": manifest.get("rows").and_then(Value::as_u64).unwrap_or_default(),
        "columns": manifest.get("columns").and_then(Value::as_u64).unwrap_or_default(),
        "clinicalExportAllowed": false,
        "reason": "Volume handle is metadata-only until pixel stack build is enabled."
    });
    fs::write(
        &volume_path,
        serde_json::to_vec_pretty(&volume_manifest).map_err(|error| error.to_string())?,
    )
    .map_err(|error| format!("Could not persist DICOM volume manifest: {error}"))?;

    let status = DicomJobStatus {
        job_id: job_id.clone(),
        kind: "dicom-volume-build".to_string(),
        state: "completed".to_string(),
        progress: 1.0,
        message:
            "DICOM volume handle persisted. Pixel stack build remains disabled for clinical export."
                .to_string(),
        manifest: None,
        artifact_path: Some(volume_path.to_string_lossy().to_string()),
        error: None,
        updated_at: now_secs(),
    };
    jobs()
        .lock()
        .map_err(|_| "DICOM job registry lock poisoned".to_string())?
        .insert(job_id, status.clone());
    Ok(status)
}

#[tauri::command]
pub fn dicom_volume_job_status(job_id: String) -> Result<DicomJobStatus, String> {
    dicom_series_job_status(job_id)
}
