// Generated by Copilot
mod abutment_presets;
mod backend_integrations;
mod backend_topology;
mod backend_workspace;
mod cad_abutment;
pub mod cad_abutment_production;
pub mod cad_abutment_real;
mod cad_alignment;
pub mod cad_articulator_real;
pub mod cad_bridge_connector;
pub mod cad_compute_router;
mod cad_core;
pub mod cad_crown_bottom;
pub mod cad_crown_feedback;
pub mod cad_crown_pipeline;
pub mod cad_csg;
pub mod cad_dicom_seg_and_guide;
pub mod cad_endo_real;
pub mod cad_freeform_brush;
pub mod cad_freeform_specialty;
pub mod cad_implant_manager;
pub mod cad_insertion_axis;
pub mod cad_margin_real;
pub mod cad_mesh_kernel;
pub mod cad_parameters_store;
mod cad_shell;
pub mod cad_show_distances_real;
mod case_repository;
pub mod case_storage;
pub mod case_watcher;
mod chat_persistence;
mod clinical_jobs;
mod dental_model_seg;
mod dicom_jobs;
mod dicom_segmentation_jobs;
mod local_share;
mod manifold_csg_runtime;
pub mod mesh_rasterizer;
mod mesh_vault;
mod public_asset_manifest;
mod python_runtime;
mod storage_layout;
mod system_runtime;
mod toolkit_codec;
mod trame_slicer_sidecar;

use backend_integrations::{
    get_backend_catalog, inspect_dicom_metadata as inspect_dicom_metadata_impl, run_geometry_probe,
};
use dental_model_seg::DentalModelSegSidecarState;
use manifold_csg_runtime::run_manifold_csg_probe as run_manifold_csg_probe_impl;
use serde::{Deserialize, Serialize};
use system_runtime::get_system_runtime_report;
use tauri::{Manager, WebviewUrl, WebviewWindowBuilder};

const BUILD_UID: &str = "TCS-A0.1.0-20260403-MX-IXA-001";

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct RuntimeInfo {
    app_name: &'static str,
    company: &'static str,
    location: &'static str,
    version: &'static str,
    build_uid: &'static str,
    profile: &'static str,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct LocalBackendEndpoint {
    base_url: &'static str,
    health_path: &'static str,
    websocket_base_url: &'static str,
    offline_only: bool,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct OpenWorkspaceWindowRequest {
    label: String,
    workspace: String,
    case_id: Option<String>,
    module: Option<String>,
    title: Option<String>,
}

fn build_workspace_window_path(request: &OpenWorkspaceWindowRequest) -> String {
    let mut query = vec![format!(
        "workspace={}",
        urlencoding::encode(&request.workspace)
    )];

    if let Some(case_id) = &request.case_id {
        query.push(format!("caseId={}", urlencoding::encode(case_id)));
    }

    if let Some(module) = &request.module {
        query.push(format!("module={}", urlencoding::encode(module)));
    }

    format!("/?{}", query.join("&"))
}

#[tauri::command]
fn get_runtime_info() -> RuntimeInfo {
    RuntimeInfo {
        app_name: "TlantiCAD Studio",
        company: "TlantiDental Studio",
        location: "Ixtapaluca, Estado de México, México",
        version: env!("CARGO_PKG_VERSION"),
        build_uid: BUILD_UID,
        profile: if cfg!(debug_assertions) {
            "debug"
        } else {
            "release"
        },
    }
}

#[tauri::command]
fn local_backend_endpoint() -> LocalBackendEndpoint {
    LocalBackendEndpoint {
        base_url: "http://127.0.0.1:17493",
        health_path: "/api/v1/health/local",
        websocket_base_url: "ws://127.0.0.1:17493/api/ws",
        offline_only: true,
    }
}

#[tauri::command]
fn get_backend_integration_catalog() -> backend_integrations::BackendCatalog {
    get_backend_catalog()
}

#[tauri::command]
fn inspect_backend_workspace() -> Result<backend_workspace::BackendWorkspaceCatalog, String> {
    backend_workspace::inspect_backend_workspace()
}

#[tauri::command]
fn run_backend_geometry_probe() -> backend_integrations::GeometryProbe {
    run_geometry_probe()
}

#[tauri::command]
fn run_backend_manifold_csg_probe() -> manifold_csg_runtime::ManifoldCsgProbe {
    run_manifold_csg_probe_impl()
}

#[tauri::command]
fn compress_text_lzma(payload: String) -> Result<String, String> {
    toolkit_codec::compress_text_lzma(payload)
}

#[tauri::command]
fn decompress_text_lzma(payload_base64: String) -> Result<String, String> {
    toolkit_codec::decompress_text_lzma(payload_base64)
}

#[tauri::command]
fn encrypt_text_payload(
    payload: String,
    passphrase: String,
) -> Result<toolkit_codec::EncryptedPayload, String> {
    toolkit_codec::encrypt_text_payload(payload, passphrase)
}

#[tauri::command]
fn decrypt_text_payload(
    ciphertext_base64: String,
    nonce_base64: String,
    passphrase: String,
) -> Result<String, String> {
    toolkit_codec::decrypt_text_payload(ciphertext_base64, nonce_base64, passphrase)
}

#[tauri::command]
fn inspect_dicom_metadata(path: String) -> Result<backend_integrations::DicomInspection, String> {
    inspect_dicom_metadata_impl(path)
}

#[tauri::command]
fn open_workspace_window(
    app: tauri::AppHandle,
    request: OpenWorkspaceWindowRequest,
) -> Result<(), String> {
    if let Some(existing_window) = app.get_webview_window(&request.label) {
        let _ = existing_window.unminimize();
        let _ = existing_window.show();
        existing_window
            .set_focus()
            .map_err(|error| error.to_string())?;
        return Ok(());
    }

    let window = WebviewWindowBuilder::new(
        &app,
        &request.label,
        WebviewUrl::App(build_workspace_window_path(&request).into()),
    )
    .title(
        request
            .title
            .unwrap_or_else(|| "TlantiCAD Studio".to_string()),
    )
    .inner_size(1600.0, 960.0)
    .min_inner_size(960.0, 620.0)
    .resizable(true)
    .center()
    .build()
    .map_err(|error| error.to_string())?;

    let _ = window.show();
    let _ = window.set_focus();

    Ok(())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let mut builder = tauri::Builder::default();

    #[cfg(desktop)]
    {
        builder = builder.plugin(tauri_plugin_single_instance::init(|app, _, _| {
            if let Some(main_window) = app.get_webview_window("main") {
                let _ = main_window.unminimize();
                let _ = main_window.show();
                let _ = main_window.set_focus();
            }
        }));
    }

    if cfg!(debug_assertions) {
        builder = builder.plugin(
            tauri_plugin_log::Builder::default()
                .level(log::LevelFilter::Info)
                .build(),
        );
    }

    builder
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_os::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_sql::Builder::default().build())
        .plugin(tauri_plugin_store::Builder::default().build())
        .plugin(tauri_plugin_clipboard_manager::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_window_state::Builder::default().build())
        .plugin(tauri_plugin_positioner::init())
        .manage(DentalModelSegSidecarState::default())
        .manage(local_share::LocalShareState::default())
        .manage(case_watcher::CaseWatcherState::default())
        .manage(cad_compute_router::ComputeRouterState::default())
        .setup(|app| {
            python_runtime::hydrate_bundled_python_env(app.handle())?;
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            get_runtime_info,
            backend_topology::inspect_backend_topology,
            local_backend_endpoint,
            get_backend_integration_catalog,
            inspect_backend_workspace,
            run_backend_geometry_probe,
            run_backend_manifold_csg_probe,
            compress_text_lzma,
            decompress_text_lzma,
            encrypt_text_payload,
            decrypt_text_payload,
            inspect_dicom_metadata,
            open_workspace_window,
            case_repository::case_create,
            case_repository::case_save,
            case_repository::case_get_graph,
            case_repository::case_list,
            case_repository::case_save_asset,
            case_repository::asset_write,
            case_repository::asset_read,
            chat_persistence::chat_init,
            chat_persistence::chat_save_session,
            chat_persistence::chat_load_session,
            chat_persistence::chat_list_sessions,
            chat_persistence::chat_delete_session,
            clinical_jobs::clinical_job_record,
            clinical_jobs::clinical_job_get,
            clinical_jobs::clinical_job_list,
            clinical_jobs::clinical_job_cancel,
            clinical_jobs::clinical_artifact_record,
            clinical_jobs::clinical_command_record,
            clinical_jobs::clinical_command_undo,
            clinical_jobs::clinical_command_redo,
            clinical_jobs::clinical_command_event_get,
            public_asset_manifest::get_public_asset_manifest,
            public_asset_manifest::inspect_public_asset,
            get_system_runtime_report,
            python_runtime::get_python_bridge_status,
            python_runtime::sidecar_status,
            trame_slicer_sidecar::trame_slicer_sidecar_status,
            trame_slicer_sidecar::trame_slicer_sidecar_start,
            trame_slicer_sidecar::trame_slicer_sidecar_stop,
            trame_slicer_sidecar::slicer_runtime_status,
            trame_slicer_sidecar::slicer_runtime_download,
            trame_slicer_sidecar::slicer_models_status,
            trame_slicer_sidecar::slicer_fixtures_status,
            trame_slicer_sidecar::slicer_fixtures_download,
            trame_slicer_sidecar::slicer_models_download_all,
            trame_slicer_sidecar::slicer_clinical_job_start,
            trame_slicer_sidecar::slicer_clinical_job_status,
            trame_slicer_sidecar::slicer_clinical_job_cancel,
            cad_core::cad_bootstrap,
            cad_core::tool_registry_get,
            cad_core::case_open,
            cad_core::asset_import_prepare,
            cad_core::cad_job_start,
            cad_core::cad_job_status,
            cad_core::cad_job_cancel,
            cad_core::workflow_start,
            cad_core::workflow_status,
            cad_core::workflow_cancel,
            cad_core::module_permissions_get,
            mesh_vault::mesh_vault_import_start,
            mesh_vault::mesh_vault_job_status,
            mesh_vault::mesh_vault_cancel,
            mesh_vault::mesh_vault_find,
            cad_abutment::abutment_generate_mesh,
            cad_abutment::abutment_plan_screw_channel,
            cad_alignment::alignment_register_landmarks,
            cad_alignment::alignment_register_meshes,
            cad_shell::cad_shell_bootstrap,
            dental_model_seg::get_dental_model_seg_status,
            dental_model_seg::run_dental_model_segmentation,
            dental_model_seg::stop_dental_model_seg_sidecar,
            dicom_jobs::dicom_import_prepare_from_path,
            dicom_jobs::dicom_series_import_start,
            dicom_jobs::dicom_series_job_status,
            dicom_jobs::dicom_series_import_cancel,
            dicom_jobs::dicom_volume_build_start,
            dicom_jobs::dicom_volume_job_status,
            dicom_segmentation_jobs::dicom_segmentation_start,
            dicom_segmentation_jobs::dicom_segmentation_job_status,
            dicom_segmentation_jobs::dicom_segmentation_cancel,
            dicom_segmentation_jobs::dicom_segmentation_to_mesh_start,
            cad_csg::mesh_op,
            cad_mesh_kernel::mesh_kernel_add_remove,
            cad_mesh_kernel::mesh_kernel_compare,
            cad_mesh_kernel::mesh_kernel_adapt_to_gingiva,
            cad_insertion_axis::cad_insertion_compute,
            cad_insertion_axis::cad_insertion_unify_bridge,
            cad_margin_real::cad_margin_detect_real,
            cad_margin_real::cad_margin_correct_real,
            cad_margin_real::cad_margin_repair_real,
            cad_bridge_connector::cad_bridge_connector_create,
            cad_crown_bottom::cad_crown_bottom_generate,
            cad_abutment_real::cad_abutment_generate_real,
            cad_abutment_real::cad_abutment_validate_real,
            cad_freeform_brush::cad_freeform_paint_pull,
            cad_freeform_brush::cad_freeform_paint_smooth,
            cad_freeform_brush::cad_freeform_paint_drape,
            cad_freeform_brush::cad_freeform_emergence_profile,
            cad_articulator_real::cad_articulator_default_triangle,
            cad_articulator_real::cad_articulator_register,
            cad_articulator_real::cad_articulator_simulate,
            cad_articulator_real::cad_articulator_fit_plane,
            cad_endo_real::cad_endo_chamber_build,
            cad_endo_real::cad_endo_estimate_canal_axis,
            cad_show_distances_real::cad_show_distances_real,
            cad_implant_manager::cad_implant_change_type,
            cad_implant_manager::cad_implant_delete,
            cad_implant_manager::cad_implant_define_references,
            cad_implant_manager::cad_implant_validate_placement,
            cad_crown_feedback::cad_crown_validate_real,
            cad_crown_feedback::cad_crown_constraint_bounds,
            cad_crown_pipeline::cad_crown_pipeline_run,
            cad_abutment_production::cad_abutment_production_blank,
            cad_abutment_production::cad_abutment_screw_channel,
            cad_abutment_production::cad_abutment_nesting_puck,
            cad_freeform_specialty::cad_freeform_bar_create,
            cad_freeform_specialty::cad_freeform_telescope_create,
            cad_freeform_specialty::cad_freeform_post_and_core_create,
            cad_parameters_store::parameters_load,
            cad_parameters_store::parameters_save,
            cad_parameters_store::parameters_reset,
            cad_parameters_store::parameters_list_scopes,
            cad_parameters_store::parameters_export_json,
            cad_dicom_seg_and_guide::cad_dicom_threshold_voxels,
            cad_dicom_seg_and_guide::cad_dicom_region_grow_3d,
            cad_dicom_seg_and_guide::cad_dicom_marching_cubes,
            cad_dicom_seg_and_guide::cad_guide_extract_gingiva,
            cad_dicom_seg_and_guide::cad_guide_build_sleeve,
            case_watcher::case_watcher_start,
            case_watcher::case_watcher_stop,
            cad_compute_router::cad_compute_run_bench,
            cad_compute_router::cad_compute_run_boundary_bench,
            cad_compute_router::cad_compute_status,
            cad_compute_router::cad_compute_set_energy_mode,
            abutment_presets::abutment_preset_save,
            abutment_presets::abutment_preset_list,
            abutment_presets::abutment_preset_delete,
            abutment_presets::abutment_preset_open_folder,
            case_storage::resolve_paths,
            case_storage::tlanticad_data_root_get,
            case_storage::validate_case,
            case_storage::case_blob_encrypt,
            case_storage::case_blob_decrypt,
            case_storage::audit_append,
            local_share::local_share_advertise,
            local_share::local_share_stop_advertising,
            local_share::local_share_browse_start,
            local_share::local_share_browse_stop,
            local_share::local_share_listen,
            local_share::local_share_stop_listening,
            local_share::local_share_send,
            local_share::local_share_accept,
            local_share::local_share_reject,
            local_share::local_share_generate_pin,
            local_share::local_share_local_transports,
            mesh_rasterizer::mesh_rasterize
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
