// Generated by Copilot
use serde::Serialize;
use system_info::{
    ai_workload::{analyze_ai_workload, AiWorkloadReport},
    gpu::detect_gpus,
    system::get_system_report_base,
    SystemReport,
};

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SystemRuntimeReport {
    pub system: SystemReport,
    pub ai_workload: AiWorkloadReport,
    pub route: &'static str,
}

#[tauri::command]
pub fn get_system_runtime_report() -> Result<SystemRuntimeReport, String> {
    let (os, cpu, memory, disks) = get_system_report_base();
    let (gpus, capabilities) = detect_gpus();

    let system = SystemReport {
        os,
        cpu,
        memory: memory.clone(),
        gpus: gpus.clone(),
        disks: disks.clone(),
        capabilities: capabilities.clone(),
    };

    let ai_workload = analyze_ai_workload(&gpus, &memory, &disks, &capabilities);

    Ok(SystemRuntimeReport {
        system,
        ai_workload,
        route: "workspace/backend/system/runtime-report",
    })
}
