// Generated by Copilot
import React, { useEffect, useMemo, useState } from 'react';
import { ExternalLink, LibraryBig, RefreshCcw, Search, Sparkles, Wand2 } from 'lucide-react';

import { AssetLibraryFilterChip } from '@/components/asset-library/AssetLibraryFilterChip';
import { AssetLibraryItemRow } from '@/components/asset-library/AssetLibraryItemRow';
import { AssetLibraryPanelMessage } from '@/components/asset-library/AssetLibraryPanelMessage';
import { AssetLibraryUsageCard } from '@/components/asset-library/AssetLibraryUsageCard';
import { LazyPublicAssetModelPreview } from '@/components/asset-library/LazyPublicAssetModelPreview';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import type { TlantiModuleId } from '@/core';
import { isTauriRuntime, openPathInSystem } from '@/platform/desktop-system';
import { loadPublicAssetInsight, type PublicAssetInsight } from '@/lib/public-asset-insights';
import { PUBLIC_ASSET_LIBRARY_ROOTS, listPublicAssetRootsForModule, type PublicAssetLibraryItem, type PublicAssetLibrarySurface, type PublicAssetRoot, isPreviewablePublicAsset, loadPublicAssetLibrary } from '@/lib/public-asset-library';
import { cn } from '@/lib/utils';

export type PublicAssetLibraryActionMode = 'cad' | 'db' | 'semantic';

interface PublicAssetLibraryBrowserProps {
  surface: PublicAssetLibrarySurface;
  moduleId?: TlantiModuleId | null;
  onAction?: (asset: PublicAssetLibraryItem, mode: PublicAssetLibraryActionMode) => Promise<void> | void;
  onBatchAction?: (assets: PublicAssetLibraryItem[], mode: PublicAssetLibraryActionMode) => Promise<void> | void;
  useActionLabel?: string;
  title?: string;
  description?: string;
}

export function PublicAssetLibraryBrowser({
  surface,
  moduleId,
  onAction,
  onBatchAction,
  useActionLabel = surface === 'cad' ? 'Use in CAD' : 'Import to case',
  title = 'Integrated asset library',
  description = 'Analyze and reuse the public library inside CAD and Workspace workflows.',
}: PublicAssetLibraryBrowserProps) {
  const desktopRuntime = isTauriRuntime();
  const availableRoots = useMemo(() => listPublicAssetRootsForModule(moduleId), [moduleId]);
  const [items, setItems] = useState<PublicAssetLibraryItem[]>([]);
  const [search, setSearch] = useState('');
  const [rootFilter, setRootFilter] = useState<'all' | PublicAssetRoot>('all');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [pendingActionId, setPendingActionId] = useState<string | null>(null);
  const [wizardOpen, setWizardOpen] = useState(false);
  const [insight, setInsight] = useState<PublicAssetInsight | null>(null);
  const [insightLoading, setInsightLoading] = useState(false);
  const [selectedAssetIds, setSelectedAssetIds] = useState<string[]>([]);

  const refreshLibrary = React.useCallback(async (forceRefresh = false) => {
    setIsLoading(true);
    setError(null);
    try {
      const nextItems = await loadPublicAssetLibrary({
        forceRefresh,
        moduleId,
        rootFilter,
      });
      setItems(nextItems);
    } catch (libraryError) {
      setError(libraryError instanceof Error ? libraryError.message : 'Unable to load the bundled asset library.');
    } finally {
      setIsLoading(false);
    }
  }, [moduleId, rootFilter]);

  useEffect(() => {
    if (rootFilter !== 'all' && !availableRoots.includes(rootFilter)) {
      setRootFilter('all');
    }
  }, [availableRoots, rootFilter]);

  useEffect(() => {
    void refreshLibrary();
  }, [refreshLibrary]);

  const filteredItems = useMemo(() => {
    const normalized = search.trim().toLowerCase();
    return items.filter((item) => {
      if (rootFilter !== 'all' && item.root !== rootFilter) {
        return false;
      }
      if (normalized && !item.searchableText.includes(normalized)) {
        return false;
      }
      return true;
    });
  }, [items, rootFilter, search]);

  const visibleItems = useMemo(() => filteredItems.slice(0, 240), [filteredItems]);
  const selectedAsset = useMemo(
    () => visibleItems.find((item) => item.id === selectedId) ?? visibleItems[0] ?? null,
    [selectedId, visibleItems],
  );

  const batchAssets = useMemo(() => items.filter((item) => selectedAssetIds.includes(item.id)), [items, selectedAssetIds]);

  useEffect(() => {
    if (!selectedAsset && visibleItems[0]) {
      setSelectedId(visibleItems[0].id);
    }
  }, [selectedAsset, visibleItems]);

  const canUseSelectedAsset = selectedAsset
    ? surface === 'cad'
      ? selectedAsset.supportedInCad
      : selectedAsset.supportedInDb
    : false;

  const semanticActionLabel = useMemo(() => {
    if (!selectedAsset) {
      return 'Apply semantic action';
    }

    switch (selectedAsset.semanticUsage) {
      case 'overlay':
        return 'Apply as overlay';
      case 'preset':
        return 'Apply as preset';
      case 'dental-library':
        return 'Activate dental library';
      default:
        return 'Open semantic action';
    }
  }, [selectedAsset]);

  useEffect(() => {
    if (!selectedAsset || !desktopRuntime) {
      setInsight(null);
      return;
    }

    const needsInsight = ['xml', 'json', 'stl', 'sdfa', 'drmsdfa', 'eoff', 'barprofile', 'partinfo', 'metadata', 'matrix4', 'dentalproject', 'rendereffect'].includes(selectedAsset.extension);
    if (!needsInsight) {
      setInsight(null);
      return;
    }

    let cancelled = false;
    setInsightLoading(true);
    void loadPublicAssetInsight(selectedAsset)
      .then((nextInsight) => {
        if (!cancelled) {
          setInsight(nextInsight);
        }
      })
      .catch((loadError) => {
        console.error(loadError);
        if (!cancelled) {
          setInsight(null);
        }
      })
      .finally(() => {
        if (!cancelled) {
          setInsightLoading(false);
        }
      });

    return () => {
      cancelled = true;
    };
  }, [desktopRuntime, selectedAsset]);

  const handleAction = async (mode: PublicAssetLibraryActionMode) => {
    if (!selectedAsset || !onAction) {
      return;
    }

    if (mode === 'cad' && !selectedAsset.supportedInCad) {
      return;
    }

    if (mode === 'db' && !selectedAsset.supportedInDb) {
      return;
    }

    if (mode === 'semantic' && selectedAsset.semanticUsage === 'reference') {
      return;
    }

    setPendingActionId(`${selectedAsset.id}:${mode}`);
    try {
      await onAction(selectedAsset, mode);
    } finally {
      setPendingActionId(null);
    }
  };

  const handleBatchAction = async (mode: PublicAssetLibraryActionMode) => {
    if (!onBatchAction || !batchAssets.length) {
      return;
    }

    setPendingActionId(`batch:${mode}`);
    try {
      await onBatchAction(batchAssets, mode);
      setSelectedAssetIds([]);
    } finally {
      setPendingActionId(null);
    }
  };

  const toggleBatchSelection = (assetId: string) => {
    setSelectedAssetIds((prev) => prev.includes(assetId) ? prev.filter((id) => id !== assetId) : [...prev, assetId]);
  };

  const usageCards = selectedAsset ? [
    {
      id: 'cad' as const,
      title: 'Usar en CAD',
      description: selectedAsset.supportedInCad ? 'Inserta el asset compatible al lienzo actual.' : 'No es un formato insertable en CAD todavía.',
      enabled: surface === 'cad' && selectedAsset.supportedInCad && Boolean(onAction),
      accent: 'text-text-primary',
    },
    {
      id: 'db' as const,
      title: 'Importar a DB',
      description: selectedAsset.supportedInDb ? 'Guarda este asset en el caso activo con su semántica.' : 'No conviene importarlo al caso como asset operativo.',
      enabled: surface === 'db' && selectedAsset.supportedInDb && Boolean(onAction),
      accent: 'text-text-primary',
    },
    {
      id: 'semantic' as const,
      title: semanticActionLabel,
      description: selectedAsset.semanticDescription,
      enabled: selectedAsset.semanticUsage !== 'reference' && Boolean(onAction),
      accent: 'text-text-display',
    },
  ] : [];

  return (
    <div className="rounded-2xl border border-border bg-card p-4">
      <div className="flex items-start justify-between gap-3">
        <div>
          <div className="flex items-center gap-2">
            <LibraryBig className="size-4 text-text-secondary" />
            <p className="text-xs uppercase text-text-secondary">{title}</p>
          </div>
          <p className="mt-1 text-sm text-text-primary text-pretty">{description}</p>
        </div>
        <Button variant="outline" size="icon" onClick={() => void refreshLibrary(true)} aria-label="Refresh asset library">
          <RefreshCcw className="size-4" />
        </Button>
      </div>

      {!desktopRuntime ? (
        <AssetLibraryPanelMessage
          className="mt-4"
          tone="dashed"
          title="Desktop runtime required"
          description="The full public asset catalog is available in the desktop runtime, where Tauri exposes filtered manifests for bundled resources."
        />
      ) : null}

      <div className="mt-4 grid gap-3">
        <div className="relative">
          <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-text-secondary" />
          <Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search library assets by name or folder" className="pl-9" />
        </div>

        <div className="flex flex-wrap gap-2">
          <AssetLibraryFilterChip active={rootFilter === 'all'} label="All roots" onClick={() => setRootFilter('all')} />
          {PUBLIC_ASSET_LIBRARY_ROOTS.filter((root) => availableRoots.includes(root.key)).map((root) => (
            <AssetLibraryFilterChip key={root.key} active={rootFilter === root.key} label={root.label} onClick={() => setRootFilter(root.key)} />
          ))}
        </div>

        <div className="flex flex-wrap items-center gap-2 text-xs text-text-secondary tabular-nums">
          <Badge className="border border-border bg-surface text-text-primary">{items.length} indexed</Badge>
          <Badge className="border border-border bg-surface text-text-primary">{filteredItems.length} matching</Badge>
          {moduleId ? <Badge className="border border-border bg-card text-text-primary">module {moduleId}</Badge> : null}
          {selectedAssetIds.length ? <Badge className="border border-border bg-card text-text-primary">{selectedAssetIds.length} selected</Badge> : null}
          {filteredItems.length > visibleItems.length ? (
            <Badge className="border border-border bg-card text-text-secondary">Showing first {visibleItems.length}</Badge>
          ) : null}
        </div>

        {onBatchAction && selectedAssetIds.length > 1 ? (
          <div className="flex flex-wrap gap-2 rounded-2xl border border-border bg-surface p-3">
            <Button size="sm" onClick={() => void handleBatchAction(surface === 'cad' ? 'cad' : 'db')} disabled={pendingActionId === `batch:${surface === 'cad' ? 'cad' : 'db'}`}>
              {surface === 'cad' ? 'Insert batch in CAD' : 'Import batch to DB'}
            </Button>
            <Button size="sm" variant="outline" onClick={() => void handleBatchAction('semantic')} disabled={pendingActionId === 'batch:semantic'}>
              Apply semantic batch
            </Button>
            <Button size="sm" variant="ghost" onClick={() => setSelectedAssetIds([])}>
              Clear selection
            </Button>
          </div>
        ) : null}
      </div>

      {error ? (
        <AssetLibraryPanelMessage className="mt-4" title="Library unavailable" description={error} actionLabel="Retry" onAction={() => void refreshLibrary(true)} />
      ) : null}

      {isLoading ? (
        <AssetLibraryPanelMessage className="mt-4" title="Loading public asset manifest…" description="Querying the Tauri manifest for the current module and building the searchable semantic catalog." />
      ) : null}

      {!isLoading && !error ? (
        <div className="mt-4 grid gap-4 xl:grid-cols-[1.1fr_0.9fr]">
          <ScrollArea className="h-[24rem] rounded-2xl border border-border bg-surface">
            <div className="grid gap-2 p-3">
              {visibleItems.length ? visibleItems.map((item) => (
                <AssetLibraryItemRow
                  key={item.id}
                  asset={item}
                  isBatchSelected={selectedAssetIds.includes(item.id)}
                  isSelected={selectedAsset?.id === item.id}
                  onSelect={() => setSelectedId(item.id)}
                  onToggleBatch={() => toggleBatchSelection(item.id)}
                  surface={surface}
                />
              )) : (
                <AssetLibraryPanelMessage tone="dashed" title="No assets match the current filters." description="Try another root or a broader search." />
              )}
            </div>
          </ScrollArea>

          <div className="grid gap-3 rounded-2xl border border-border bg-surface p-4">
            {selectedAsset ? (
              <>
                <div>
                  <p className="text-sm text-text-display">{selectedAsset.label}</p>
                  <p className="mt-1 truncate text-xs text-text-secondary">{selectedAsset.relativePath}</p>
                </div>

                <div className="rounded-2xl border border-border bg-card p-3">
                  <div className="flex items-center gap-2">
                    <Sparkles className="size-4 text-text-display" />
                    <p className="text-xs uppercase text-text-secondary">Semantic profile</p>
                  </div>
                  <p className="mt-2 text-sm text-text-primary">{selectedAsset.semanticLabel}</p>
                  <p className="mt-1 text-sm text-text-secondary text-pretty">{selectedAsset.semanticDescription}</p>
                  <div className="mt-3 flex flex-wrap gap-2">
                    {selectedAsset.autoTags.slice(0, 10).map((tag) => (
                      <Badge key={tag} className="border border-border bg-surface text-text-primary">{tag}</Badge>
                    ))}
                  </div>
                </div>

                {selectedAsset.kind === 'model' ? (
                  <LazyPublicAssetModelPreview asset={selectedAsset} />
                ) : selectedAsset.previewUrl && isPreviewablePublicAsset(selectedAsset) ? (
                  selectedAsset.kind === 'audio' ? (
                    <audio controls className="w-full" src={selectedAsset.previewUrl} />
                  ) : (
                    <div className="overflow-hidden rounded-2xl border border-border bg-card">
                      <img src={selectedAsset.previewUrl} alt={selectedAsset.label} className="h-56 w-full object-contain bg-black/5" />
                    </div>
                  )
                ) : (
                  <AssetLibraryPanelMessage
                    tone="dashed"
                    title={`Preview is not available for ${selectedAsset.extension || 'unknown'} assets.`}
                    description="The item is indexed and ready for workflow actions when supported."
                    className="flex h-56 items-center justify-center text-center"
                  />
                )}

                <div className="rounded-2xl border border-border bg-card p-3">
                  <div className="flex items-center gap-2">
                    <Wand2 className="size-4 text-text-secondary" />
                    <p className="text-xs uppercase text-text-secondary">Specialized preview</p>
                  </div>
                  {insightLoading ? (
                    <p className="mt-2 text-sm text-text-secondary">Inspecting file structure…</p>
                  ) : insight ? (
                    <div className="mt-3 grid gap-3">
                      <div>
                        <p className="text-sm text-text-primary">{insight.title}</p>
                        <div className="mt-2 grid gap-2 text-xs text-text-secondary tabular-nums">
                          {insight.details.map((detail) => (
                            <div key={detail.label} className="flex items-center justify-between gap-4 rounded-xl border border-border bg-surface px-3 py-2">
                              <span>{detail.label}</span>
                              <span className="text-right text-text-primary">{detail.value}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                      {insight.sample ? (
                        <pre className="max-h-32 overflow-auto rounded-xl border border-border bg-surface px-3 py-3 text-xs text-text-secondary">{insight.sample}</pre>
                      ) : null}
                    </div>
                  ) : (
                    <p className="mt-2 text-sm text-text-secondary">This asset uses the standard visual preview because no extra structural decoder is needed.</p>
                  )}
                </div>

                <div className="grid grid-cols-2 gap-2 text-xs text-text-secondary tabular-nums">
                  <div className="rounded-xl border border-border bg-card px-3 py-2">
                    <p className="uppercase">Root</p>
                    <p className="mt-1 text-text-primary">{selectedAsset.root}</p>
                  </div>
                  <div className="rounded-xl border border-border bg-card px-3 py-2">
                    <p className="uppercase">Kind</p>
                    <p className="mt-1 text-text-primary">{selectedAsset.kind}</p>
                  </div>
                </div>

                <div className="flex flex-wrap gap-2">
                  <Button variant="outline" size="sm" onClick={() => void openPathInSystem(selectedAsset.absolutePath)}>
                    <ExternalLink className="size-4" />
                    Open source
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => setWizardOpen(true)}>
                    <Wand2 className="size-4" />
                    Usage wizard
                  </Button>
                  <Button size="sm" onClick={() => void handleAction(surface === 'cad' ? 'cad' : 'db')} disabled={!canUseSelectedAsset || pendingActionId === `${selectedAsset.id}:${surface === 'cad' ? 'cad' : 'db'}` || !onAction}>
                    {useActionLabel}
                  </Button>
                </div>
              </>
            ) : (
              <AssetLibraryPanelMessage tone="dashed" title="Pick a library asset to inspect its name, path and integration options." />
            )}
          </div>
        </div>
      ) : null}

      <Sheet open={wizardOpen} onOpenChange={setWizardOpen}>
        <SheetContent side="right" className="w-full max-w-xl border-border bg-surface text-text-primary">
          <SheetHeader>
            <SheetTitle>Usage wizard</SheetTitle>
            <SheetDescription>
              Decide how to use this library asset in the current context.
            </SheetDescription>
          </SheetHeader>

          {selectedAsset ? (
            <div className="mt-6 grid gap-4">
              <div className="rounded-2xl border border-border bg-card p-4">
                <p className="text-sm text-text-display">{selectedAsset.label}</p>
                <p className="mt-1 text-sm text-text-secondary text-pretty">{selectedAsset.semanticDescription}</p>
                <div className="mt-3 flex flex-wrap gap-2">
                  {selectedAsset.autoTags.map((tag) => (
                    <Badge key={tag} className="border border-border bg-surface text-text-primary">{tag}</Badge>
                  ))}
                </div>
              </div>

              <div className="grid gap-3">
                {usageCards.map((card) => (
                  <AssetLibraryUsageCard
                    key={card.id}
                    title={card.title}
                    description={card.description}
                    accentClassName={card.accent}
                    disabled={!card.enabled}
                    pending={pendingActionId === `${selectedAsset.id}:${card.id}`}
                    onAction={() => void handleAction(card.id)}
                  />
                ))}

                <div className="rounded-2xl border border-border bg-card p-4">
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <p className="text-sm text-text-primary">Abrir como referencia</p>
                      <p className="mt-1 text-sm text-text-secondary text-pretty">Open the original file in the OS and inspect it outside the workspace.</p>
                    </div>
                    <Button size="sm" variant="outline" onClick={() => void openPathInSystem(selectedAsset.absolutePath)}>
                      Open reference
                    </Button>
                  </div>
                </div>
              </div>

              {insight ? (
                <div className="rounded-2xl border border-border bg-card p-4">
                  <p className="text-xs uppercase text-text-secondary">Interpretable preview</p>
                  <p className="mt-2 text-sm text-text-primary">{insight.title}</p>
                  <div className="mt-3 grid gap-2 text-xs text-text-secondary tabular-nums">
                    {insight.details.map((detail) => (
                      <div key={detail.label} className="flex items-center justify-between gap-4 rounded-xl border border-border bg-surface px-3 py-2">
                        <span>{detail.label}</span>
                        <span className="text-right text-text-primary">{detail.value}</span>
                      </div>
                    ))}
                  </div>
                </div>
              ) : null}
            </div>
          ) : null}
        </SheetContent>
      </Sheet>
    </div>
  );
}
