// Generated by Copilot
export const APP_ABOUT = {
  productName: 'TlantiCAD Dental Studio',
  studio: 'TlantiDental Studio',
  version: '0.1.0-alpha.1',
  bundleIdentifier: 'mx.tlantidentalstudio.tlanticad',
  buildUid: 'TCS-A0.1.0-20260403-MX-IXA-001',
  buildNumber: '2026.04.03-alpha.001',
  copyright: '© 2026 TlantiDental Studio. Todos los derechos reservados.',
  location: 'Ixtapaluca, Estado de México, México',
};
