// Generated by Copilot
export interface BackendIntegration {
  id: string;
  crateName: string;
  category: string;
  status: string;
  enabled: boolean;
  feature: string;
  route: string;
  notes: string;
  requiresSystemDependencies: boolean;
}

export interface BackendCatalog {
  appSurface: string;
  activeFeatureCount: number;
  experimentalFeatureCount: number;
  integrations: BackendIntegration[];
}

export interface GeometryProbe {
  centroid: [number, number, number];
  boundsMin: [number, number, number];
  boundsMax: [number, number, number];
  boundsSize: [number, number, number];
  nearestSampleIndex: number;
  route: string;
}

export interface WorkspaceFunction {
  name: string;
  signature: string;
  file: string;
  line: number;
  kind: string;
}

export interface WorkspaceCrateInfo {
  name: string;
  packageName: string;
  description?: string | null;
  relativePath: string;
  rustFileCount: number;
  publicFunctionCount: number;
  tauriCommandCount: number;
  topFunctions: WorkspaceFunction[];
}

export interface BackendWorkspaceCatalog {
  workspaceRoot: string;
  crateCount: number;
  rustFileCount: number;
  publicFunctionCount: number;
  tauriCommandCount: number;
  route: string;
  crates: WorkspaceCrateInfo[];
}

export interface SystemRuntimeReport {
  system: {
    os: {
      name: string;
      version: string;
      arch: string;
      hostname: string;
    };
    cpu: {
      brand: string;
      cores: number;
      frequencyMhz: number;
      usagePercent: number;
    };
    memory: {
      totalBytes: number;
      usedBytes: number;
      availableBytes: number;
      usagePercent: number;
    };
    gpus: Array<{
      name: string;
      vendor: string;
      backend: string;
      driverInfo: string;
      deviceType: string;
      features: string[];
    }>;
    disks: Array<{
      name: string;
      mountPoint: string;
      totalBytes: number;
      availableBytes: number;
      fileSystem: string;
    }>;
    capabilities: {
      webgpuSupported: boolean;
      vulkanSupported: boolean;
      metalSupported: boolean;
      dx12Supported: boolean;
      maxTextureSize: number;
      maxBufferSize: number;
      recommendedRenderQuality: 'low' | 'medium' | 'high' | 'ultra';
    };
  };
  aiWorkload: {
    workloadScores: {
      overall: number;
      dicomViewing: number;
      cbct3d: number;
      aiInference: number;
      pacsStorage: number;
      meshGeneration: number;
    };
    recommendedSettings: {
      renderQuality: string;
      maxTextureSize: number;
      dicomCacheMb: number;
      enableGpuInference: boolean;
      enable3dViewer: boolean;
      enableCbctViewer: boolean;
      maxConcurrentImports: number;
      thumbnailQuality: string;
    };
  };
  route: string;
}

export interface PythonRepoStatus {
  id: string;
  label: string;
  url: string;
  path?: string | null;
  present: boolean;
  supportedInputs: string[];
  notes: string;
}

export interface PythonWorkflowStatus {
  id: string;
  label: string;
  route: string;
  recommendedRepoId: string;
  supportedInputs: string[];
  ready: boolean;
  notes: string;
}

export interface PythonBridgeStatus {
  pyo3Enabled: boolean;
  bridgeMode: string;
  pythonAvailable: boolean;
  pythonVersion?: string | null;
  pythonExecutable?: string | null;
  manifestPath?: string | null;
  pythonHome?: string | null;
  supportPaths: Record<string, string>;
  repos: PythonRepoStatus[];
  workflows: PythonWorkflowStatus[];
  notes: string[];
}

export interface EncryptedPayload {
  algorithm: string;
  keyDerivation: string;
  nonceBase64: string;
  ciphertextBase64: string;
}

const browserFallbackCatalog: BackendCatalog = {
  appSurface: 'Workspace / Settings / Backend Integrations',
  activeFeatureCount: 5,
  experimentalFeatureCount: 5,
  integrations: [
    {
      id: 'mesh-csg',
      crateName: 'csgrs',
      category: 'mesh-processing',
      status: 'ready',
      enabled: true,
      feature: 'backend-csg',
      route: 'workspace/backend/mesh-csg',
      notes: 'Boolean CSG pipeline configured for Rust backend integration.',
      requiresSystemDependencies: false,
    },
    {
      id: 'dicom-core',
      crateName: 'dicom + dicom-object',
      category: 'dicom',
      status: 'ready',
      enabled: true,
      feature: 'backend-dicom',
      route: 'workspace/backend/dicom',
      notes: 'DICOM metadata route available in desktop runtime.',
      requiresSystemDependencies: false,
    },
    {
      id: 'vision-opencv',
      crateName: 'opencv',
      category: 'vision',
      status: 'planned',
      enabled: false,
      feature: 'backend-vision',
      route: 'workspace/backend/vision',
      notes: 'Feature-gated until native OpenCV provisioning is added.',
      requiresSystemDependencies: true,
    },
    {
      id: 'python-sidecar',
      crateName: 'python3 + JSON sidecar',
      category: 'python-runtime',
      status: 'experimental',
      enabled: true,
      feature: 'runtime-default',
      route: 'workspace/backend/python/sidecar',
      notes: 'Current route for external dental Python tooling such as mesh segmentation sidecars.',
      requiresSystemDependencies: true,
    },
    {
      id: 'python-pyo3',
      crateName: 'pyo3',
      category: 'python-runtime',
      status: 'optional',
      enabled: false,
      feature: 'backend-python-embed',
      route: 'workspace/backend/python/pyo3',
      notes: 'Optional embedded Python bridge enabled only in Python-aware desktop builds.',
      requiresSystemDependencies: true,
    },
    {
      id: 'brep-occt-wasm-webview',
      crateName: 'OCCT WASM + Tauri WebView',
      category: 'industrial-cad-preview',
      status: 'planned',
      enabled: false,
      feature: 'frontend-occt-wasm',
      route: 'workspace/backend/occt-wasm-webview',
      notes: 'Offline WebView-hosted OCCT preview path for B-Rep experiments, STEP/IGES inspection and docs demos. It exchanges handles/manifests, not full mesh buffers over JSON IPC.',
      requiresSystemDependencies: false,
    },
  ],
};

const browserFallbackProbe: GeometryProbe = {
  centroid: [-0.125, 1.875, 2.625],
  boundsMin: [-12, -6, -4],
  boundsMax: [8, 7.5, 9],
  boundsSize: [20, 13.5, 13],
  nearestSampleIndex: 3,
  route: 'workspace/backend/geometry/probe',
};

const browserFallbackWorkspaceCatalog: BackendWorkspaceCatalog = {
  workspaceRoot: 'apps/desktop/src-tauri/crates',
  crateCount: 3,
  rustFileCount: 8,
  publicFunctionCount: 12,
  tauriCommandCount: 0,
  route: 'workspace/backend/workspace-crates',
  crates: [
    {
      name: 'tlanticad-tensor',
      packageName: 'tlanticad-tensor',
      description: 'Tensor primitives and CPU-first inference helpers for dental workloads.',
      relativePath: 'tlanticad-tensor',
      rustFileCount: 2,
      publicFunctionCount: 4,
      tauriCommandCount: 0,
      topFunctions: [
        {
          name: 'estimate_bone_density',
          signature: 'pub fn estimate_bone_density(&self, hu_values: &[f32]) -> BoneDensityResult {',
          file: 'src/inference.rs',
          line: 84,
          kind: 'fn',
        },
      ],
    },
    {
      name: 'system-info',
      packageName: 'system-info',
      description: 'Desktop runtime machine report and GPU capability detection.',
      relativePath: 'system-info',
      rustFileCount: 3,
      publicFunctionCount: 5,
      tauriCommandCount: 0,
      topFunctions: [],
    },
    {
      name: 'tlanticad-rendering',
      packageName: 'tlanticad-rendering',
      description: 'Rendering-oriented crate reserved for future CAD viewport migration.',
      relativePath: 'tlanticad-rendering',
      rustFileCount: 3,
      publicFunctionCount: 3,
      tauriCommandCount: 0,
      topFunctions: [],
    },
  ],
};

const browserFallbackRuntimeReport: SystemRuntimeReport = {
  system: {
    os: {
      name: 'Browser fallback',
      version: 'n/a',
      arch: 'unknown',
      hostname: 'localhost',
    },
    cpu: {
      brand: 'Browser sandbox',
      cores: 0,
      frequencyMhz: 0,
      usagePercent: 0,
    },
    memory: {
      totalBytes: 0,
      usedBytes: 0,
      availableBytes: 0,
      usagePercent: 0,
    },
    gpus: [],
    disks: [],
    capabilities: {
      webgpuSupported: false,
      vulkanSupported: false,
      metalSupported: false,
      dx12Supported: false,
      maxTextureSize: 0,
      maxBufferSize: 0,
      recommendedRenderQuality: 'low',
    },
  },
  aiWorkload: {
    workloadScores: {
      overall: 0,
      dicomViewing: 0,
      cbct3d: 0,
      aiInference: 0,
      pacsStorage: 0,
      meshGeneration: 0,
    },
    recommendedSettings: {
      renderQuality: 'low',
      maxTextureSize: 0,
      dicomCacheMb: 0,
      enableGpuInference: false,
      enable3dViewer: false,
      enableCbctViewer: false,
      maxConcurrentImports: 1,
      thumbnailQuality: 'low',
    },
  },
  route: 'workspace/backend/system/runtime-report',
};

const browserFallbackPythonBridgeStatus: PythonBridgeStatus = {
  pyo3Enabled: false,
  bridgeMode: 'external-python',
  pythonAvailable: false,
  pythonVersion: null,
  pythonExecutable: null,
  manifestPath: null,
  pythonHome: null,
  supportPaths: {},
  repos: [],
  workflows: [],
  notes: ['Python runtime status is only available inside the desktop runtime.'],
};

async function safeInvoke<T>(command: string, args?: Record<string, unknown>): Promise<T> {
  try {
    const tauriCore = await import('@tauri-apps/api/core');
    return await tauriCore.invoke<T>(command, args);
  } catch (error) {
    throw error;
  }
}

export async function loadBackendCatalog(): Promise<BackendCatalog> {
  try {
    return await safeInvoke<BackendCatalog>('get_backend_integration_catalog');
  } catch {
    return browserFallbackCatalog;
  }
}

export async function loadGeometryProbe(): Promise<GeometryProbe> {
  try {
    return await safeInvoke<GeometryProbe>('run_backend_geometry_probe');
  } catch {
    return browserFallbackProbe;
  }
}

export async function loadBackendWorkspaceCatalog(): Promise<BackendWorkspaceCatalog> {
  try {
    return await safeInvoke<BackendWorkspaceCatalog>('inspect_backend_workspace');
  } catch {
    return browserFallbackWorkspaceCatalog;
  }
}

export async function loadSystemRuntimeReport(): Promise<SystemRuntimeReport> {
  try {
    return await safeInvoke<SystemRuntimeReport>('get_system_runtime_report');
  } catch {
    return browserFallbackRuntimeReport;
  }
}

export async function loadPythonBridgeStatus(): Promise<PythonBridgeStatus> {
  try {
    return await safeInvoke<PythonBridgeStatus>('get_python_bridge_status');
  } catch {
    return browserFallbackPythonBridgeStatus;
  }
}

export async function compressToolkitPayload(payload: string): Promise<string> {
  return safeInvoke<string>('compress_text_lzma', { payload });
}

export async function decompressToolkitPayload(payloadBase64: string): Promise<string> {
  return safeInvoke<string>('decompress_text_lzma', { payloadBase64 });
}

export async function encryptToolkitPayload(payload: string, passphrase: string): Promise<EncryptedPayload> {
  return safeInvoke<EncryptedPayload>('encrypt_text_payload', { payload, passphrase });
}

export async function decryptToolkitPayload(ciphertextBase64: string, nonceBase64: string, passphrase: string): Promise<string> {
  return safeInvoke<string>('decrypt_text_payload', { ciphertextBase64, nonceBase64, passphrase });
}
