// Generated by Copilot
export type DentalRestorationType =
  | 'anatomic-crown'
  | 'anatomic-coping'
  | 'veneer'
  | 'inlay-onlay'
  | 'pontic'
  | 'implant-restoration'
  | 'adjacent-tooth'
  | 'antagonist'
  | 'omit-in-bridge';

export type DentalProductionMethod =
  | 'inhouse-milling'
  | 'five-axis-milling'
  | 'laser-melting'
  | 'printing'
  | 'outsourced-center';

export type DentalMaterialType =
  | 'zirconia'
  | 'zirconia-multilayer'
  | 'pmma'
  | 'wax'
  | 'np-metal'
  | 'titanium'
  | '3d-print'
  | 'lithium-disilicate'
  | 'composite';

export type DentalImplantMode = 'none' | 'custom-abutment' | 'screw-retained' | 'stock-abutment';

export interface DentalConnectorCandidate {
  key: string;
  fromTooth: string;
  toTooth: string;
  span: string[];
  active: boolean;
  canConnect: boolean;
  auto: boolean;
  reason?: string;
}

export interface DentalOption<T extends string> {
  value: T;
  label: string;
  color?: string;
  description?: string;
}

export const RESTORATION_OPTIONS: DentalOption<DentalRestorationType>[] = [
  { value: 'anatomic-crown', label: 'Anatomic crown', color: '#ffffff' },
  { value: 'anatomic-coping', label: 'Anatomic coping', color: '#d4a843' },
  { value: 'veneer', label: 'Veneer', color: '#5b9bf6' },
  { value: 'inlay-onlay', label: 'Inlay / Onlay', color: '#22c55e' },
  { value: 'pontic', label: 'Pontic', color: '#f97316' },
  { value: 'implant-restoration', label: 'Implant restoration', color: '#d71921' },
  { value: 'adjacent-tooth', label: 'Adjacent tooth', color: '#8b8b8b' },
  { value: 'antagonist', label: 'Antagonist', color: '#d71921' },
  { value: 'omit-in-bridge', label: 'Omit in bridge', color: '#64748b' },
];

export const MATERIAL_OPTIONS: DentalOption<DentalMaterialType>[] = [
  { value: 'zirconia', label: 'Zirconia' },
  { value: 'zirconia-multilayer', label: 'Zirconia multilayer' },
  { value: 'pmma', label: 'PMMA / Acrylic' },
  { value: 'wax', label: 'Wax' },
  { value: 'np-metal', label: 'NP Metal / CoCr' },
  { value: 'titanium', label: 'Titanium' },
  { value: '3d-print', label: '3D Print' },
  { value: 'lithium-disilicate', label: 'Lithium disilicate' },
  { value: 'composite', label: 'Composite' },
];

export const PRODUCTION_OPTIONS: DentalOption<DentalProductionMethod>[] = [
  { value: 'inhouse-milling', label: 'In-house milling' },
  { value: 'five-axis-milling', label: '5-axis milling' },
  { value: 'laser-melting', label: 'Laser melting' },
  { value: 'printing', label: 'Printing' },
  { value: 'outsourced-center', label: 'Outsourced center' },
];

export const IMPLANT_MODE_OPTIONS: DentalOption<DentalImplantMode>[] = [
  { value: 'none', label: 'No implant' },
  { value: 'custom-abutment', label: 'Custom abutment' },
  { value: 'screw-retained', label: 'Screw retained' },
  { value: 'stock-abutment', label: 'On stock abutment' },
];

export function getRestorationColor(restorationType?: DentalRestorationType, antagonist?: boolean) {
  if (antagonist || restorationType === 'antagonist') {
    return '#d71921';
  }

  return RESTORATION_OPTIONS.find((option) => option.value === restorationType)?.color ?? '#ffffff';
}

export function getRestorationLabel(restorationType?: DentalRestorationType) {
  return RESTORATION_OPTIONS.find((option) => option.value === restorationType)?.label ?? 'Anatomic crown';
}

const CONNECTABLE_RESTORATIONS = new Set<DentalRestorationType>([
  'anatomic-crown',
  'anatomic-coping',
  'pontic',
  'implant-restoration',
  'veneer',
  'inlay-onlay',
]);

export const FDI_VISIBLE_ROWS = [
  ['18', '17', '16', '15', '14', '13', '12', '11'],
  ['21', '22', '23', '24', '25', '26', '27', '28'],
  ['48', '47', '46', '45', '44', '43', '42', '41'],
  ['31', '32', '33', '34', '35', '36', '37', '38'],
] as const;

const TOOTH_ORDER: Map<string, number> = new Map(FDI_VISIBLE_ROWS.flat().map((tooth, index) => [tooth, index]));

export function getToothOrderIndex(toothNumber: string) {
  return TOOTH_ORDER.get(toothNumber) ?? Number.MAX_SAFE_INTEGER;
}

export function buildConnectorKey(fromTooth: string, toTooth: string) {
  const ordered = [fromTooth, toTooth].sort((left, right) => getToothOrderIndex(left) - getToothOrderIndex(right));
  return `${ordered[0]}__${ordered[1]}`;
}

function isConnectable(restorationType?: DentalRestorationType) {
  return restorationType ? CONNECTABLE_RESTORATIONS.has(restorationType) : false;
}

function isBridgePlaceholder(restorationType?: DentalRestorationType) {
  return restorationType === 'omit-in-bridge';
}

export function getDentalConnectorCandidates(
  toothMap: Record<string, {
    selected: boolean;
    antagonist: boolean;
    restorationType?: DentalRestorationType;
    material?: DentalMaterialType;
  }>,
  connectorOverrides: Record<string, boolean> = {},
) {
  const connectors: DentalConnectorCandidate[] = [];

  for (const row of FDI_VISIBLE_ROWS) {
    for (let startIndex = 0; startIndex < row.length; startIndex += 1) {
      const fromTooth = row[startIndex];
      const fromState = toothMap[`tooth-${fromTooth}`];

      if (!fromState?.selected || fromState.antagonist || !isConnectable(fromState.restorationType)) {
        continue;
      }

      const omittedSpan: string[] = [];

      for (let nextIndex = startIndex + 1; nextIndex < row.length; nextIndex += 1) {
        const candidateTooth = row[nextIndex];
        const candidateState = toothMap[`tooth-${candidateTooth}`];

        if (!candidateState?.selected) {
          break;
        }

        if (candidateState.antagonist) {
          break;
        }

        if (isBridgePlaceholder(candidateState.restorationType)) {
          omittedSpan.push(candidateTooth);
          continue;
        }

        if (!isConnectable(candidateState.restorationType)) {
          break;
        }

        const materialMismatch = Boolean(fromState.material && candidateState.material && fromState.material !== candidateState.material);
        const key = buildConnectorKey(fromTooth, candidateTooth);
        const auto = omittedSpan.length > 0 || fromState.restorationType === 'pontic' || candidateState.restorationType === 'pontic';
        const canConnect = !materialMismatch;
        const override = connectorOverrides[key];

        connectors.push({
          key,
          fromTooth,
          toTooth: candidateTooth,
          span: [...omittedSpan],
          auto,
          canConnect,
          active: canConnect ? (override ?? auto) : false,
          reason: materialMismatch ? 'Material mismatch' : omittedSpan.length > 0 ? 'Bridge span via omit in bridge' : auto ? 'Auto bridge connector' : 'Manual connector available',
        });

        break;
      }
    }
  }

  return connectors;
}
