// Generated by Copilot
import type { FileData } from '@/types';

export interface DentalAiWorkflowHint {
  id: 'cbct-dicom-segmentation' | 'pxi-panoramic-segmentation' | 'stl-vtk-inapp-segmentation' | 'obj-tooth-labeling' | 'unknown';
  label: string;
  recommendedTool: string;
  supportedInputs: string[];
  executableInApp: boolean;
  notes: string;
}

function getExtension(file: Pick<FileData, 'name' | 'sourcePath'>) {
  const candidate = file.sourcePath ?? file.name;
  const extension = candidate.split('.').pop()?.toLowerCase();
  return extension ? `.${extension}` : null;
}

export function detectDentalAiWorkflow(file: FileData | null): DentalAiWorkflowHint | null {
  if (!file) {
    return null;
  }

  const extension = getExtension(file);

  if (file.type === 'DICOM') {
    return {
      id: 'cbct-dicom-segmentation',
      label: 'CBCT / DICOM segmentation',
      recommendedTool: 'Dentist-SOTA DICOM sanitizer + SlicerDentalSegmentator / Dentist-SOTA CBCT R2U-Net',
      supportedInputs: ['.dcm', '.dicom', '.ima'],
      executableInApp: true,
      notes: 'Use a safe DICOM ingestion step first, then choose between the stable Slicer vendor path and the new Dentist-SOTA research route for STS-Tooth aligned CBCT processing.',
    };
  }

  if (file.type === 'IMAGE' && ['.png', '.jpg', '.jpeg', '.webp'].includes(extension ?? '')) {
    return {
      id: 'pxi-panoramic-segmentation',
      label: 'Panoramic PXI segmentation',
      recommendedTool: 'Dentist-SOTA PXI R2U-Net',
      supportedInputs: ['.png', '.jpg', '.jpeg', '.webp'],
      executableInApp: true,
      notes: 'Best suited for 2D panoramic radiographs. TlantiCAD can create the clinical job now; inference remains gated until a licensed/checksummed model artifact is installed.',
    };
  }

  if (file.type === 'MODEL' && (extension === '.stl' || extension === '.vtk')) {
    return {
      id: 'stl-vtk-inapp-segmentation',
      label: 'IOS mesh segmentation',
      recommendedTool: 'DentalModelSeg sidecar',
      supportedInputs: ['.stl', '.vtk'],
      executableInApp: true,
      notes: 'This is the current in-app Python route exposed in the Properties panel for direct desktop execution.',
    };
  }

  if (file.type === 'MODEL' && extension === '.obj') {
    return {
      id: 'obj-tooth-labeling',
      label: 'OBJ tooth labeling',
      recommendedTool: 'ToothGroupNetwork',
      supportedInputs: ['.obj'],
      executableInApp: false,
      notes: 'Best suited for labeled upper/lower OBJ workflows and checkpoint-driven mesh inference.',
    };
  }

  return {
    id: 'unknown',
    label: 'No specialized AI route detected',
    recommendedTool: 'Manual review',
    supportedInputs: extension ? [extension] : [],
    executableInApp: false,
    notes: 'This asset does not currently match a Python dental workflow configured in TlantiCAD.',
  };
}
