// Generated by Copilot
import type { DentalMaterialKey, DentalMaterialOverride, FileData } from '@/types';

export interface DentalMaterialProfile {
  key: DentalMaterialKey;
  label: string;
  color: string;
  metalness: number;
  roughness: number;
  clearcoat: number;
  clearcoatRoughness: number;
  transmission?: number;
  thickness?: number;
  ior?: number;
  attenuationColor?: string;
  attenuationDistance?: number;
  opacity?: number;
}

const DENTAL_MATERIALS: Record<DentalMaterialKey, DentalMaterialProfile> = {
  enamel: {
    key: 'enamel',
    label: 'Enamel',
    color: '#e2d8ca',
    metalness: 0.02,
    roughness: 0.36,
    clearcoat: 0.42,
    clearcoatRoughness: 0.28,
    transmission: 0.08,
    thickness: 0.6,
    ior: 1.52,
    attenuationColor: '#f4eadf',
    attenuationDistance: 1.6,
  },
  dentin: {
    key: 'dentin',
    label: 'Dentin',
    color: '#c89d73',
    metalness: 0.01,
    roughness: 0.58,
    clearcoat: 0.16,
    clearcoatRoughness: 0.54,
    transmission: 0.03,
    thickness: 0.4,
    ior: 1.5,
    attenuationColor: '#dfb68d',
    attenuationDistance: 1.1,
  },
  gingiva: {
    key: 'gingiva',
    label: 'Gingiva',
    color: '#c4877d',
    metalness: 0.0,
    roughness: 0.72,
    clearcoat: 0.08,
    clearcoatRoughness: 0.72,
    transmission: 0.02,
    thickness: 0.35,
    ior: 1.38,
    attenuationColor: '#d99a90',
    attenuationDistance: 0.9,
  },
  zirconia: {
    key: 'zirconia',
    label: 'Zirconia',
    color: '#f3f1eb',
    metalness: 0.0,
    roughness: 0.22,
    clearcoat: 0.52,
    clearcoatRoughness: 0.18,
    transmission: 0.01,
    thickness: 0.2,
    ior: 1.76,
    attenuationColor: '#ffffff',
    attenuationDistance: 2.5,
  },
  metal: {
    key: 'metal',
    label: 'Titanium / Metal',
    color: '#b9bec6',
    metalness: 0.92,
    roughness: 0.24,
    clearcoat: 0.1,
    clearcoatRoughness: 0.2,
  },
  pmma: {
    key: 'pmma',
    label: 'PMMA',
    color: '#f4e9dd',
    metalness: 0.01,
    roughness: 0.34,
    clearcoat: 0.32,
    clearcoatRoughness: 0.22,
    transmission: 0.06,
    thickness: 0.4,
    ior: 1.49,
    attenuationColor: '#f6efe6',
    attenuationDistance: 1.8,
  },
  'guide-resin': {
    key: 'guide-resin',
    label: 'Guide Resin',
    color: '#d9eef5',
    metalness: 0.0,
    roughness: 0.18,
    clearcoat: 0.7,
    clearcoatRoughness: 0.08,
    transmission: 0.38,
    thickness: 1.2,
    ior: 1.47,
    attenuationColor: '#c7edf7',
    attenuationDistance: 0.75,
    opacity: 0.92,
  },
  'scan-default': {
    key: 'scan-default',
    label: 'Neutral scan',
    color: '#d5ccbf',
    metalness: 0.03,
    roughness: 0.46,
    clearcoat: 0.26,
    clearcoatRoughness: 0.34,
    transmission: 0.04,
    thickness: 0.45,
    ior: 1.46,
    attenuationColor: '#ece2d7',
    attenuationDistance: 1.5,
  },
};

export const DENTAL_MATERIAL_OPTIONS: Array<{ value: DentalMaterialOverride; label: string }> = [
  { value: 'auto', label: 'Auto' },
  { value: 'enamel', label: 'Enamel' },
  { value: 'dentin', label: 'Dentin' },
  { value: 'gingiva', label: 'Gingiva' },
  { value: 'zirconia', label: 'Zirconia' },
  { value: 'metal', label: 'Metal' },
  { value: 'pmma', label: 'PMMA' },
  { value: 'guide-resin', label: 'Guide Resin' },
  { value: 'scan-default', label: 'Neutral Scan' },
];

export function getDentalMaterialProfile(key: DentalMaterialKey) {
  return DENTAL_MATERIALS[key];
}

function buildMaterialSearchText(file: FileData) {
  return [
    file.name,
    file.sourcePath,
    file.sourceRelativePath,
    file.sourceRoot,
    file.semanticUsage,
    ...(file.semanticTags ?? []),
  ]
    .filter(Boolean)
    .join(' ')
    .toLowerCase();
}

function matches(searchText: string, patterns: RegExp[]) {
  return patterns.some((pattern) => pattern.test(searchText));
}

export function resolveDentalMaterialProfile(file: FileData): DentalMaterialProfile {
  if (file.dentalMaterialOverride && file.dentalMaterialOverride !== 'auto') {
    return getDentalMaterialProfile(file.dentalMaterialOverride);
  }

  const searchText = buildMaterialSearchText(file);

  if (matches(searchText, [/gingiva/, /gum/, /enc[ií]a/, /soft.?tissue/])) {
    return DENTAL_MATERIALS.gingiva;
  }

  if (matches(searchText, [/implant/, /titan/, /titanium/, /metal/, /bracket/, /wire/, /archwire/, /abutment/, /analog/, /screw/])) {
    return DENTAL_MATERIALS.metal;
  }

  if (matches(searchText, [/guide/, /surgical.?guide/, /splint/, /tray/, /resin/])) {
    return DENTAL_MATERIALS['guide-resin'];
  }

  if (matches(searchText, [/pmma/, /provisional/, /temporary/, /temp/])) {
    return DENTAL_MATERIALS.pmma;
  }

  if (matches(searchText, [/zirconia/, /zirconium/, /\bzr\b/])) {
    return DENTAL_MATERIALS.zirconia;
  }

  if (matches(searchText, [/dentin/, /dentina/, /core/])) {
    return DENTAL_MATERIALS.dentin;
  }

  if (matches(searchText, [/enamel/, /esmalte/, /scan/, /upper/, /lower/, /maxilla/, /mandible/, /tooth/, /teeth/, /diente/, /crown/, /dental-library/, /teeth-library/])) {
    return DENTAL_MATERIALS.enamel;
  }

  return DENTAL_MATERIALS['scan-default'];
}
