// Generated by Copilot
export type PendingCadImportPayload =
  | {
    source: 'launcher-dicom';
    paths: string[];
    directoryPath?: undefined;
    files?: undefined;
  }
  | {
    source: 'launcher-dicom';
    files: File[];
    paths?: undefined;
    directoryPath?: undefined;
  }
  | {
    source: 'launcher-dicom';
    directoryPath: string;
    files?: undefined;
    paths?: undefined;
  };

let pendingCadImport: PendingCadImportPayload | null = null;

export function setPendingCadImport(payload: PendingCadImportPayload) {
  pendingCadImport = payload;
}

export function consumePendingCadImport() {
  const currentPayload = pendingCadImport;
  pendingCadImport = null;
  return currentPayload;
}

export function peekPendingCadImport() {
  return pendingCadImport;
}