// Generated by Copilot
import type { PublicAssetLibraryItem } from '@/lib/public-asset-library';
import type { TlantiToothState } from '@/stores/tlantidb-case-store';

export interface DentalLibraryDefaults {
  patch: Partial<TlantiToothState>;
  title: string;
  notes: string[];
}

function hasTag(asset: PublicAssetLibraryItem, ...tags: string[]) {
  return tags.some((tag) => asset.autoTags.includes(tag) || asset.semanticFamilies.includes(tag));
}

export function inferDentalLibraryDefaults(asset: PublicAssetLibraryItem): DentalLibraryDefaults {
  const patch: Partial<TlantiToothState> = {
    selected: true,
    antagonist: false,
    condition: 'anatomic-crown',
    restorationType: 'anatomic-crown',
    material: 'zirconia-multilayer',
    shade: 'A1',
    productionMethod: 'five-axis-milling',
    implantMode: 'none',
  };
  const notes: string[] = [];
  let title = 'General tooth library';

  if (hasTag(asset, 'smilers', 'smile-design')) {
    patch.restorationType = 'veneer';
    patch.condition = 'veneer';
    patch.material = 'lithium-disilicate';
    patch.shade = 'BL1';
    title = 'Smile design veneer library';
    notes.push('Seeds veneer workflows and bright esthetic shades.');
  }

  if (hasTag(asset, 'implant')) {
    patch.restorationType = 'implant-restoration';
    patch.condition = 'implant-restoration';
    patch.material = 'titanium';
    patch.implantMode = hasTag(asset, 'screw-retained') ? 'screw-retained' : 'custom-abutment';
    title = 'Implant restoration library';
    notes.push('Optimized for implant restoration and titanium defaults.');
  }

  if (hasTag(asset, 'pontic')) {
    patch.restorationType = 'pontic';
    patch.condition = 'pontic';
    title = 'Pontic library';
    notes.push('Designed for bridge spans and pontic setup.');
  }

  if (hasTag(asset, 'bar-design', 'articulator')) {
    patch.productionMethod = 'five-axis-milling';
    patch.material = 'titanium';
    title = hasTag(asset, 'articulator') ? 'Articulator-driven library' : 'Bar design library';
    notes.push('Prefers milling-oriented workflows and rigid materials.');
  }

  if (hasTag(asset, 'materials')) {
    notes.push('Material cues were found in the library asset name/path.');
    if (asset.relativePath.toLowerCase().includes('pmma')) patch.material = 'pmma';
    if (asset.relativePath.toLowerCase().includes('wax')) patch.material = 'wax';
    if (asset.relativePath.toLowerCase().includes('composite')) patch.material = 'composite';
    if (asset.relativePath.toLowerCase().includes('lithium')) patch.material = 'lithium-disilicate';
    if (asset.relativePath.toLowerCase().includes('zirconia')) patch.material = 'zirconia-multilayer';
  }

  if (hasTag(asset, 'teeth-library') && !notes.length) {
    notes.push('Applies a balanced crown workflow as the default entry point.');
  }

  return {
    patch,
    title,
    notes,
  };
}
