// Generated by Copilot
import type { ToolMode } from '@/types';
import type { PublicAssetLibraryItem } from '@/lib/public-asset-library';

export interface CadPresetEffect {
  activeTool?: ToolMode;
  gridVisible?: boolean;
  snapValue?: number | null;
  transformSpace?: 'local' | 'world';
  controlScheme?: 'standard' | 'cad';
  preferredOverlayAlignment?: 'front' | 'plane';
  summary: string;
}

function hasTag(asset: PublicAssetLibraryItem, ...tags: string[]) {
  return tags.some((tag) => asset.autoTags.includes(tag) || asset.semanticFamilies.includes(tag));
}

export function inferCadPresetEffect(asset: PublicAssetLibraryItem): CadPresetEffect {
  if (hasTag(asset, 'cephalometry', 'overlay')) {
    return {
      activeTool: 'MEASURE',
      gridVisible: false,
      snapValue: 1,
      transformSpace: 'world',
      controlScheme: 'cad',
      preferredOverlayAlignment: 'front',
      summary: 'Measurement-oriented overlay preset applied.',
    };
  }

  if (hasTag(asset, 'implant')) {
    return {
      activeTool: 'MOVE',
      gridVisible: true,
      snapValue: 0.5,
      transformSpace: 'world',
      controlScheme: 'cad',
      preferredOverlayAlignment: 'plane',
      summary: 'Implant planning preset applied with world snapping.',
    };
  }

  if (hasTag(asset, 'articulator', 'occlusion')) {
    return {
      activeTool: 'ROTATE',
      gridVisible: true,
      snapValue: 1,
      transformSpace: 'world',
      controlScheme: 'cad',
      preferredOverlayAlignment: 'plane',
      summary: 'Articulator preset applied for plane-aligned rotations.',
    };
  }

  if (hasTag(asset, 'materials', 'manufacturing', 'nesting')) {
    return {
      activeTool: 'SELECT',
      gridVisible: true,
      snapValue: 0.25,
      transformSpace: 'local',
      controlScheme: 'cad',
      preferredOverlayAlignment: 'front',
      summary: 'Manufacturing/material preset applied for fine snapping.',
    };
  }

  return {
    activeTool: 'SELECT',
    gridVisible: true,
    snapValue: null,
    transformSpace: 'local',
    controlScheme: 'cad',
    preferredOverlayAlignment: 'front',
    summary: 'General CAD preset applied.',
  };
}
