// Generated by Copilot
import { convertFileSrc } from '@tauri-apps/api/core';

import {
  ASSET_LIBRARY_ROOTS as CLINICAL_ASSET_LIBRARY_ROOTS,
  listAssetPlacementsForModule,
  type AssetPlacementDefinition,
  type TlantiModuleId,
} from '@/core';
import { isTauriRuntime } from '@/platform/desktop-system';
import { derivePublicAssetSemanticProfile, type PublicAssetSemanticUsage } from '@/lib/public-asset-semantics';

export type PublicAssetLibrarySurface = 'cad' | 'db';
export type PublicAssetRoot = 'Bitmaps' | 'Graphics' | 'icons' | 'images' | 'LayoutPhantoms' | 'PredefinedElements' | 'library';
export type PublicAssetKind = 'image' | 'vector' | 'audio' | 'model' | 'xml' | 'preset' | 'effect' | 'binary' | 'document';

export interface PublicAssetLibraryRootMeta {
  key: PublicAssetRoot;
  label: string;
  description: string;
}

export interface PublicAssetLibraryItem {
  id: string;
  root: PublicAssetRoot;
  name: string;
  label: string;
  extension: string;
  kind: PublicAssetKind;
  relativePath: string;
  rootRelativePath: string;
  absolutePath: string;
  bytes: number | null;
  previewUrl: string | null;
  supportedInCad: boolean;
  supportedInDb: boolean;
  semanticUsage: PublicAssetSemanticUsage;
  semanticLabel: string;
  semanticDescription: string;
  autoTags: string[];
  semanticFamilies: string[];
  searchableText: string;
}

export const PUBLIC_ASSET_LIBRARY_ROOTS: PublicAssetLibraryRootMeta[] = [
  { key: 'Bitmaps', label: 'Bitmaps', description: 'Bitmap artwork and operation visuals.' },
  { key: 'Graphics', label: 'Graphics', description: 'CAD, Workspace and workflow UI graphics.' },
  { key: 'icons', label: 'Icons', description: 'Operational icons, scans, dental share and module iconography.' },
  { key: 'images', label: 'Images', description: 'Auxiliary app images and material previews.' },
  { key: 'LayoutPhantoms', label: 'Layout phantoms', description: 'Layout phantom references and scene overlays.' },
  { key: 'PredefinedElements', label: 'Predefined elements', description: 'Ceph landmarks, cards, XML presets and instructional elements.' },
  { key: 'library', label: 'Library', description: 'Dental CAD libraries, prosthetic presets, controls and visualizers.' },
];

const IMAGE_EXTENSIONS = new Set(['png', 'jpg', 'jpeg', 'webp', 'avif']);
const VECTOR_EXTENSIONS = new Set(['svg']);
const AUDIO_EXTENSIONS = new Set(['mp3', 'wav']);
const MODEL_EXTENSIONS = new Set(['stl', 'obj', 'ply', 'glb', 'gltf', 'off']);
const XML_EXTENSIONS = new Set(['xml', 'json']);
const PRESET_EXTENSIONS = new Set(['sdfa', 'drmsdfa', 'eoff', 'barprofile', 'partinfo', 'metadata', 'matrix4', 'dentalproject']);
const EFFECT_EXTENSIONS = new Set(['rendereffect']);
const BINARY_EXTENSIONS = new Set(['dll', 'db']);

interface PublicAssetManifestTarget {
  root: PublicAssetRoot;
  subpath?: string | null;
}

interface PublicAssetManifestItemDto {
  id: string;
  root: PublicAssetRoot;
  name: string;
  extension: string;
  kind: PublicAssetKind;
  relativePath: string;
  rootRelativePath: string;
  absolutePath: string;
  bytes: number;
}

interface PublicAssetManifestDto {
  root: PublicAssetRoot;
  subpath?: string | null;
  totalCount: number;
  items: PublicAssetManifestItemDto[];
}

export interface PublicAssetLibraryLoadOptions {
  forceRefresh?: boolean;
  moduleId?: TlantiModuleId | null;
  rootFilter?: 'all' | PublicAssetRoot;
}

const assetLibraryCache = new Map<string, Promise<PublicAssetLibraryItem[]>>();

const PUBLIC_ROOT_KEYS = new Set<PublicAssetRoot>(PUBLIC_ASSET_LIBRARY_ROOTS.map((root) => root.key));

function getExtension(name: string) {
  const raw = name.split('.').pop()?.toLowerCase() ?? '';
  return raw;
}

function inferKind(extension: string): PublicAssetKind {
  if (IMAGE_EXTENSIONS.has(extension)) return 'image';
  if (VECTOR_EXTENSIONS.has(extension)) return 'vector';
  if (AUDIO_EXTENSIONS.has(extension)) return 'audio';
  if (MODEL_EXTENSIONS.has(extension)) return 'model';
  if (XML_EXTENSIONS.has(extension)) return 'xml';
  if (PRESET_EXTENSIONS.has(extension)) return 'preset';
  if (EFFECT_EXTENSIONS.has(extension)) return 'effect';
  if (BINARY_EXTENSIONS.has(extension)) return 'binary';
  return 'document';
}

function normalizePathSlashes(value: string) {
  return value.replace(/\\/g, '/');
}

function parsePublicAssetTarget(path: string): PublicAssetManifestTarget | null {
  const normalized = normalizePathSlashes(path);
  const segments = normalized.split('/').filter(Boolean);
  if (!segments.length || segments[0] !== 'public' || segments.length < 2) {
    return null;
  }

  const root = segments[1] as PublicAssetRoot;
  if (!PUBLIC_ROOT_KEYS.has(root)) {
    return null;
  }

  return {
    root,
    subpath: segments.length > 2 ? segments.slice(2).join('/') : null,
  };
}

function humanizeAssetName(name: string) {
  return name
    .replace(/\.[^.]+$/, '')
    .replace(/[_+.-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function supportsCad(kind: PublicAssetKind, extension: string) {
  if (kind === 'image' || kind === 'vector') {
    return ['png', 'jpg', 'jpeg', 'webp', 'avif', 'svg'].includes(extension);
  }

  if (kind === 'model') {
    return ['stl', 'obj', 'ply', 'glb', 'gltf'].includes(extension);
  }

  return false;
}

function supportsDb(kind: PublicAssetKind) {
  return !['binary', 'effect'].includes(kind);
}

function targetKey(target: PublicAssetManifestTarget) {
  return `${target.root}:${target.subpath ?? ''}`;
}

function manifestTargetForPlacement(placement: AssetPlacementDefinition): PublicAssetManifestTarget | null {
  const rootDefinition = CLINICAL_ASSET_LIBRARY_ROOTS[placement.rootId];
  const baseTarget = parsePublicAssetTarget(rootDefinition.stableTargetPath);
  if (!baseTarget) {
    return null;
  }

  const subpathParts = [baseTarget.subpath, placement.subpath].filter((value): value is string => Boolean(value && value.trim()));

  return {
    root: baseTarget.root,
    subpath: subpathParts.length ? subpathParts.join('/') : null,
  };
}

function collapseTargets(targets: PublicAssetManifestTarget[]) {
  const rootLevelQueries = new Set(targets.filter((target) => !target.subpath).map((target) => target.root));
  const deduped = new Map<string, PublicAssetManifestTarget>();

  for (const target of targets) {
    if (rootLevelQueries.has(target.root) && target.subpath) {
      continue;
    }
    deduped.set(targetKey(target), target);
  }

  return [...deduped.values()];
}

function getTargetsForModule(moduleId: TlantiModuleId, rootFilter: 'all' | PublicAssetRoot) {
  const targets = listAssetPlacementsForModule(moduleId)
    .map(manifestTargetForPlacement)
    .filter((target): target is PublicAssetManifestTarget => Boolean(target))
    .filter((target) => rootFilter === 'all' || target.root === rootFilter);

  return collapseTargets(targets);
}

function getTargets(rootFilter: 'all' | PublicAssetRoot, moduleId?: TlantiModuleId | null) {
  if (moduleId) {
    const moduleTargets = getTargetsForModule(moduleId, rootFilter);
    if (moduleTargets.length) {
      return moduleTargets;
    }
  }

  if (rootFilter === 'all') {
    return PUBLIC_ASSET_LIBRARY_ROOTS.map((root) => ({ root: root.key, subpath: null }));
  }

  return [{ root: rootFilter, subpath: null }];
}

function toLibraryItem(item: PublicAssetManifestItemDto): PublicAssetLibraryItem {
  const extension = item.extension || getExtension(item.name);
  const kind = item.kind || inferKind(extension);
  const semantic = derivePublicAssetSemanticProfile({
    root: item.root,
    name: item.name,
    relativePath: item.relativePath,
    kind,
    extension,
  });

  return {
    id: item.id,
    root: item.root,
    name: item.name,
    label: humanizeAssetName(item.name),
    extension,
    kind,
    relativePath: item.relativePath,
    rootRelativePath: item.rootRelativePath,
    absolutePath: item.absolutePath,
    bytes: item.bytes ?? null,
    previewUrl: ['image', 'vector', 'audio'].includes(kind) ? convertFileSrc(item.absolutePath) : null,
    supportedInCad: supportsCad(kind, extension),
    supportedInDb: supportsDb(kind),
    semanticUsage: semantic.usage,
    semanticLabel: semantic.label,
    semanticDescription: semantic.description,
    autoTags: semantic.autoTags,
    semanticFamilies: semantic.families,
    searchableText: `${item.root} ${item.rootRelativePath} ${humanizeAssetName(item.name)} ${semantic.autoTags.join(' ')} ${semantic.families.join(' ')}`.toLowerCase(),
  };
}

async function loadManifestTarget(target: PublicAssetManifestTarget, forceRefresh = false) {
  const key = targetKey(target);
  if (forceRefresh) {
    assetLibraryCache.delete(key);
  }

  if (!assetLibraryCache.has(key)) {
    assetLibraryCache.set(key, (async () => {
      const { invoke } = await import('@tauri-apps/api/core');
      const manifest = await invoke<PublicAssetManifestDto>('get_public_asset_manifest', {
        query: {
          root: target.root,
          subpath: target.subpath ?? null,
          forceRefresh,
        },
      });
      return manifest.items.map(toLibraryItem);
    })());
  }

  return assetLibraryCache.get(key)!;
}

export async function loadPublicAssetLibrary(options: PublicAssetLibraryLoadOptions = {}) {
  if (!isTauriRuntime()) {
    return [];
  }

  const rootFilter = options.rootFilter ?? 'all';
  const targets = getTargets(rootFilter, options.moduleId);
  const results = await Promise.all(targets.map((target) => loadManifestTarget(target, options.forceRefresh ?? false)));
  const deduped = new Map<string, PublicAssetLibraryItem>();

  for (const item of results.flat()) {
    deduped.set(item.id, item);
  }

  return [...deduped.values()].sort((left, right) => left.relativePath.localeCompare(right.relativePath));
}

export function listPublicAssetRootsForModule(moduleId?: TlantiModuleId | null) {
  if (!moduleId) {
    return PUBLIC_ASSET_LIBRARY_ROOTS.map((root) => root.key);
  }

  const rootKeys = new Set(getTargetsForModule(moduleId, 'all').map((target) => target.root));
  return PUBLIC_ASSET_LIBRARY_ROOTS.filter((root) => rootKeys.has(root.key)).map((root) => root.key);
}

export function isPreviewablePublicAsset(item: PublicAssetLibraryItem) {
  return item.kind === 'image' || item.kind === 'vector' || item.kind === 'audio';
}
