// Generated by Copilot
import { isTauriRuntime } from '@/platform/desktop-system';

export interface RuntimeDiagnostics {
  tauriVersion: string;
  viteVersion: string;
  reactVersion: string;
  reactDomVersion: string;
  platform: string;
  architecture: string;
  hostname: string;
  workspaceLocation: string;
  caseLocation: string;
}

async function getOsDiagnostics() {
  if (!isTauriRuntime()) {
    return {
      platform: typeof navigator !== 'undefined' ? navigator.userAgent : 'Browser runtime',
      architecture: typeof navigator !== 'undefined' ? navigator.platform : 'unknown',
      hostname: typeof window !== 'undefined' ? window.location.hostname : 'localhost',
    };
  }

  try {
    const [{ platform, arch, hostname }] = await Promise.all([
      import('@tauri-apps/plugin-os'),
    ]);

    return {
      platform: await platform(),
      architecture: await arch(),
      hostname: (await hostname()) ?? 'unknown',
    };
  } catch {
    return {
      platform: 'desktop-runtime',
      architecture: 'unknown',
      hostname: 'unknown',
    };
  }
}

export async function getRuntimeDiagnostics(input: {
  caseLocation?: string | null;
  workspaceLocation?: string | null;
}): Promise<RuntimeDiagnostics> {
  const os = await getOsDiagnostics();

  return {
    tauriVersion: '2.10.3',
    viteVersion: '6.2.0',
    reactVersion: '19.2.3',
    reactDomVersion: '19.2.3',
    platform: os.platform,
    architecture: os.architecture,
    hostname: os.hostname,
    workspaceLocation: input.workspaceLocation ?? (typeof window !== 'undefined' ? window.location.origin : 'unknown'),
    caseLocation: input.caseLocation ?? 'No local case path saved yet',
  };
}

export function formatRuntimeDiagnostics(input: RuntimeDiagnostics) {
  return [
    'TlantiCAD Dental Studio Diagnostics',
    `Tauri: ${input.tauriVersion}`,
    `Vite: ${input.viteVersion}`,
    `React: ${input.reactVersion}`,
    `React DOM: ${input.reactDomVersion}`,
    `Platform: ${input.platform}`,
    `Architecture: ${input.architecture}`,
    `Hostname: ${input.hostname}`,
    `Workspace: ${input.workspaceLocation}`,
    `Active case path: ${input.caseLocation}`,
  ].join('\n');
}

export async function exportRuntimeDiagnosticsReport(contents: string, suggestedName = 'tlanticad-crash-report.txt') {
  if (!isTauriRuntime()) {
    const blob = new Blob([contents], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = suggestedName;
    anchor.click();
    URL.revokeObjectURL(url);
    return suggestedName;
  }

  const [{ save }, { writeTextFile }] = await Promise.all([
    import('@tauri-apps/plugin-dialog'),
    import('@tauri-apps/plugin-fs'),
  ]);

  const targetPath = await save({
    title: 'Save diagnostics report',
    defaultPath: suggestedName,
    filters: [{ name: 'Text', extensions: ['txt'] }],
  });

  if (!targetPath) {
    return null;
  }

  await writeTextFile(targetPath, contents);
  return targetPath;
}
