// Generated by Copilot
export interface TimeZoneGroup {
  label: string;
  zones: string[];
}

const SOUTH_AMERICA_HINTS = [
  'Argentina',
  'Araguaina',
  'Asuncion',
  'Bahia',
  'Belem',
  'Boa_Vista',
  'Bogota',
  'Buenos_Aires',
  'Campo_Grande',
  'Caracas',
  'Cayenne',
  'Chile',
  'Cordoba',
  'Cuiaba',
  'Eirunepe',
  'Fortaleza',
  'Guayaquil',
  'Guyana',
  'La_Paz',
  'Lima',
  'Maceio',
  'Manaus',
  'Montevideo',
  'Noronha',
  'Paramaribo',
  'Porto_Velho',
  'Recife',
  'Rio_Branco',
  'Santarem',
  'Santiago',
  'Sao_Paulo',
];

const NORTH_AND_CENTRAL_HINTS = [
  'Adak',
  'Anchorage',
  'Anguilla',
  'Antigua',
  'Aruba',
  'Atikokan',
  'Bahamas',
  'Barbados',
  'Belize',
  'Blanc-Sablon',
  'Boise',
  'Cambridge_Bay',
  'Cancun',
  'Cayman',
  'Chicago',
  'Costa_Rica',
  'Creston',
  'Curacao',
  'Danmarkshavn',
  'Dawson',
  'Denver',
  'Detroit',
  'Dominica',
  'Edmonton',
  'El_Salvador',
  'Glace_Bay',
  'Goose_Bay',
  'Grand_Turk',
  'Grenada',
  'Guadeloupe',
  'Guatemala',
  'Halifax',
  'Havana',
  'Hermosillo',
  'Indiana',
  'Inuvik',
  'Iqaluit',
  'Jamaica',
  'Juneau',
  'Kentucky',
  'Knox_IN',
  'Los_Angeles',
  'Managua',
  'Martinique',
  'Matamoros',
  'Mazatlan',
  'Menominee',
  'Merida',
  'Metlakatla',
  'Mexico_City',
  'Miquelon',
  'Moncton',
  'Monterrey',
  'Montserrat',
  'Nassau',
  'New_York',
  'Nipigon',
  'Nome',
  'Ojinaga',
  'Panama',
  'Phoenix',
  'Port-au-Prince',
  'Port_of_Spain',
  'Puerto_Rico',
  'Rainy_River',
  'Rankin_Inlet',
  'Regina',
  'Resolute',
  'Santo_Domingo',
  'Sitka',
  'St_Barthelemy',
  'St_Johns',
  'St_Kitts',
  'St_Lucia',
  'St_Thomas',
  'St_Vincent',
  'Swift_Current',
  'Tegucigalpa',
  'Thule',
  'Thunder_Bay',
  'Tijuana',
  'Toronto',
  'Tortola',
  'Vancouver',
  'Whitehorse',
  'Winnipeg',
  'Yakutat',
];

function sortZones(zones: string[]) {
  return [...zones].sort((left, right) => left.localeCompare(right));
}

function buildLabel(zone: string) {
  return zone.replace(/_/g, ' ');
}

export function getGroupedTimeZones() {
  const zones = typeof Intl !== 'undefined' && typeof Intl.supportedValuesOf === 'function'
    ? Intl.supportedValuesOf('timeZone')
    : ['UTC'];

  const groups: Record<string, string[]> = {
    'América del Norte y Centro': [],
    'Sudamérica': [],
    'Europa': [],
    'África': [],
    'Asia': [],
    'Oceanía': [],
    'UTC y otros': [],
  };

  zones.forEach((zone) => {
    if (zone.startsWith('Europe/')) {
      groups['Europa'].push(zone);
      return;
    }

    if (zone.startsWith('Africa/')) {
      groups['África'].push(zone);
      return;
    }

    if (zone.startsWith('Asia/')) {
      groups['Asia'].push(zone);
      return;
    }

    if (zone.startsWith('Australia/') || zone.startsWith('Pacific/')) {
      groups['Oceanía'].push(zone);
      return;
    }

    if (zone.startsWith('America/')) {
      const city = zone.slice('America/'.length);
      if (SOUTH_AMERICA_HINTS.some((hint) => city.includes(hint))) {
        groups['Sudamérica'].push(zone);
      } else if (NORTH_AND_CENTRAL_HINTS.some((hint) => city.includes(hint))) {
        groups['América del Norte y Centro'].push(zone);
      } else {
        groups['América del Norte y Centro'].push(zone);
      }
      return;
    }

    groups['UTC y otros'].push(zone);
  });

  return Object.entries(groups)
    .map(([label, zoneList]) => ({ label, zones: sortZones(zoneList) }))
    .filter((group) => group.zones.length)
    .map((group) => ({
      ...group,
      zones: group.zones.map((zone) => `${zone}`),
    }));
}

export function formatTimeZoneLabel(zone: string) {
  return buildLabel(zone);
}
