// Generated by Copilot
import type { TlantiCaseAssetCategory, TlantiCaseAssetRole } from '@/stores/tlantidb-case-store';

const ROLE_PATTERNS: Array<{ role: TlantiCaseAssetRole; patterns: RegExp[] }> = [
  { role: 'pre-op-photo', patterns: [/pre[-_ ]?op/i, /portrait/i, /face/i] },
  { role: 'smile-photo', patterns: [/smile/i, /photo/i, /frontal/i] },
  { role: 'shade-reference', patterns: [/shade/i, /vita/i, /color/i] },
  { role: 'prep-scan', patterns: [/prep/i, /preparation/i, /abutment/i] },
  { role: 'antagonist-scan', patterns: [/antagon/i, /oppos/i] },
  { role: 'bite-registration', patterns: [/bite/i, /occlusion/i, /occlusal/i] },
  { role: 'gingiva-scan', patterns: [/gingiva/i, /tissue/i, /soft[-_ ]?tissue/i] },
  { role: 'dicom-study', patterns: [/dicom/i, /cbct/i, /ct/i, /scan/i] },
  { role: 'consent-document', patterns: [/consent/i, /authorization/i] },
  { role: 'lab-prescription', patterns: [/rx/i, /prescription/i, /lab[-_ ]?order/i, /order/i] },
  { role: 'manufacturing-report', patterns: [/report/i, /mill/i, /manufactur/i, /interop/i, /xml/i] },
  { role: 'restoration-model', patterns: [/stl/i, /mesh/i, /model/i, /crown/i, /bridge/i, /guide/i] },
];

export function inferClinicalAssetRole(fileName: string, category: TlantiCaseAssetCategory): TlantiCaseAssetRole {
  const normalized = fileName.toLowerCase();
  const detected = ROLE_PATTERNS.find((item) => item.patterns.some((pattern) => pattern.test(normalized)));
  if (detected) {
    return detected.role;
  }

  switch (category) {
    case 'dicom':
      return 'dicom-study';
    case 'model':
      return 'restoration-model';
    case 'image':
      return 'clinical-photo';
    case 'report':
      return 'manufacturing-report';
    case 'document':
    default:
      return 'clinical-note';
  }
}

export function inferClinicalAssetTags(fileName: string, category: TlantiCaseAssetCategory) {
  const tags = new Set<string>([category]);
  const normalized = fileName.toLowerCase();

  if (/upper|maxilla/i.test(normalized)) tags.add('upper');
  if (/lower|mandible/i.test(normalized)) tags.add('lower');
  if (/left/i.test(normalized)) tags.add('left');
  if (/right/i.test(normalized)) tags.add('right');
  if (/temp|temporary/i.test(normalized)) tags.add('temporary');
  if (/final/i.test(normalized)) tags.add('final');
  if (/implant/i.test(normalized)) tags.add('implant');
  if (/bridge/i.test(normalized)) tags.add('bridge');
  if (/crown/i.test(normalized)) tags.add('crown');
  if (/guide/i.test(normalized)) tags.add('guide');
  if (/photo|jpeg|jpg|png|webp/i.test(normalized)) tags.add('photo');
  if (/pdf|report/i.test(normalized)) tags.add('report');

  return Array.from(tags);
}

export function normalizeAssetTags(input: string) {
  return Array.from(new Set(input.split(',').map((item) => item.trim().toLowerCase()).filter(Boolean)));
}

export const CLINICAL_ASSET_ROLE_LABELS: Record<TlantiCaseAssetRole, string> = {
  'clinical-photo': 'Clinical photo',
  'pre-op-photo': 'Pre-op photo',
  'smile-photo': 'Smile photo',
  'shade-reference': 'Shade reference',
  'prep-scan': 'Prep scan',
  'antagonist-scan': 'Antagonist scan',
  'bite-registration': 'Bite registration',
  'gingiva-scan': 'Gingiva scan',
  'dicom-study': 'DICOM study',
  'consent-document': 'Consent document',
  'lab-prescription': 'Lab prescription',
  'clinical-note': 'Clinical note',
  'manufacturing-report': 'Manufacturing report',
  'restoration-model': 'Restoration model',
  other: 'Other',
};
