// Generated by Copilot
import type { SystemRuntimeReport } from '@/lib/backend-integrations';
import type {
  TlantiDbPerformanceProfile,
  TlantiDbRenderQuality,
  TlantiDbThumbnailQuality,
} from '@/stores/tlantidb-case-store';

function normalizeRenderQuality(value: string): TlantiDbRenderQuality {
  if (value === 'ultra' || value === 'high' || value === 'medium') {
    return value;
  }

  return 'low';
}

function normalizeThumbnailQuality(value: string): TlantiDbThumbnailQuality {
  if (value === 'high' || value === 'medium') {
    return value;
  }

  return 'low';
}

export function buildMachineSignature(report: SystemRuntimeReport) {
  const gpuKey = report.system.gpus[0]?.name ?? 'no-gpu';
  return [
    report.system.os.name,
    report.system.os.arch,
    report.system.cpu.brand,
    gpuKey,
    report.system.memory.totalBytes,
  ].join('::');
}

export function derivePerformanceProfileFromRuntimeReport(report: SystemRuntimeReport): TlantiDbPerformanceProfile {
  const recommended = report.aiWorkload.recommendedSettings;

  return {
    mode: 'auto',
    source: 'auto',
    renderQuality: normalizeRenderQuality(recommended.renderQuality),
    dicomCacheMb: Math.max(256, Math.min(4096, recommended.dicomCacheMb)),
    enableGpuInference: recommended.enableGpuInference,
    enable3dViewer: recommended.enable3dViewer,
    enableCbctViewer: recommended.enableCbctViewer,
    maxConcurrentImports: Math.max(1, Math.min(8, recommended.maxConcurrentImports)),
    thumbnailQuality: normalizeThumbnailQuality(recommended.thumbnailQuality),
    overallScore: report.aiWorkload.workloadScores.overall,
    machineSignature: buildMachineSignature(report),
    lastAutoAppliedAt: new Date().toISOString(),
  };
}

export function shouldAutoApplyRuntimeProfile(
  currentProfile: TlantiDbPerformanceProfile,
  report: SystemRuntimeReport,
) {
  if (currentProfile.mode !== 'auto') {
    return false;
  }

  const nextSignature = buildMachineSignature(report);
  return currentProfile.machineSignature !== nextSignature || currentProfile.source === 'default';
}
