// Generated by Copilot
import type { TlantiCase, TlantiDbPreferences, TlantiDbState } from '@/stores/tlantidb-case-store';

export interface TlantiDbSearchResult {
  id: string;
  kind: 'case' | 'setting' | 'action';
  label: string;
  description: string;
  keywords: string[];
  caseId?: string;
  actionId?: 'open-settings' | 'open-case' | 'toggle-language';
}

function normalize(value: string) {
  return value.toLowerCase().trim();
}

function buildSettingResults(preferences: TlantiDbPreferences): TlantiDbSearchResult[] {
  return [
    {
      id: 'setting-timezone',
      kind: 'setting',
      label: 'Timezone y región',
      description: `Zona horaria actual: ${preferences.timeZone}`,
      keywords: ['timezone', 'region', 'hora', 'zona horaria', preferences.timeZone],
      actionId: 'open-settings',
    },
    {
      id: 'setting-language',
      kind: 'setting',
      label: 'Idioma del workspace',
      description: 'Configurar idioma, nomenclatura y preferencias regionales futuras.',
      keywords: ['idioma', 'language', 'fdi', 'international', 'numeracion'],
      actionId: 'open-settings',
    },
    {
      id: 'setting-windows',
      kind: 'setting',
      label: 'Ventanas y sincronización',
      description: preferences.openModulesInNewWindow
        ? 'Multiventana del sistema habilitada.'
        : 'Multiventana del sistema deshabilitada.',
      keywords: ['window', 'ventana', 'multiventana', 'sync', 'sincronizacion'],
      actionId: 'open-settings',
    },
    {
      id: 'setting-assets',
      kind: 'setting',
      label: 'Assets, XML y paquetes de caso',
      description: 'Futuro punto de entrada para exportación XML y assets clínicos.',
      keywords: ['xml', 'assets', 'package', 'paquete', 'archivo caso'],
      actionId: 'open-settings',
    },
    {
      id: 'setting-runtime-performance',
      kind: 'setting',
      label: 'AI, render y cache adaptativos',
      description: `Perfil actual: ${preferences.performanceProfile.renderQuality} · ${preferences.performanceProfile.dicomCacheMb} MB cache · modo ${preferences.performanceProfile.mode}.`,
      keywords: ['runtime', 'performance', 'ai', 'render', 'cache', 'gpu', 'cbct', 'machine profile', 'adaptive'],
      actionId: 'open-settings',
    },
    {
      id: 'setting-user',
      kind: 'setting',
      label: 'Usuario, laboratorio y estaciones',
      description: 'Preferencias de operador, laboratorio y dispositivo.',
      keywords: ['usuario', 'user', 'lab', 'laboratorio', 'estacion'],
      actionId: 'open-settings',
    },
  ];
}

function buildCaseResult(caseItem: TlantiCase): TlantiDbSearchResult {
  return {
    id: `case-${caseItem.id}`,
    kind: 'case',
    label: `${caseItem.caseNumber} · ${caseItem.name}`,
    description: `${caseItem.clientName} · ${caseItem.status} · ${caseItem.materialShade}`,
    keywords: [
      caseItem.caseNumber,
      caseItem.name,
      caseItem.clientName,
      caseItem.clientId,
      caseItem.technicianName,
      caseItem.materialShade,
      ...caseItem.tags,
    ],
    caseId: caseItem.id,
    actionId: 'open-case',
  };
}

export function searchTlantiDb(state: TlantiDbState, query: string): TlantiDbSearchResult[] {
  const normalizedQuery = normalize(query);
  if (!normalizedQuery) {
    return [];
  }

  const allResults: TlantiDbSearchResult[] = [
    ...state.cases.map(buildCaseResult),
    ...buildSettingResults(state.preferences),
    {
      id: 'action-settings',
      kind: 'action' as const,
      label: 'Abrir configuración general',
      description: 'Idioma, ventanas, sincronización, XML y opciones futuras.',
      keywords: ['settings', 'config', 'preferencias', 'general'],
      actionId: 'open-settings' as const,
    },
  ];

  return allResults
    .filter((result) => {
      const haystack = normalize(`${result.label} ${result.description} ${result.keywords.join(' ')}`);
      return haystack.includes(normalizedQuery);
    })
    .slice(0, 8);
}
