// Generated by Copilot
import type { AppWorkspaceId } from '@/components/workspaces/workspace.config';

export interface WorkspaceLaunchContext {
  workspace: AppWorkspaceId;
  caseId?: string;
  module?: string;
  title?: string;
}

const WORKSPACE_ALIASES: Record<string, AppWorkspaceId> = {
  cad: 'tlanticad',
  tlanticad: 'tlanticad',
  'tlanti-cad': 'tlanticad',
  db: 'tlantidb',
  tlantidb: 'tlantidb',
  'tlanti-db': 'tlantidb',
  workspace: 'tlantidb',
  preloader: 'tlantidb',
};

export function normalizeWorkspaceId(value?: string | null): AppWorkspaceId {
  if (!value) return 'tlantidb';
  return WORKSPACE_ALIASES[value.trim().toLowerCase()] ?? 'tlantidb';
}

export function getWorkspaceLaunchContext(): WorkspaceLaunchContext {
  if (typeof window === 'undefined') {
    return { workspace: 'tlantidb' };
  }

  const params = new URLSearchParams(window.location.search);
  const workspace = normalizeWorkspaceId(params.get('workspace'));
  const module = params.get('module') ?? undefined;

  return {
    workspace,
    caseId: params.get('caseId') ?? undefined,
    module: workspace === 'tlanticad' ? module : undefined,
    title: params.get('title') ?? undefined,
  };
}

export function buildWorkspaceUrl(context: WorkspaceLaunchContext): string {
  const url = new URL(typeof window !== 'undefined' ? window.location.href : 'http://127.0.0.1:1420/');
  url.searchParams.set('workspace', context.workspace);

  if (context.caseId) {
    url.searchParams.set('caseId', context.caseId);
  } else {
    url.searchParams.delete('caseId');
  }

  if (context.workspace === 'tlanticad' && context.module) {
    url.searchParams.set('module', context.module);
  } else {
    url.searchParams.delete('module');
  }

  if (context.workspace === 'tlanticad' && context.title) {
    url.searchParams.set('title', context.title);
  } else {
    url.searchParams.delete('title');
  }

  return `${url.pathname}${url.search}${url.hash}`;
}
