// Generated by Copilot
import React, { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { cn } from '../lib/utils';
import { ThemeMode } from '../types';
import type { AppWorkspaceId } from './workspace.config';
import type { WorkspacePreloaderPhase } from '@/lib/workspace-orchestrator';

interface TlantiWorkspacePreloaderProps {
  visible?: boolean;
  title?: string;
  subtitle: string;
  themeMode: ThemeMode;
  phase?: WorkspacePreloaderPhase;
  workspace?: AppWorkspaceId;
  caseId?: string;
  moduleId?: string;
}

export const TlantiWorkspacePreloader: React.FC<TlantiWorkspacePreloaderProps> = ({
  visible = true,
  title = 'TlantiCAD',
  subtitle,
  themeMode,
  phase = 'boot',
  workspace,
  caseId,
  moduleId,
}) => {
  const [hasMounted, setHasMounted] = useState(false);

  useEffect(() => {
    setHasMounted(true);
  }, []);

  const statusItems = hasMounted
    ? [
        workspace ? (workspace === 'tlanticad' ? 'TlantiCAD' : 'TlantiDB') : null,
        moduleId ?? null,
        caseId ? `case ${caseId.slice(0, 8)}` : null,
        phase,
      ].filter(Boolean)
    : [phase];

  return (
    <AnimatePresence>
      {visible && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2, ease: 'easeOut' }}
          className={cn(
            'fixed inset-0 z-50 flex h-dvh w-full items-center justify-center',
            themeMode === 'dark' ? 'bg-black text-text-primary' : 'bg-black text-text-primary'
          )}
        >
          <div className="flex flex-col items-center gap-6 px-6 text-center">
            <div className="relative flex size-28 items-center justify-center">
              <motion.div
                aria-hidden="true"
                animate={{ rotate: 360 }}
                transition={{ duration: 1.6, ease: 'linear', repeat: Infinity }}
                className={cn(
                  'absolute inset-0 rounded-full border-4 border-transparent',
                  themeMode === 'dark'
                    ? 'border-t-text-display border-r-border-visible'
                    : 'border-t-text-display border-r-border-visible'
                )}
              />
              <div className="font-display text-4xl font-semibold text-text-display text-balance">TL</div>
            </div>

            <div className="space-y-2">
              <h1 className="font-display text-4xl font-semibold text-text-display text-balance md:text-5xl">
                {title}
              </h1>
              <p className="font-mono text-sm uppercase text-text-secondary tabular-nums text-pretty md:text-base">
                {subtitle}
              </p>
              <div className="flex flex-wrap items-center justify-center gap-2 pt-2">
                {statusItems.map((item) => (
                  <span
                    key={item}
                    className="rounded-sm border border-border bg-surface-raised px-2 py-1 font-mono text-[10px] uppercase tracking-[0.16em] text-text-secondary"
                  >
                    {item}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};
